### ISSUE TITLE
Improve drag & drop in tab view grid

### ISSUE THREAD

**Issue by kljohann** [josh-berry/tab-stash#101]
### Problem Statement
When a folder with few entries is adjacent to a folder with many tabs in the stash grid, both have the same height but the blank space at the bottom does not accept dragged items. Instead, tabs have to be dropped on top of or next to an existing entry.

### Preferred Solution(s)
Adjust CSS to grow `.folders .contents .tabs` according to the available height in `.tab-view .folder .contents`. The `Draggable` element in `folder.vue` would then be larger.

Thinking about it, it would probably be natural if the drop target covered the complete folder, s.t. it would also be possible to drop an item on e.g. the folder name. (Allowing to drag items to collapsed folders might lead to confusion, though.)

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for writing the issue! I do see what you mean about wanting to drop a tab anywhere in the blank space in the tab view.

IIRC when I was first writing the tab view, I tried doing this, but it caused another styling problem. I now can't remember what the problem was, and I just haven't gotten back to it since then. But I totally agree it would be much easier to drop a tab anywhere in the blank space. So I'll try to revisit this again soon. Thanks again!

**Comment by josh-berry** [comment]
Should be fixed in the next release. Thanks again for the report!

**Comment by kljohann** [comment]
Thanks for the fix and tab stash in general—it's wonderful! I haven't tested the change yet, but it looks similar to what I hacked together locally by using the dev tools on the tab stash page. (The use of `.tabs:last-child` sounds like a nice idea to avoid artifacts in the filtered view.)
