### ISSUE TITLE
Tab stash doesn't restore tabs to correct container

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#104]
Firefox has a new feature: containers for tabs, but TabStash doesn't seem to support it.

**Comment by josh-berry** [comment]
Right—because Tab Stash stores your websites as bookmarks, there is no way for it to remember which tabs belong to what containers, since there is no way for Tab Stash to store any extra information along with the bookmarks it creates.

However, Firefox Multi-Account Containers (MAC) itself takes care of this. All you need to do is assign a site to a particular container in MAC. This is more secure than having individual extensions (like Tab Stash) do it because MAC can ensure the same site is always opened in the same container, avoiding inadvertent leaking of cookies, browser history, etc.

**Comment by okjed** [comment]
I will say there is something to be said for capturing the container details as they're stashed. Tabs Aside does it by placing the container id inside of brackets so that the bookmark method still works and recovery to the right container is captured. I have certain Google Docs links I want to open in one container vs others in a different container... so MAC's approach won't work.
