### ISSUE TITLE
Option to manually enable dark mode

### ISSUE THREAD

**Issue by gegnew** [josh-berry/tab-stash#108]
### Question
Despite having a dark theme enabled, the Tab Stash sidebar is still light. Is there something I'm missing?

### System Details
- **Firefox Version:** 84.0.2
- **Tab Stash Version:** 2.7.1

**Comment by josh-berry** [comment]
Hi,

For whatever reason, Firefox chooses whether to use light or dark colors based on your system's light/dark theme, rather than Firefox's light or dark theme. So it could be that if your Firefox theme is dark but your system theme is light, Firefox will still choose to use the light theme for Tab Stash.

Can you double-check your system theme? If it's a light theme, that's probably the culprit.

**Comment by IAmNotAJerk** [comment]
I encounter a similar issue. My "system theme" is set to dark, Tab Stash used to be shown in dark mode but since I installed some userchrome.css, it Tab Stash is now no longer respecting that "system theme" of firefox. 
Any chance can you include theme changing in the option menu, with options like "1, Default (according to system); 2, Light; 3, Dark" to have a forced theme on the Tab Stash side when users encounter Firefox bugs?

**Comment by josh-berry** [comment]
> Any chance can you include theme changing in the option menu, with options like "1, Default (according to system); 2, Light; 3, Dark" to have a forced theme on the Tab Stash side when users encounter Firefox bugs?
> 
> Extra details:
> The way Firefox handled light and dark theme is still very confusing and sometimes buggy. Please refer to the discussion I've found:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1529323
> So, maybe not solely relying on that feature is a wiser choice.

Yes, this is a good point, and I'll look into this for a future release. Thanks!

**Comment by josh-berry** [comment]
In the next release, you'll have the option to manually force Tab Stash to use a light or a dark theme. Hope this helps!

**Comment by dquesadacr** [comment]
Beautiful! Thank you!
