### ISSUE TITLE
Ability to save and load stashes as html/opml/bookmark 

### ISSUE THREAD

**Issue by timoc** [josh-berry/tab-stash#11]
**Is your feature request related to a problem? Please describe.**
when researching a topic, i would like to be able to create a stash for that topic, and then save the stash for later research or sharing with a firefox/browser that is not in sync with this one.

**Describe the solution you'd like**
A menu option to save, load, append, replace items from a stash as bookmarks.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by josh-berry** [comment]
Hi Tim, since Tab Stash already saves all your stashed tabs as bookmarks, you can use Firefox's built in bookmark import/export feature to get an HTML or JSON file containing all your stashed tabs and other bookmarks.

Both HTML and JSON options are available in the Bookmarks library (Firefox menu > Library > Bookmarks > Show All Bookmarks). In the "import/backup" menu (the toolbar icon that looks like a star), the "Backup..." option gives you JSON, and the "Export..." option gives you HTML.

Does this address your problem or did you have something else in mind?

**Comment by timoc** [comment]
I had something else in mind. I want to be able to save and load a subset (stash worth) of bookmarks, so i can:
- share the stash with others
- use the stash for research material in a project folder
- export a stash of bookmarks that are no longer of use, but want to archive.

**Comment by josh-berry** [comment]
Got it, thanks for the clarification. I agree this could be useful to have, and I've heard one or two other requests for something similar. Will put this in my backlog for a future release.

**Comment by selster** [comment]
I would also be like to be able to save a "stash specific" file, one that could be restored, one that would look like my "stashes" when restored.  This is different, it seems to me, than saving bookmarks per se.

**Comment by josh-berry** [comment]
Import/export will be available in a variety of formats in the next Tab Stash release. :) For now, export works via simple copy-and-paste--your stashes will be displayed in the format you choose, and you can select the portion that you care about for pasting into email, notes, files, etc.
