### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by AussieGit** [josh-berry/tab-stash#111]
### Question
How can I contribute to one of my top 5 Firefox extensions? I have troubles spelling "Code" let alone coding so is there some way I can contribute financially?

### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Comment by josh-berry** [comment]
I don't have a way to accept monetary contributions right now, I'm afraid.

In terms of other ways to contribute, I always love to hear feedback--both positive and negative--on how folks are using Tab Stash, what works, what doesn't, etc. GitHub issues are the best way to do this, although email works too for anything you don't want to share publicly (tab-stash AT condordes DOT net). And of course, if you know anyone who might genuinely benefit from using it, please feel free to share it with them.

But most importantly, thank you for the thought. I really, truly appreciate it--a kind word goes a long way! 😄

**Comment by optorun** [comment]
Hey,

First of, I'm sorry if this comment open up this request again. I think it might be better to answer there instead of pooping up a new one.

I'm using tab-stash for a few weeks now and love it ! It's a fantastic tool, really useful, yet simple, and I thank you for creating and supporting it. 
I was as well looking for some way to give you back, and found this post. I'll be on the lookout for a potential future Paypal / Patreon / whatever contribute option you'd chose.

So again, thank you ! :)

**Comment by josh-berry** [comment]
@optorun My pleasure, I'm glad you're enjoying it! No worries about the comment, it's always nice to hear from folks. 😄
