### ISSUE TITLE
Adding Visual Indicator for Container tabs

### ISSUE THREAD

**Issue by SixthStreet** [josh-berry/tab-stash#125]
I've begun to use the Tab Stash sidebar permanently open as my primary tab manager and the only thing really missing is visual indicators for container tabs as the normal Firefox tab bar does.  Would adding something be feasible?

**Comment by josh-berry** [comment]
I'll have to look into how/if Firefox reports info about containers to extensions other than the official Multi-Account Containers extension. At the very least, it would probably require Tab Stash to have more permissions.

Also, I'm a little worried that showing the tab coloration might mislead users into thinking that Tab Stash can re-open a stashed tab into the same container. There's no way for Tab Stash to do this right now, because there's no way to save any extra info about the container along with the bookmark which represents the stashed tab. (Adding the container to the URL might be one way around this, but I'd like to avoid saving "special" Tab-Stash-only URLs if at all possible. Otherwise anyone trying to move away from using Tab Stash would have a hard time getting their bookmarks back into a usable state.)

So realistically, it would probably need some support from Firefox to do this in a way that wouldn't be surprising/confusing to users. I'll keep it in mind, though!

**Comment by metasean** [comment]
>I'd like to avoid saving "special" Tab-Stash-only URLs if at all possible

Personally, I'd be fine with this approach if it's the only way to get container support added to Tab Stash (such support would send me over the 🌔 with happiness).  

I'm a hard core container user and the lack of container support is the single biggest challenge that I have with Tab Stash.  Sadly, on more than one occasion, the lack of this feature has led to me having hundreds of tabs open, just so that they stay in their current containers. 😞 

What if the _default_ behavior didn't provide container support, but users could explicitly opt-in to have container support, with the acknowledgement that URLs would be saved in a Tab Stash unique format?

Alternatively, since Firefox bookmarks also include a [tags](https://support.mozilla.org/en-US/kb/categorizing-bookmarks-make-them-easy-to-find) field, could the container simply be added as a tag, e.g. `tab-stash-container | Container's Name` (again, with an explicit opt-in option and acknowledgement that the bookmark includes a tag representing which container it is associated with)?

_Regardless, thank you for creating, maintaining, growing, and open sourcing Tab Stash!_

**Comment by josh-berry** [comment]
> What if the _default_ behavior didn't provide container support, but users could explicitly opt-in to have container support, with the acknowledgement that URLs would be saved in a Tab Stash unique format?

Opt-in might be an option, though I'd prefer to find a way to do it that doesn't require users to fiddle with their settings. I'd be worried that people wouldn't discover the setting and/or get confused by how it will impact their bookmarks.

> Alternatively, since Firefox bookmarks also include a [tags](https://support.mozilla.org/en-US/kb/categorizing-bookmarks-make-them-easy-to-find) field, could the container simply be added as a tag, e.g. `tab-stash-container | Container's Name` (again, with an explicit opt-in option and acknowledgement that the bookmark includes a tag representing which container it is associated with)?

I had that same thought, but unfortunately, the tags field isn't available for browsers to use. I like the idea of putting it in the title instead of the URL, though. I'll give this some thought.

> _Regardless, thank you for creating, maintaining, growing, and open sourcing Tab Stash!_

My pleasure! I'm glad you're finding it useful. 😄

**Comment by josh-berry** [comment]
Thanks to @KerfuffleV2's hard work, the next release will show which container a tab is assigned to. (Though note that Tab Stash still doesn't remember containers.) Once the release is out, you'll have to explicitly turn on this setting in the advanced options.

Do let us know your feedback!

**Comment by josh-berry** [comment]
Since I haven't heard any feedback since 2.11 came out, this will be turned on for everyone in the next release.
