### ISSUE TITLE
Disabling/re-enabling Tab Stash leaves all stashed tabs open

### ISSUE THREAD

**Issue by libricoleur** [josh-berry/tab-stash#128]
### System Details

- **OS Version:** Arch Linux
- **Browser Version:** Firefox Developer Edition 89.0b7 (64 bits)
- **Tab Stash Version:** 2.9

**Installed Browser Extensions:**

- Auto Tab Discard
- Facebook Container
- Tridactyl
- a dozen more probably unrelated

### Describe the Bug

I was temporarily disabling a few browser extensions to resolve an unrelated issue with a website. At some point I disabled Tab Stash, and all the tabs that I had previously stashed showed up again. When I enabled Tab Stash back, all those tabs stayed open.

### Expected Behavior

While I did not expect all my stashed tabs to come back when disabling Tab Stash, I actually expected that re-enabling the extension would close/hide them again.

### Steps to Reproduce

1. Open some tabs
2. Stash them all
3. Disable Tab Stash (in about:addons)
4. Enable Tab Stash back

### Impact

I had hundreds of stashed tabs and seeing them all back made me panic a little bit. I looked for a way to properly hide them again but did not spot any, so I resolved to just stashing them again. I obviously ended up with a new group full of tabs I had already stashed, so I just deleted that new group... which closed all the tabs for good instead of keeping them hidden, making the situation worse.

### Additional Details

While reading issue #106 I learned about the "Close all stashed tabs" button, which is really neat. Had I known of its existence earlier, solving the mess I made would have been a breeze. However, it would have been even better if Tab Stash could handle being disabled and re-enabled more gracefully.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately this behavior of re-opening hidden tabs is built-in to Firefox. It happens because the hidden-tabs feature is something that's meant to be used by extensions, so if no extensions are using it (e.g. because they're disabled or uninstalled), Firefox will turn off the hidden-tabs feature entirely (making your tabs visible again).

I looked into whether there's some cleanup Tab Stash can do beforehand, and unfortunately there isn't. While Firefox does tell extensions they're being unloaded, there's no way to distinguish "unloaded because of the browser quitting" and "unloaded because of the extension being disabled". Worse, there's no way for the extension to delay the process or tell the browser to wait (e.g. to finish cleaning up hidden tabs).

So I'm afraid there's nothing I can do about this, unless Firefox gives extensions more control about when/how they're unloaded. Realistically, I don't expect this to happen, because a malicious extension might be able to abuse any such feature to stay loaded against the user's wishes.

Sorry for the inconvenience and sorry to be the bearer of bad news. :(
