### ISSUE TITLE
Make overview easier in sidebar with smaller fonts, and collapse options.

### ISSUE THREAD

**Issue by timoc** [josh-berry/tab-stash#13]
**Is your feature request related to a problem? Please describe.**
When i have alot of stashes and using ths sidebar, it is difficult to get an overview of them, especially on a laptop because:
- the font size of the stash name is large - can only show 10 closed stashes
- the side-bar always opens with the stashes open
- option to 'sort' the stash order by alpha, number of tabs etc.

**Describe the solution you'd like**
options outlined above.

**Describe alternatives you've considered**
using the stash tab. It has similar options, but removes you from the context of the open tab you are working with.

**Additional context**

**Comment by josh-berry** [comment]
I've been kicking around a couple ideas along these lines that I'd like to implement:
* Remember which groups are expanded/collapsed per browser (so e.g. your work computer can have a different set of stashes showing by default)
* Add an opt-in option for a "compact view" in the sidebar which uses smaller sizes for fonts, icons, etc.

My concern with the "compact view" is it might be a little harder for new users to figure out what's going on, since I would want to auto-hide all the controls for the group, and using smaller sizes might make groups less visually-distinct from the tabs in each group. It's definitely something I want to do—just need to figure out the best way. :)

**Comment by timoc** [comment]
Either sounds good.

**Comment by josh-berry** [comment]
An optional compact style will be available in the next release!
