### ISSUE TITLE
serious performance issues (and an expected easy fix)

### ISSUE THREAD

**Issue by Lanchon** [josh-berry/tab-stash#140]
### System Details

- **OS Version:** linux mint 19.3, latest stable 5.4 kernel
- **Browser Version:** FF 89.0.2
- **Tab Stash Version:** 2.9

### Describe the Bug

i measure the startup time and memory consumption of firefox up to the time it goes idle, with and without tab-stash. FF restores 28 windows with 407 tabs during startup on these tests, with hot caches on a quad-core i7 with 16GB ram. these results were extremely repeatable.

| | clock time | memory used |
|---|---|---|
| tab-stash disabled | 1:10 s | 7.5GB |
| tab-stash enabled | 3:55 s | 11.4GB |
| increase factor | 3.36 times | 1.52 times |

the suspected problem: tab-stash insists on opening itself as a sidebar on every new window, be it restored or opened new. this obtrusive behavior could only be useful for naive first time users, and forcing it down on every user is at best a usability problem. but the immense resource usage it brings with it makes me categorize it as a serious bug because it breaks firefox on some circumstances (see below).

the fix: tab-stash should *never* pop up its sidebar by itself. the trend in browser is unobtrusiveness: less chrome, less clutter. people are perfectly capable of opening a window when they need it; no reason to pop open 28 identical sidebars because the user might need one later. firefox session restore could restore open sidebars **that were open at session save**, but if you ask me, i rather have that disabled too. but tab-stash should absolutely not be popped open in other restored windows. a setting to conditionally retain the current buggy behavior **should not be introduced**: it is dangerous (more below).

tab-stash should not pop open in new windows either (but a setting for this case only would be acceptable).

### More Info

when i first installed tab-stash i had 1000+ tabs opened. it worked ok so i started stashing. i maybe stashed 200 tabs, then had to restart FF due to an update... and then hell was unleashed! even with 200 fewer tabs, tab-stash resource usage was over the limit my system could handle, so my complete system was suddenly brought to its kees. severe thrashing meant no process made progress, and especially FF could not finish opening so i was unable to stash more tabs: i was trapped. i had to kill firefox and use another browser to research how to disable an extension manually by touching the firefox local config dir. then firefox restored my session just fine, and after that i re-enabled tab-stash and then stashed everything i could in a single go -no restarts- until the tab count got really low. then i took the plunge: restart firefox. this time all was fine, i could continue to use tab-stash.

but tab-stash is unsafe: if you are close to your system resource limits and install tab-stash (think about it: too many new users might be in that situation!), and then restart firefox... boom! you are screwed. this is enough of a reason to kill this sidebar-open-by-default thing, even as an option. but as a side benefit, with this change the extension would become more usable and nice.

thanks for your great work on this extension!

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by Lanchon** [comment]
> firefox session restore could restore open sidebars that were open at session save, but if you ask me, i rather have that disabled too.

a reason to disable this that the current version of tab-stash forced all sidebars open (on last session restore), and the newer version would then keep them open, forcing us to go window by window. there is not much value in restoring sidebar state: i will open it when i need it. and open sidebars slow startup a lot.

workaround: after tab-stash is fixed and locally updated, disable the extension to force-close sidebars; then re-enable.

**Comment by Lanchon** [comment]
this might solve:

https://github.com/josh-berry/tab-stash/issues/97
https://github.com/josh-berry/tab-stash/issues/33

**Comment by josh-berry** [comment]
First off, sorry for the trouble and thanks for the detailed write-up. I think there are actually two issues here:

1. The sidebar opening itself when opening a new window
2. Memory usage with vs. without Tab Stash

## 1. Self-opening sidebar

So this behavior is quite perplexing to me, because there is no code in Tab Stash that opens the sidebar on every new window. Not only that, but Firefox *does not allow* extensions to open the sidebar themselves except as the result of [a specific set of user actions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions) (such as clicking the extension's toolbar icon, or choosing one of the extension's context-menu options).

So even if I wanted to put such annoying behavior in Tab Stash, I couldn't. (And I wholeheartedly agree with you that doing so would be a bad idea, even if it were possible.)

All that said, I did a little experimentation, and from what I can tell, Firefox opens the Tab Stash sidebar itself only in these situations:
* If the extension is installed or updated
* If you're opening a new window and the sidebar was already open in the previous window
* You clicked the Sidebar icon in your toolbar, or did some other explicit action to invoke it (which you would know you had done)

So I can only think of two theories as to why this is happening:
* You're opening a new window from a window that already has the sidebar open, so the new window is also getting a sidebar. Or, you have a window *somewhere* with a sidebar open, and so Firefox is getting confused about whether you actually want the sidebar to be opened in a new window or not.
* Firefox somehow thinks Tab Stash wasn't installed correctly, and is trying to reinstall it or complete the installation, and this is resulting in the sidebar being opened.

As far as I know, there is no explicit setting that tells Firefox to open the sidebar by default in new windows (but it's possible I missed something).

Here is what I would suggest:
1. Make sure you've closed all the sidebars in all the windows, and see if opening a new window still opens the sidebar.
2. If so, maybe there is some preference that is set that is causing this behavior (did you change any settings in `about:config` or similar?)
3. If neither of these solves your sidebar problem, try uninstalling and reinstalling Tab Stash.

## 2. Memory usage

The first thing is to narrow down where the extra memory usage is coming from (if it is in fact Tab Stash). Just as a point of comparison, on my system (with ~375 stashed tabs as of this writing) Tab Stash itself uses <100 MB of RAM (though the browser as a whole of course uses much more).

Fortunately, Firefox itself offers some nice memory-profiling tools. The first place to check is `about:performance`, which will show you the open tabs, extensions, etc. and how much memory they are using. Unfortunately, `about:performance` has a bit of a blind spot when it comes to extension memory use (but it's much easier to read than the next method), so you can use this just to rule out any open tabs taking up excessive memory.

If nothing stands out to you in `about:performance`, the more detailed view can be found at `about:memory` (which is how I measured the number above), which breaks down memory usage by every single thing that's open. Here's how to use it:

1. Find out Tab Stash's extension UUID (it's different for every install). Right-click the Tab Stash icon in the toolbar and choose "Show Stashed Tabs in a Tab". Copy the UUID that appears after `moz-extension://` in the address bar.
2. Make sure you have one copy of the Tab Stash UI loaded (could be the sidebar, could be in a tab, doesn't matter). If you have the sidebar open already, close it.
3. Go to `about:memory` and click "Measure". If you have a lot of tabs open, the measurement will probably take a while and Firefox will go unresponsive, so be patient. (It shouldn't take more than a minute or so though.)
4. Paste the UUID into the "Filter" box on the right.
5. Look for those `moz-extension://<tab-stash's-uuid>` URLs and you'll be able to find how much memory Tab Stash is using.
6. You can look for other memory hogs in the same way—by filtering, or just by exploring the memory tree that Firefox reports.

If `about:memory` shows that Tab Stash is using a lot of memory (more than, say, 100MB or so for each page), then I have some follow-up questions:

* How many open tabs did you have at the time (in total, across all windows)? A rough guess is good enough if you can't get an exact count
* How many bookmarks do you have (in total, across all bookmarks)? A rough guess is good enough if you can't get an exact count
* How many tabs/groups are in Tab Stash? (e.g. "Search X groups, Y tabs" at the top of the Tab Stash UI)

Let me know what you find!

**Comment by Lanchon** [comment]
thanks for the detailed response!

### 1. Self-opening sidebar

ok, so now i am perplexed too. before i closed the sidebar on *every* window and later restarted to find all sidebars open. i did this several times. also, i was opening new windows from a window with the sidebar closed (i used the new window toolbar button, so i know which window i opened from). yet every time the sidebar popped open. i restarted many times (as can be seen given my measurements).

a day or two later, both of these behaviors ceased: new window and restore session both don't open the sidebar anymore. i have no idea why. i am sure there was a firefox update in between, that is why i restarted later. so given that there is nothing you did wrong and thus nothing you can do, lets write this down as a firefox bug. i no longer experience the issue, so i can't test anything anyhow.

### 2. Memory usage

i can't really test right now, ill try to return to this later. i still wanted to reply. a few notes:

> on my system (with ~375 stashed tabs as of this writing) Tab Stash itself uses <100 MB of RAM

stashed? when i said "28 windows with 407 tabs" those are live tabs i was restoring. stash tabs? i didn't think of that, they are just bookmarks after all... but yes, tab stash has to load them (hopefully lazily per folder one day). anyway i probably have 1000+ stashed tabs.

now... after the firefox update, FF takes ages to restore session. it opens all windows without showing any content in them, then totally freezes for like 3 minutes, then continues like nothing happened. this did not happen while i did the prior tests. the first thing i need to check is whether tab stash has anything to do with this new thing.

i'll try report later.

thanks!

**Comment by josh-berry** [comment]
hm, I wonder if there is some sort of issue with Firefox's saved session data, since it was showing inconsistent behavior with the sidebar and now problems restoring windows/tabs on a restart. Here is another thing to try if you need any more ideas: https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data

Good luck!

**Comment by Lanchon** [comment]
the freeze on session restore is 3min 20s for some 300+ tabs. but it happens with or without tabstash. memory is no longer an issue now that tabstash does not pop up on every window.

given that both problems with tabstash (open sidebars, crazy memory) are solved, i will close the issue.

BTW, during the freeze only one CPU thread is being used (100%). no memory usage change during that period. ill have to investigate.

thanks!
