### ISSUE TITLE
Show warning when stashing temp files

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#148]
### Problem Statement
Stashing of files allow stashing temp files.

### Preferred Solution(s)
Warn the user.

### Alternative Solution(s)
Copy the file into another directory, like saving it.

### Additional Context
Stash an "Open in Firefox" PDF.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately I'm afraid there's not much I can do here, since:

- Tab Stash has no way to know what is considered a temp file and what isn't; this varies from OS to OS and even application to application, and there's no way we could reliably tell, across all combinations of OSes/applications, whether a particular file is going to be deleted by the OS/application after it's closed.
- For security reasons, extensions aren't generally allowed to interact with the filesystem anyway, so there's no way to save a copy of a PDF (or whatever) even locally.
- Even if Tab Stash could save copies of local files, there's no way to sync them between your computers.

Sorry to be the bearer of bad news here, but I'm afraid this one won't be possible.

**Comment by EmmanuelMess** [comment]
> * Tab Stash has no way to know what is considered a temp file and what isn't; this varies from OS to OS and even application to application, and there's no way we could reliably tell, across all combinations of OSes/applications, whether a particular file is going to be deleted by the OS/application after it's closed.

Isn't there a list of directories Firefox uses to save PDF's when one chooses to "open in firefox" when downloading?

> * For security reasons, extensions aren't generally allowed to interact with the filesystem anyway, so there's no way to save a copy of a PDF (or whatever) even locally.
> 
> * Even if Tab Stash could save copies of local files, there's no way to sync them between your computers.

No need, this issue is just to implement a warning to tell the user the file they stashed could be deleted at any time.

**Comment by josh-berry** [comment]
> Isn't there a list of directories Firefox uses to save PDF's when one chooses to "open in firefox" when downloading?

No there isn't. If you're opening a PDF from another application in Firefox, it's entirely dependent on where the PDF is saved, which application downloaded it, etc. If you're opening a PDF from within Firefox itself (e.g. clicking on a link on a website), the PDF may not be saved at all--it may just be loaded directly from the URL.
