### ISSUE TITLE
Auto save (and possibly auto load) stashes

### ISSUE THREAD

**Issue by jbmorgado** [josh-berry/tab-stash#15]
Will it be possible to add some kind of auto-saving/loading?
When you are in a stash, it would automatically save the changes (in the open tabs) to that stash.

The idea is mainly to allow to synchronize open tabs between Firefox on different computers.

**Comment by josh-berry** [comment]
I've given this some thought, and unfortunately I think it would be very hard to do safely/reliably. The problem with any type of auto-sync is that tabs can navigate between multiple URLs very quickly (e.g. because of the redirections that are done by many websites during logins, real-time page updates, etc.). Tab Stash stores all of its tabs as normal bookmarks in your library, so the Firefox bookmarks engine would have to keep up with these changes.

I've had a couple conversations with the Firefox devs about how bookmarks and syncing work, and from what I understand, Firefox bookmarks/sync were just never designed to keep up with such a high rate of change, and making such changes is likely going to cause trouble with sync in particular.

If you're not already aware, the Firefox Library contains all your synced tabs that are open on other machines (*Firefox Menu > Library > Synced Tabs*), so that might be a feature worth checking out. There might also be some other session-saving/loading extensions which do this, although they probably aren't going to save your tabs as bookmarks (for the same reason).

If I do think of a way to make this work, I might revisit it, but at this stage that seems pretty unlikely. Sorry to be the bearer of bad news. :/

**Comment by jbmorgado** [comment]
Thank you @josh-berry . That was a very clear and detailed explanation. I understand.

**Comment by despecial** [comment]
@josh-berry 
new tab stash user question:
As I understand, the extension is not able to update opened stash urls to the latest state (automatically)
Would it be possible to add a manual option/trigger to update the title and url of the opened stast item?

Example, I open a forum post on page 10, navigate some pages and want to close it at page 15.
If I re-open the stashed url, it will open again at page 10 instead of page 15.

I understand what you wrote here before, but a manual update trigger would be super helpful.
Hope I explained it well :)

**Comment by josh-berry** [comment]
@despecial It's possible, yes, and something I've been considering. That would probably be its own issue though (separate from this one).
