### ISSUE TITLE
Grouping links by day and not by time/current group, show as a list like in OneTab?

### ISSUE THREAD

**Issue by anephew** [josh-berry/tab-stash#155]
### Question
Is it possible to group links by day (in the current group) and not by time? Аnd for example time to show on the links themselves? Too many cards, very difficult to look at, I would like to show cards as a list as in One Tab.

Thank you

**Comment by josh-berry** [comment]
Hi, there is an advanced setting you can adjust to get something similar to what you're asking re. grouping by day. (Unfortunately there's not a way to show times on the links themselves; that would need some development work.)

By default, Tab Stash will add tabs to recently-created stashes (rather than creating a new stash) if the topmost stash was created in the last 5 minutes and doesn't have a custom name. The advanced setting allows you to change this time interval--so for example you could set it to 8*60 = 480 minutes, so that everything from the last 8 hours gets added to the same stash.

To change the settings, select "Options" from the main Tab Stash menu (next to the search bar), which will bring you to this page:
<img width="511" alt="Screenshot 2021-09-03 231517" src="https://user-images.githubusercontent.com/1203893/132084923-a753e0f2-3d11-41ec-967a-7d8aa0f72c1a.png">

Make sure you've turned on the advanced settings, and then you can adjust the time however you'd like.

Hope this helps, let me know how it goes!
