### ISSUE TITLE
Automatic openning stashed tabs after last tab is closed

### ISSUE THREAD

**Issue by dspjm** [josh-berry/tab-stash#156]
### System Details
- **OS Version:**  Windows 10
- **Browser Version:**  Firefox 92.0
- **Tab Stash Version:** 2.9

**Installed Browser Extensions:**

- No incompatible addons are installed
- 

### Describe the Bug
When the last tab is closed, the window is not closed due to custom setting, tab stash will automatically open one of its stashed tabs. If you close it, it will open another. Unless, you have opened the "stashed tab" tab.

### Expected Behavior
No opened stashed tabs after closing last tab.

### Steps to Reproduce
1. Set browser.tabs.closeWindowWithLastTab to false.
2. Close stashed tabs tab
2. Close all the tabs
3. See error

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately, this behavior is controlled by Firefox, and there is no way for Tab Stash to intercept or change it. It happens because Tab Stash uses Firefox's "hidden tabs" feature to keep stashed tabs open but hidden (i.e. not in your tab bar). When Firefox determines that you have closed the last visible tab, it will restore a hidden tab rather than close the window.

The only way to work around this is to change Tab Stash's "Tab and Memory Management" setting to "Close the tab immediately":

<img width="485" alt="Screenshot 2021-09-06 100837" src="https://user-images.githubusercontent.com/1203893/132247800-f56bde52-a067-4071-84e9-9cbeb6568793.png">

This will prevent Tab Stash from using the hidden-tabs feature entirely. The downside to this option is that when restoring a tab, it will be like loading it completely fresh, so it will take longer to load and it may not have saved whatever you were doing before.

Hope this helps!

**Comment by lucatrv** [comment]
I was also struggling with this issue. If this is the case, I would make "close the tab immediately" the default setting, and remove the other two options altogether. If I stash a tab, it means I wanted to save it for later, and I do not care if I will have to load it completely from fresh, most likely I will also have restarted Firefox in between.

**Comment by dspjm** [comment]
> 
> I was also struggling with this issue. If this is the case, I would make "close the tab immediately" the default setting, and remove the other two options altogether. If I stash a tab, it means I wanted to save it for later, and I do not care if I will have to load it completely from fresh, most likely I will also have restarted Firefox in between.

I don't think there is a need to delete the options anyway, someone might need that.

**Comment by lucatrv** [comment]
Ok, I wrote that thinking that the code would simplify (also because the "Hide and show browser tabs" permission would not be needed anymore), but I agree that those options could be kept. I would suggest however to make "close the tab immediately" the default setting, because IMHO the present "hide tabs" behavior is confusing for new and casual users (advanced users could change that if they need it).

Another setting that I would change for the same reason is "When the toolbar button i clicked -> Don't stash any tabs" (advanced users could change that as well if they need it). See also this [gHacks review](https://www.ghacks.net/2020/06/05/save-your-firefox-tabs-in-a-single-click-with-tab-stash/).

BTW, after using Tab Stash for some time, I would like to propose the following improvements:

- Ability to select an existing group when stashing tabs (similar to the Firefox bookmark popup).
- Change "Stash this tab" into "Stash this tab or selected tabs" behavior.
- Ability to open a stashed group in a new window keeping them synced (similarly to "Tabs Outliner").
- Options to load tabs in the background by default, and to keep tabs open when stashed by default.

Do you prefer me to open four separate feature requests, or just one? Moreover if you do not agree with any or all of them, please let me know and I will not open them altogether. Thanks

**Comment by josh-berry** [comment]
> Ok, I wrote that thinking that the code would simplify (also because the "Hide and show browser tabs" permission would not be needed anymore), but I agree that those options could be kept. I would suggest however to make "close the tab immediately" the default setting, because IMHO the present "hide tabs" behavior is confusing for new and casual users (advanced users could change that if they need it).

I think this actually cuts both ways—I could also see new/casual users being confused by stashing something and losing any state/content in the tab when restoring it later. So I err on the side of keeping state by default (and users who run into this can always change the setting).

Any other Firefox extension which is using hidden tabs will run into the same issue, so it's probably something the Firefox folks will ultimately have to address.

> Another setting that I would change for the same reason is "When the toolbar button i clicked -> Don't stash any tabs" (advanced users could change that as well if they need it). See also this gHacks review.

See #123.

**Comment by josh-berry** [comment]
I'm going to go ahead and close this out, but feel free to leave another comment if there are any more thoughts on this!
