### ISSUE TITLE
Add dark theme support

### ISSUE THREAD

**Issue by GithubUser5462** [josh-berry/tab-stash#16]
It would be nice if the sidebar and tab view supported the dark theme,
either automatically or through a toggle.

**Comment by josh-berry** [comment]
I agree. Unfortunately, Firefox doesn't provide a way for extensions to tell whether a dark theme is enabled or not. I've tried to support dark themes to the extent possible within Firefox's constraints (e.g. by providing a dark-theme version of the toolbar icon), but I'll need more info from their themes API to do this in a way that looks good.

I'm not super keen on adding a manual setting for dark mode to Tab Stash itself, because Tab Stash is just one of potentially many extensions that run in your browser, and I think it's a little silly to ask a user to switch all their extensions by hand along with switching the browser theme. So I'd rather wait for Firefox and do it in a way that's seamless.

In any case, I'll keep this issue open in the meantime as a reminder to revisit periodically—Firefox is adding/updating their extension APIs all the time, so hopefully they will get around to adding a dark-theme flag soon.

**Comment by GithubUser5462** [comment]
Fair enough, fwiw:

- in firefox beta (68) there is the preference `browser.in-content.dark-mode` which sets the in content pages (addons manager, options, homepage, ...) to dark when toggled.
- the most closely releated bugzilla bug to this issue is probably [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1529323).

**Comment by RandomHam** [comment]
just wanted to add that recoloring the icon in url bar would also be a thing to consider. I don't know if that's possible seamlessly already.

**Comment by josh-berry** [comment]
> in firefox beta (68) there is the preference browser.in-content.dark-mode which sets the in content pages (addons manager, options, homepage, ...) to dark when toggled.

Unfortunately I don't think extensions have the ability to query more than a predefined set of browser preferences.

> the most closely releated bugzilla bug to this issue is probably [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1529323).

Good to know, and thanks for the pointer to Bugzilla. I didn't know about this particular bit of CSS,  which might be present in the most recent version of Firefox [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). I'll have to investigate more to see if a full dark theme might be possible (and will re-tag this issue accordingly).

> just wanted to add that recoloring the icon in url bar would also be a thing to consider.

Sadly that's one of the things missing—the toolbar icon does get recolored, but the URL button doesn't because there's no entry in the `manifest.xml` for dark themes like there is for the toolbar button.

**Comment by happysurf** [comment]
> Sadly that's one of the things missing—the toolbar icon does get recolored, but the URL button doesn't because there's no entry in the manifest.xml for dark themes like there is for the toolbar button.

At moment the solution could be make the address bar icon in medium gray, visible in white and dark backgrounds.
See Want My RSS addon for that at:  https://github.com/Reeywhaar/want-my-rss

**Comment by josh-berry** [comment]
Adding a note as reported in #23: in dark mode, the options page has dark text on a dark background.

**Comment by josh-berry** [comment]
> At moment the solution could be make the URL icon in medium gray, visible in white and dark backgrounds.

Yes, that's true and a good point. I'll see if there are some interim changes I can make until proper Firefox support is available.

**Comment by josh-berry** [comment]
I've made some color changes to the button in the location bar to hopefully make it more visible in dark mode.

I also did a little more investigation on the aforementioned CSS rules for light/dark theme, and unfortunately it turns out that Firefox does not respect those selections at least as of FF 67. So unfortunately I'm not going to be able to implement any kind of dark theme until FF exposes the dark-vs.-light theme info to extensions in some way (either through CSS or an extension API).

Will keep this issue open in the meantime and tag it appropriately, though, to revisit if/when Firefox adds better support for extensions and dark themes.

**Comment by josh-berry** [comment]
see also: https://bugzilla.mozilla.org/show_bug.cgi?id=1542044

**Comment by Neurognostic** [comment]
Might want to look into how [Tree Style Tab](https://github.com/piroor/treestyletab) has implemented browser theme detection.

I am not a web dev, but [this seems like this is [roughly] the implementation](https://github.com/piroor/treestyletab/blob/f2f041bddae49a214c892ff189973588d4dc8c6f/webextensions/sidebar/sidebar.js#L287-L345):

```javascript
import * as BrowserTheme from '/common/browser-theme.js'

:root {
      ${BrowserTheme.generateThemeRules(theme)}
}
```

For example, when using the default dark theme it returns these css vars:
```css
--theme-colors-frame: hsl(240, 5%, 5%)​;
--theme-colors-icons: rgb(249, 249, 250, 0.7)​;
--theme-colors-ntp_background: #2A2A2E​;
--theme-colors-ntp_text: rgb(249, 249, 250)​;
--theme-colors-popup: #4a4a4f​;
--theme-colors-popup_border: #27272b​;
--theme-colors-popup_text: rgb(249, 249, 250)​;
--theme-colors-sidebar: #38383D​;
--theme-colors-sidebar_border: rgba(255, 255, 255, 0.1)​;
--theme-colors-sidebar_text: rgb(249, 249, 250)​;
--theme-colors-tab_background_text: rgb(249, 249, 250)​;
--theme-colors-tab_line: #0a84ff​;
--theme-colors-toolbar: hsl(240, 1%, 20%)​;
--theme-colors-toolbar_bottom_separator: hsl(240, 5%, 5%)​;
--theme-colors-toolbar_field: rgb(71, 71, 73)​;
--theme-colors-toolbar_field_border: rgba(249, 249, 250, 0.2)​;
--theme-colors-toolbar_field_separator: #5F6670​;
--theme-colors-toolbar_field_text: rgb(249, 249, 250)​;
```
And when using the default (light) theme:
```css
--theme-colors-frame: #E3E4E6​;
--theme-colors-icons: rgb(24, 25, 26, 0.7)​;
--theme-colors-popup: #fff​;
--theme-colors-popup_border: #ccc​;
--theme-colors-popup_text: #0c0c0d​;
--theme-colors-tab_background_text: rgb(24, 25, 26)​;
--theme-colors-tab_line: #0a84ff​;
--theme-colors-toolbar: #f5f6f7​;
--theme-colors-toolbar_bottom_separator: #ccc​;
--theme-colors-toolbar_field: #fff​;
--theme-colors-toolbar_field_border: #ccc​;
```

These can then be used by the user or the extension as a "theme".

Relevant commits:
https://github.com/piroor/treestyletab/commit/f2f041bddae49a214c892ff189973588d4dc8c6f
https://github.com/piroor/treestyletab/commit/5cd7f41eefbd096bcb9b1e77ffd3b0bc7f2ead19
https://github.com/piroor/treestyletab/commit/093de79bc265051d128bdfbb89cab6ae3567be11
https://github.com/piroor/treestyletab/commit/a1bee34baaa0725059d19cef187802f6f0f746a5

Maybe @piroor can comment on implementation details for [browser-theme.js](https://github.com/piroor/treestyletab/blob/master/webextensions/common/browser-theme.js), because I do not have a clue 😉.

**Comment by josh-berry** [comment]
It looks like Firefox 70 and later support detecting dark mode using standard (or soon-to-be standard) CSS `@media` queries. So this should at least be possible now.

**Comment by josh-berry** [comment]
The next release of Tab Stash will have dark mode support. :) To enable it, you will have to enable the system-wide dark mode (using the Firefox dark theme is unfortunately not enough to get Firefox to use the correct CSS color scheme).

Happy New Year!

**Comment by josh-berry** [comment]
Tab Stash 2.5 was just released with dark mode support. Hope you like it! If anything seems off/hard to see, please open a new issue and let me know.

**Comment by Neurognostic** [comment]
> Tab Stash 2.5 was just released with dark mode support. Hope you like it! If anything seems off/hard to see, please open a new issue and let me know.

Awesome job, no more bright-white sidebar with dark theming.

![image](https://user-images.githubusercontent.com/23530447/71760087-6811ad00-2e7d-11ea-83e8-b4bebba2f075.png)

**Comment by MrLonkers** [comment]
I guess it only works on Windows and not a Mac. I was wondering why it was dark at work (Windows 10) but not at home (Mac)

**Comment by josh-berry** [comment]
> I guess it only works on Windows and not a Mac. I was wondering why it was dark at work (Windows 10) but not at home (Mac)

It works on both Mac and Windows (in fact, the screenshot on the addon listing was taken on my Mac). However, you need to have your theme set to dark in System Preferences; changing the Firefox theme is not enough. Hope this helps!

**Comment by dquesadacr** [comment]
Hi! First of all, thanks for the great tool!

I'm using Manjaro with the breath2dark theme (also dark theme in firefox) and still get the light theme on tab stash. I also tried to tweek it according to this [post](https://www.reddit.com/r/FirefoxCSS/comments/dvr1gm/change_the_background_in_the_tab_stash_extension/), but still can't seem to make it work... 

Any help or tips on how to make it work on my theme or how to change the css would be appreciated!

Cheers

**Comment by josh-berry** [comment]
> I'm using Manjaro with the breath2dark theme (also dark theme in firefox) and still get the light theme on tab stash. I also tried to tweek it according to this [post](https://www.reddit.com/r/FirefoxCSS/comments/dvr1gm/change_the_background_in_the_tab_stash_extension/), but still can't seem to make it work...

There's an open feature request to make this manually configurable so you can force dark mode to be turned on. Please give it a thumbs-up if you'd like to see it implemented: https://github.com/josh-berry/tab-stash/issues/108

I'm afraid the best I can suggest is to wait for this feature. I don't recommend CSS mods (like what's in the Reddit post) because they're quite complex to do, and there's a lot that can go wrong if they're done incorrectly. It's also possible they will break on any update to Tab Stash.

In the specific case of the mod you linked, there's also a chance it may impact other websites, not just Tab Stash (e.g. if the same CSS IDs/classes are being used), since Firefox applies the `userContent.css` file across all extensions and websites. Just something to be aware of in case other sites start to break or look strange after applying the mod.

**Comment by dquesadacr** [comment]
Thanks for the reply! Thumbs-up already given!
