### ISSUE TITLE
Disabling extension unhides all tabs; Re-enabling doesn't hide them.

### ISSUE THREAD

**Issue by mystiquewolf** [josh-berry/tab-stash#160]
### System Details

- **OS Version:** Kubuntu 21.04
- **Browser Version:** Firefox 92.0
- **Tab Stash Version:** 2.9

### Describe the Bug

Disabling `Tab Stash` causes all tabs it has hidden to reappear / unhide. Enabling it again does not offer to hide them automatically for the user.

### Expected Behavior

Extension should offer to automatically hide all of the tabs that were hidden last time and are currently unhidden.

### Steps to Reproduce

1. Open lots of tabs
2. Stash some of the tabs
3. Disable `Tab Stash`. Notice that all hidden tabs have unhidden themselves automatically
4. Enable `Tab Stash`. Notice the inconsistency between tabs status in the `Tab Stash` side view and the real hidden status of the tabs.

### Impact
After re-enabling `Tab Stash` still shows the tabs as hidden and code logic probably relies on this state. The tabs real state is unhidden.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, this is precisely what the "Close all stashed tabs" button is for:

<img width="397" alt="Screen Shot 2021-09-29 at 09 39 52" src="https://user-images.githubusercontent.com/1203893/135312241-40975265-6385-4ad4-a7fd-859c80221873.png">

If, for any reason, you want to close all the stashed tabs in the window so you only have unstashed tabs to deal with, you can use this.

> After re-enabling `Tab Stash` still shows the tabs as hidden and code logic probably relies on this state. The tabs real state is unhidden.

When you say it "shows the tabs as hidden" do you mean they're still present in the stash? This is expected (you didn't delete them, after all)—but, because the tabs are no longer hidden, they should show up in a blue color to indicate the tab is open. If they're NOT showing up as blue, let me know, and I'll investigate further.

On a more general note, there is no harm in doing exactly what you have done (unloading/reloading)—Tab Stash treats the browser as the single source of truth. You can hide/unhide tabs, manually move bookmarks around, etc. all day long even while Tab Stash is running and there should be no issues/inconsistencies in doing so. In fact, unloading/reloading the extension actually regenerates most internal state (except for things like favicons)—so if you *do* hit some inconsistency, this would work around such an issue, not make it worse.

Anyway, let me know if the un-hidden tabs are actually showing in blue (i.e. open) in the stashes. If so, I don't think there's a bug here.

**Comment by mystiquewolf** [comment]
- If a tab is unhidden it shows in blue
- Yes, this button (although it says "close") does hide a stashed tab which is unhidden via the browser. Which is awesome!
- I didn't see this button because my list of unstashed tabs was collapsed and only two buttons showed on hover there. In addition, i didn't remember to look there for an action as the tab itself was not in this list of unstashed tabs but in a specific group, so i didn't expect an action to affect it from a different place.
- Maybe a good idea is to better inform the user about this existing ability/feature?

**Comment by josh-berry** [comment]
Yeah, before Tab Stash remembered deleted items/had an undo feature, I had made those buttons hidden so that users wouldn't accidentally delete something without at least being forced to see what they were deleting. Now that deleted items are a thing, they probably don't need to be hidden anymore. Will make a note for a future release!

**Comment by josh-berry** [comment]
This will be available in 2.10, coming soon!
