### ISSUE TITLE
Rename tab (feature request)

### ISSUE THREAD

**Issue by shalpin** [josh-berry/tab-stash#168]
First - thanks for creating an awesome extension! I have tried several ways to wrangle my tabs and this seems very efficient, giving me everything I want and nothing I don't.

Tab Stash appears to derive the name of the tab from page data - I would like to be able to amend this to display a name I choose.

The reason I want to do this is that I work with web applications that run on different systems. Tab Stash appears to use data from the page as the name of the tab, but this means that different systems running the same web app are all named the same. I would like them to show a name I give them so I can distinguish them.

I was hoping that bookmarking the page and naming the bookmark would allow Tab Stash to pick up that name and use it, but it does not do that. I also tried exporting/editing/importng - I found the name listed in square brackets in the markdown export. I exported that, edited the name and imported, but importing that data just showed the auto-generated name and not the one I had edited it to. I was also wondering if a right click on the name might bring up a rename option, but it does not.

I tried restarting and clearing session info, but it always seems to pick up the auto-generated name.

Is there some way I can rename the link names that Tab Stash determines?

**Comment by shalpin** [comment]
Sorry - it seems to have picked up the name now .... I'm not sure why ... I made a mistake. Please close this and thanks once again!

**Comment by josh-berry** [comment]
Hi, thanks for sharing! Glad to hear you're finding Tab Stash useful.

I actually have the same problem at work (same web application, running in different regions), and the way I've handled it has been to have different stashes for different regions. (But of course that won't work in all situations.)

Tab Stash will choose the name for a tab based on the page title. So if a tab with the right URL is open, the UI will use the title from that tab. Otherwise, it uses whatever title was saved in your bookmarks. So you *can* rename tabs, sort of, by editing the bookmark directly in Firefox. But then the tab title will get substituted in the UI when the tab is re-opened (though the bookmark itself will not be renamed).

Hopefully this explains what you're seeing--sometimes it will pick up the name, and sometimes it won't, depending on whether it's getting the name from an open tab or from your bookmarks.

Anyway, let me know if, now that you know the above, you're still interested in a renaming feature--I'll keep the issue open in the meantime.

**Comment by justpeanuts** [comment]
+1 for the option to rename tabs (even before stashing the tabs)
This would allow Tab Stash to also function as a much needed(IMO) Firefox alternative for the Chrome addon "Tab outliner". I made a reddit post complaining that firefox lacks addons to emulate the some functionalities of Tab outliner - https://www.reddit.com/r/firefox/comments/q4fz1a/still_no_firefox_analogue_of_tab_outliner_chrome/?utm_source=share&utm_medium=web2x&context=3

**Comment by josh-berry** [comment]
Happy to report this will be in the next release. Thanks to @sleak75 for contributing the implementation!
