### ISSUE TITLE
high cpu usage - cleaning up old deleted items

### ISSUE THREAD

**Issue by Amir-m-a** [josh-berry/tab-stash#172]
### System Details
- Windows 10, 10th gen intel 4c/8t cpu
- Firefox 94.0.1
- Tab Stash Version: 2.10

### Describe the Bug
high cpu usage(one core at 100%) after startup for prolonged time(never stops actually).

### Expected Behavior
normal cpu usage as before latest update.

### Steps to Reproduce
it happens every time after startup.

### Impact
one core is used completely, made me disable the add-on altogether.

### Additional Details
tried to debug it and apparently lots of events are triggered which call gc function and it runs into exception at [here](https://github.com/josh-berry/tab-stash/blob/839f53c03a6e5a6564f212a413387157ba8f2c6f/src/model/bookmarks.ts#L121). here's call tree in a performance record:
![image](https://user-images.githubusercontent.com/33460495/142763514-ea0a1daa-a4f2-4b83-89fe-86466695a891.png)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Yikes, can you share the full stack trace from the exception? Should be visible in the console output.

Can you also save and upload that recording if you still have it?

**Comment by Amir-m-a** [comment]
> Yikes, can you share the full stack trace from the exception? Should be visible in the console output.
> 
> Can you also save and upload that recording if you still have it?

here's the record: [profile.zip](https://github.com/josh-berry/tab-stash/files/7578621/profile.zip)
about the stack trace, it's not shown in console. the one I mentioned back then is from debugger after enabling "pause on caught exception". the trace is:
```
node (webpack://tab-stash/src/model/bookmarks.ts#121)
gc (webpack://tab-stash/src/model/index.ts#224)
gc (webpack://tab-stash/src/model/bookmark-metadata.ts#36)
```
![image](https://user-images.githubusercontent.com/33460495/142807839-b2320018-8cf1-40dc-b269-0dcdbf128207.png)

though some how it's fixed now, not sure exactly how. I set "remember items that were deleted ..." in options to 1 day and after sometime the "unstashed tabs" became responsive(which wasn't before) and cpu usage is normal now. after bunch of restarts it's still fine, so problem solved apparently. I don't remove tabs from stash but maybe it considers the closed tabs as being removed from "unstashed tabs" and that has caused the problem. anyway glad I can use it again.
thanks btw for the great add-on.

**Comment by josh-berry** [comment]
Aha, I'm guessing what happened here is you had a ton of deleted items, and it just took a LOT of time and CPU to clear them out. The default for remembering deleted items is 180 days, and so when you changed it to only 1 day, Tab Stash suddenly had 179 days' worth of items to get rid of.

Once the old items were cleared out, however, everything went back to normal because there was nothing left to delete. So the good news is this shouldn't happen again.

The deletion is unfortunately a pretty expensive process (which is why it's only done periodically), but I'll see if there's something that can be done to optimize it or at least spread it out so it doesn't impact performance as much.

**Comment by josh-berry** [comment]
## Workaround

For the record, since I've heard reports of some other users hitting this, the way to work around this issue is to **uninstall and reinstall Tab Stash.** (Disabling/enabling is not enough.)

This will clear the deleted-items history, so that Tab Stash doesn't try to do it in the background. Of course, you will lose all your deleted items by doing this, but CPU usage should return to normal.

**Comment by josh-berry** [comment]
See also, this comment: https://github.com/josh-berry/tab-stash/issues/175#issuecomment-1013624930

Seems likely that cleaning up deleted items may just be very expensive in general. I'll look into that as part of this bug.

**Comment by naugtur** [comment]
Here's a fresh recording of a profile
[profile.json.zip](https://github.com/josh-berry/tab-stash/files/7985372/profile.json.zip)

I did the reinstall trick before and it helped. Didn't delete much since then. probably around 20-30 tabs.

Pausing in the debugger randomly I was getting more or less the same stack. unfortunately sourcemaps won't load, so couldn't dig in more. 

![Screenshot_2022-02-02_10-58-34](https://user-images.githubusercontent.com/509375/152133240-56b25698-f9b2-4526-8ac4-8ee931099560.png)

**Comment by josh-berry** [comment]
I think I've found (and fixed) what was causing high CPU for deleted items, especially for folks who have a lot of deleted items, haven't restarted their browsers in a while, etc.

If any of you are interested in the gory details you can read the linked commit above, but the short version is: Tab Stash's background page was keeping deleted items around in memory for no reason. Over time, those items were accumulating, causing *everything* related to deleted items to slow down--and the more you delete, the slower it gets.

This bug was not an easy one to find, but hopefully it's squished now and will be banished from the next release onward. :)

----------

@naugtur Thanks for sharing the profile and the stack trace. The profile seemed dominated by GC time (probably for the reason mentioned above!). Still, in your case it's odd that your stack traces are mostly showing bookmark-metadata GC rather than deleted-items GC. I don't *think* there is another bug here (I did take a look at bookmark-metadata just to see if I could find anything), but you never know. :)

I'll close this bug, but please do open another one if, after the next release (with the deleted-items fix), you see high CPU usage again.
