### ISSUE TITLE
High CPU usage without doing anything related to tab stash

### ISSUE THREAD

**Issue by jannismain** [josh-berry/tab-stash#175]
### System Details

- **OS Version:** macOS 12.0.1 (21A559)
- **Browser Version:** Firefox 94.0.1 (64-bit)
- **Tab Stash Version:** 2.10

**Installed Browser Extensions:**
![image](https://user-images.githubusercontent.com/14290527/143011646-657a3306-31f6-4002-9537-bfd742b2e4dc.png)

### Describe the Bug
Seemingly at random times while browsing (tab stash not open or interacted with) the CPU usage of FirefoxCP WebExtensions will increase drastically and the fans will spin up.
![image](https://user-images.githubusercontent.com/14290527/143011892-40171ba3-c064-4913-b26f-00beca1e0d07.png)

A look at the Firefox task manager will reveal Tab Stash to be the culprit:
![image](https://user-images.githubusercontent.com/14290527/143012276-66e77397-b2bd-4a1e-8955-d0fdd6e90ae6.png)

### Expected Behavior
- no significant cpu usage
- no fan noise

### Steps to Reproduce
I haven't figures out a pattern yet. If I do, I will update this section.

### Impact
Restarting Firefox or disabling tab stash solved the issue for me.

### Additional Details
This seems to be unrelated to #172, as the cause there was related to changing the config option "remember items that were deleted ...", an option I haven't heard of before or changed for my installation.

I tried recording the activity in the Firefox Dev Tools, but it recorded mostly idle time, so I don't think my recording would be of any help. Can I provide any other useful debugging data?

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by jannismain** [comment]
Regarding #173 , I have now downgraded to 2.9 and will monitor if the problem persists there..

**Comment by josh-berry** [comment]
This sounds suspiciously similar (but not exactly like) a bug in Firefox itself, with a fix due to be released in Firefox 95: https://bugzilla.mozilla.org/show_bug.cgi?id=1706594

That said, there are a lot of things that can cause high CPU usage, so I'll be curious to hear (1) if you have the same issue on 2.9, and (2) if you hit it again (regardless of whether it's on 2.9 or 2.10), if there are any error logs that might shed some light on what's happening: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

Thanks for the report and let me know how it goes!

**Comment by josh-berry** [comment]
BTW, you can also record performance data in that same developer-tools window as above; if the CPU usage is coming from Tab Stash's background process, this should capture it. If even the background dev-tools window performance data shows mostly idle time, then that's a likely indicator that you're hitting the Firefox bug I mentioned above.

**Comment by jannismain** [comment]
Since downgrading to 2.9 I haven't experienced the issue again. Will keep monitoring for a couple more days, though...

**Comment by josh-berry** [comment]
hmmm strange.

2.10.1 is out now; does 2.10.1 show the same issue? If so, collecting console output and a performance profile (as mentioned above) would help narrow it down. Let me know how it goes!

**Comment by jannismain** [comment]
I just checked and I already got updated to v2.10.1. So far, haven't seen the high CPU usage problem again.
So far, it seems to have been specific to v2.10.0. I'm closing this for now, but will re-open if the problem should come back in a future version.

**Comment by kwilczynski** [comment]
Hi @josh-berry,

Even though @jannismain closed his issue, it seems a very - if not identical - thing is having place on my system. I have latest version of the extension and latest Firefox, and yesterday I had to disable Tab Stash as it would keep using a lot of CPU time for no apparent reason.

To add, I am not really a heavy Tab Stash user - more of a casual use where I stash something every so often.

I can open a dedicated issue if that would be something you would prefer, however, I wonder if this is somewhat related to me upgrading Firefox to the latest version recently.

**Comment by josh-berry** [comment]
Hi @kwilczynski, sorry for the trouble:
1. If you enable Tab Stash again now that you've disabled it, does the CPU issue come back? (If it does come back, it might take a few minutes to do so)
2. If disabling/enabling didn't help, can you try uninstalling/reinstalling Tab Stash? Does that reduce the CPU?

If neither (1) nor (2) help, then feel free to go ahead and open a new issue. And just in case you want to do a little more investigating, here's how to check for error logs, including anything you find would be helpful: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

**Comment by kwilczynski** [comment]
> Hi @kwilczynski, sorry for the trouble:

No a problem at all! Thank you so much for your work on Tab Stash!

>     1. If you enable Tab Stash again now that you've disabled it, does the CPU issue come back? (If it does come back, it might take a few minutes to do so)

Yes, it would happen almost a second after I enable the extension. I left it once enabled for a day or so, hoping that perhaps it has to recalculate something and such (however, I don't really have a lot of stashes, so to speak), but this didn't seem to help.
 
>     2. If disabling/enabling didn't help, can you try uninstalling/reinstalling Tab Stash? Does that reduce the CPU?

Attempted to do this now (before replying here), however, it had no apparent effect. As per:

![Screenshot from 2021-12-12 23-08-11](https://user-images.githubusercontent.com/250723/145731494-1888761e-3d47-4e4d-baca-0723f2fc17ca.png)
 
> 
> If neither (1) nor (2) help, then feel free to go ahead and open a new issue. And just in case you want to do a little more investigating, here's how to check for error logs, including anything you find would be helpful: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

Will do! Thank you.

**Comment by kwilczynski** [comment]
Hi @josh-berry,

A quick update.

Following the reinstallation of the extension, I decided to try something else. I stopped the extension, removed Tab Stash from bookmarks, enabled the extension. No issues with a clean slate, so to speak. Then I stopped the extension again, and restored deleted Tab Stash folder so that it was again in my bookmarks, and then enabled Tab Stash again. After a brief jump to "Medium" usage as reported in the performance view, things have calmed down.

No high CPU usage at the moment.

I am not sure why this worked, but it seems to have fixed the problem.

**Comment by josh-berry** [comment]
Very strange! If you happened to catch any error logs, I'd still like to take a look at them, but if not, no worries--I'm glad re-creating the bookmarks helped!

**Comment by josh-berry** [comment]
@LucienLeMagicien Yep, I agree that's idle time. There's actually a known Firefox issue that can cause very similar symptoms (high CPU usage attributed to an extension process, but nothing's happening in the performance monitor). Fortunately it's fixed in Firefox 95 and later. I assume you're on an ESR for a good reason, but if it fits your situation, I'd suggest trying with the latest Firefox and see if it helps. That should at least confirm if it's the same issue.

NOTE: You may want to make a backup of your profile before upgrading. I don't think Firefox allows downgrades if you want to go back to the ESR after your test.

**Comment by LucienLeMagicien** [comment]
@josh-berry I moved my profile over to firefox 95.0.1 and tl;dr after some time, I don't see a big CPU usage anymore, but did for a bit.

After starting firefox, I got high CPU usage again, but this time the profiler displayed a ton of DOM Events:
![image](https://user-images.githubusercontent.com/61185219/146675801-bb2c8464-5674-43db-95b2-73af1709dc66.png)
![image](https://user-images.githubusercontent.com/61185219/146675824-cf1376d0-27d4-4065-9c6c-b69ba9a76fb4.png)

It kept eating at the CPU after disabling/re-enabling the addon, same with uninstalling-reinstalling it. Then I stashed my three windows for a total of 90 tabs and it seemingly calmed down, and reloading the tabs or restarting the browser doesn't trigger the issue again...

I'm not sure if it simply needed time to process things in the background (there was a good 20 minutes between me switching browser versions and me noticing the CPU usage being normal again), or if disabling/re-enabling, uninstalling/reinstalling, stashing windows, or a combination of these helped, or if it was just a fluke. In hindsight, I should have left it run for a bit before trying anything myself...
(For the record, my "remember items that were deleted ..." setting is still set at the default 180 days, and I have about 2200 tabs in 20 groups.)

Since then I've uninstalled tabstash, restarted the browser, reinstalled tabstash again, and have been monitoring for a little bit now with no issues to be seen, so I guess it's solved on my end! And the issue in my previous post was probably due to that firefox bug, as you said.

Thanks for your time!

**Comment by adorabilis** [comment]
I’m experiencing this issue on Firefox 96.0, macOS 12.1. I only noticed it recently when fan noise became audible. Disabling and enabling Tab Stash didn’t work so I tried reinstalling (same settings restored) and the problem went away. I’ll report back if it happens again.

![Screenshot 2022-01-04 at 10 42 07 PM](https://user-images.githubusercontent.com/16101408/148078122-4d9b4259-38ac-4e8e-a9f5-aa43348764d2.jpg)

**Comment by aerobounce** [comment]
- macOS 12.1
- Firefox 96.0.1 with a fresh profile and with Firefox caches removed
- Tab Stash 2.10.1

The issue is intact for a fresh profile, it keeps CPU usage unexpectedly high.
However, setting `Remember items that were deleted on this computer for n days` to `1 days` fixes the issue and I can confirm this is a consistent fix.

**Comment by josh-berry** [comment]
Thanks everyone for all of the reports/data you've sent in. I really appreciate it and it's helped a lot to narrow the CPU issues down. There are two different causes of high CPU in Tab Stash (not counting the bug in Firefox itself that was fixed in FF 95), and we have separate bugs for tracking each of the issues:

* #172 
* #201 

Fortunately, there are workarounds for both (for the most part), and I think I have enough information for now to work on fixes (or at least, mitigations) for the next release.

In the meantime, if you're seeing high CPU and neither of the workarounds in either of the above issues work for you (even temporarily), please feel free to open a new issue and I'll do what I can to help.
