### ISSUE TITLE
Unable to open tab-stash in tab since 2.10.1

### ISSUE THREAD

**Issue by Yagoth** [josh-berry/tab-stash#177]
### Bug
Unable to open tab-stash in tab.  I have tried via the right click context menu on a page and via right clicking the icon.  Neither works.
A contributing issue is I have 3000+ tabs saved, however I was able to open tabstash in a tab pre 2.10.1 update.  I have it set to closed the tab immediately when stashed, so theoretically they should take up minimal resources.   I just started using Tab-Stash after importing from one tab.  I has worked okay for a few days, but today its stopped being responsive.

### System Details
Computer: 16GB ram, 6 Core Intel Core i7-8750H, GTX 1050ti

Extensions:
Cookie Manager
Feedbro
KeepassXC-Browser
OneTab(Temporarally while I see if Tab-stash works)
Privacy Badger
TinEye Reverse Image Seach
uBlockOrgin
Video Speed Controller
VT4Browsers

- **OS Version:**
Windows 10 20H2
- **Browser Version:**
94.0.2
- **Tab Stash Version:**
2.10.1

**Comment by Yagoth** [comment]
The issue persist even when I downgrade to 2.9 or upgrade back to 2.10.1

![Tabstash open tab view error](https://user-images.githubusercontent.com/8422621/143522187-953bb1fa-8aa7-46d2-a843-d69f1ca4b4be.PNG)

Got activated event for unknown tab 23 index.js:1
    expect index.ts:101
    whenTabActivated tabs.ts:450
    whenTabActivated self-hosted:1175
    n wiring.ts:27
    apply self-hosted:2715
    applySafeWithoutClone ExtensionCommon.jsm:623
    fire ExtensionChild.jsm:802
    recvRunListener ExtensionChild.jsm:806
    recvRunListener self-hosted:1175
    _recv ConduitsChild.jsm:78
    receiveMessage ConduitsChild.jsm:184
Got activated event for unknown tab 23 stash-list.js:1
    expect index.ts:101
    whenTabActivated tabs.ts:450
    whenTabActivated self-hosted:1175
    o wiring.ts:27
    apply self-hosted:2715
    applySafeWithoutClone ExtensionCommon.jsm:623
    fire ExtensionChild.jsm:802
    recvRunListener ExtensionChild.jsm:806
    recvRunListener self-hosted:1175
    _recv ConduitsChild.jsm:78
    receiveMessage ConduitsChild.jsm:184
Got activated event for unknown tab 23 stash-list.js:1
    expect index.ts:101
    whenTabActivated tabs.ts:450
    whenTabActivated self-hosted:1175
    o wiring.ts:27
    apply self-hosted:2715
    applySafeWithoutClone ExtensionCommon.jsm:623
    fire ExtensionChild.jsm:802
    recvRunListener ExtensionChild.jsm:806
    recvRunListener self-hosted:1175
    _recv ConduitsChild.jsm:78
    receiveMessage ConduitsChild.jsm:184
Uncaught (in promise) Error: Invalid tab ID: 14 undefined
Uncaught (in promise) Error: Invalid tab ID: 14 undefined

​

**Comment by josh-berry** [comment]
Thanks for sharing the error log, this really helps. Here's what I think is happening (you can skip the part between the lines if you don't care about the gory details):

---------

1. Firefox is telling Tab Stash that tab 23 is activated, but Tab Stash has no idea which tab this is
2. In 2.10.1, when something like this happens (indicating Tab Stash is out of sync with the browser), Tab Stash will ask Firefox for the complete list of tabs again.
3. Since this appears to be happening repeatedly for the same tab, it seems likely that Firefox is not reporting any info about tab 23 to Tab Stash.
4. Those "Invalid tab ID: 14" errors appear to be coming from Firefox itself (i.e. the `undefined` source).

So how does this relate to opening the stash UI? When opening/restoring a tab, Tab Stash will check its list of open tabs to see what is already open and avoid creating duplicates. If it seems like the UI is already open, we'll try to switch to it instead of opening a duplicate tab. It's possible those "Invalid tab ID" errors are related to Tab Stash's attempts to open the UI in a tab.

---------

So at first glance, it seems like Firefox is reporting wrong info about which tabs are open to Tab Stash, and Tab Stash is relying on that wrong info when it's trying to open the UI in a tab.

A couple questions for you:
* Have you restarted Firefox since you first installed Tab Stash?
* Have you restarted Firefox since the issue started occurring?

And a couple things to try:
1. Restart Firefox and see if the issue with the UI resolves itself
2. If that doesn't help, try this: https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data

Let me know how it goes!

**Comment by Yagoth** [comment]
I have restarted FF a few times since installing tab-stash 2.9.

I am not sure if tab-stash 2.10.1 was functional for any period of time prior to a restart, sorry.
After issues began I restarted FF several times, including once in safe mode..  The issues persisted.  

### Fixed :) using option 2
However,  I disabled then re-enabled: "about:preferences>General>Startup:Open previous windows and tabs", which seems to have solved not only the "can't open tab-stash in tab" issue, but also the other performance/UI issues that began with the download of 2.10.1  I think this is what you mean by Restart-Firefox-Without-Saved-Session-Data, but the UI labels seem to have changed a bit since you wrote your guide.

Thanks for the explanation and quick reply. 
BTW. I have not upgraded/fixed my other computers from 2.9 yet.  Do you want still want other 2.10/2.10.1 console error records for other odd behaviors?

**Comment by josh-berry** [comment]
Glad to hear this helped. :)

If you're still seeing odd behaviors on 2.10.1 after clearing your saved session data, I'd love to see error logs from those instances as well.

> I think this is what you mean by Restart-Firefox-Without-Saved-Session-Data, ...

Yup that's exactly it.

> ... but the UI labels seem to have changed a bit since you wrote your guide.

It seems so, thanks for letting me know. I updated the guide.

**Comment by josh-berry** [comment]
Closing out both of these since it seems like everything got sorted out, but if you're still having issues, let me know!
