### ISSUE TITLE
Stashing all open tabs causes tabs to be added to existing (recent) tab group

### ISSUE THREAD

**Issue by Xiazee** [josh-berry/tab-stash#179]
### System Details
- **OS Version:** Windows 10
- **Browser Version:** 94.0.2
- **Tab Stash Version:** 2.10.1

### Describe the Bug
When stashing all tabs by clicking the "Tab Stash" toolbar button, or from the "Stash unstashed to new group" button in the sidebar, all the newly stashed tabs are added to the latest tab group, instead of a new group being created.

The tabs from the second window are below those from the first window.

### Expected Behavior
It should create a new tab stash group, at least one per browser window that you chose to stash.

### Steps to Reproduce
1. Open two browser windows with tabs
2. Stash all tabs in both in quick succession
3. Observe the tabs from both windows being stashed into the same group.

### Impact
This counteracts any attempt to group tabs by topic, as tabs from multiple windows will be mashed together.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out. This behavior is intentional, and it's there to help you efficiently collect tabs that should be in the same stash, but are spread across several different locations (within the same window, or across different windows).

If you find it bothersome, there are a couple ways you can work around it or turn it off:

1. When you want to start stashing to a different group, explicitly create a new empty group by clicking the blue icon with a `+` in *Unstashed Tabs*.
2. Rename the group you just created so it doesn't have a default name (i.e. `Saved <date/time>`). The next time you stash something, it will go into a new unnamed group.
3. Disable the feature entirely in the Tab Stash options.

If you want to disable the feature entirely, go to `Options...` in the Tab Stash menu, make sure `Show advanced settings` is turned on, then set the `Append to the top-most stash ...` option to 0 minutes.

Hope this helps, let me know if you have any more questions!

**Comment by Xiazee** [comment]
I believe this behavior was introduced in one of the recent updates.

The option specifically says "When stashing a *single* tab:", so it would sound like it shouldn't apply when stashing multiple tabs at a time.

And the button in the side bar also specifically says "to a new group". If I would like to append them, i would press the corresponding button on the existing group, instead of the one under Unstashed Tabs.

**Comment by josh-berry** [comment]
ha, you're right. I should read more carefully. 😆 

I'll definitely look into this and try to get it fixed soon. Sorry for the inconvenience!

**Comment by josh-berry** [comment]
This will be fixed in the next release!
