### ISSUE TITLE
Tab Stash consuming 30-40% CPU constantly after 2.10.1 update

### ISSUE THREAD

**Issue by giazzon** [josh-berry/tab-stash#180]
### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox 94.0.2 
- **Tab Stash Version:** 2.10.1

**Installed Browser Extensions:**

- uBlock
- Undo Close Tab
- Better Twitter
- LinkedIn Acitivity

### Describe the Bug

Since the 2.10.1 update, Tab Stash has been constantly consuming between 30 to 40% CPU. I could confirm this by using Firefox's Task Manager. Disabling Tab Stash resolved the issue. 

![image](https://user-images.githubusercontent.com/29783764/144494965-9af9bea1-2028-4c66-8bf3-35376f8a930a.png)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, sorry for the trouble and thanks for the report. Are you seeing any errors in the console log, and if so, can you share them? Here's how to check: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

As I mentioned in my reply to your review, 2.10.1 has a new "safety net" which is supposed to help Tab Stash recover from inconsistencies in Firefox itself (e.g. Firefox telling Tab Stash it opened a tab which then doesn't exist, that sort of thing), and it's possible this "safety net" is tripping repeatedly. Whenever the safety net kicks in, Tab Stash tries to re-sync itself with the tabs/bookmarks that are present in your browser, and depending on how many tabs and bookmarks you have, this can be an expensive operation.

The error logs should tell us for sure one way or the other, but if that is in fact what's happening, then clearing your saved session data should fix the problem. Here's how to do it if you want to give it a try: https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data

Let me know what you find!

**Comment by giazzon** [comment]
Hi Josh, tried clearing the saved session, no good. There's no log also. Is there a way to disable the "safety net" feature introduced in 2.10.1?

**Comment by josh-berry** [comment]
Got it. If you're not seeing any errors in the log, then it's not the safety net. An error log will always be emitted when a problem is detected that triggers the safety net (to help in debugging/figure out why it tripped in the first place).

Can you check if you've adjusted the privacy settings to remember deleted items? Tab Stash Menu > Options... > "Remember items that were deleted on this computer" (under "Privacy"). The default is 180 days; is it still 180 days or did you decrease it?

There's another known issue where if there are lots of deleted items to clean up at once, CPU usage will increase while the deleted items are cleared. This is only temporary though and will sort itself out once all the old deleted items are gone.

If you're impatient and you don't care about keeping any deleted items, you can uninstall and reinstall the extension (disabling/enabling is not enough), and the browser will wipe the deleted items for you. (Any stashed tabs you actually want to save will be preserved, since they're saved in your bookmarks and not in Tab Stash's storage.)

If you haven't adjusted the deleted-items settings, and if uninstalling/reinstalling doesn't help, then let me know and I can explain how to collect some performance data that will hopefully show where the CPU time is going.

**Comment by giazzon** [comment]
Well, I just enabled the extension after the weekend and it seems to have fixed somehow. I did not change the Tab Stash Menu > Options... > "Remember items that were deleted on this computer" option nor uninstalled it. CPU usage is fine now. I'll let you know if this happens again. Thank you for your support.
