### ISSUE TITLE
Anyone seen this? Click on links in Tab Stash instead opening recently opened tabs.

### ISSUE THREAD

**Issue by sbn-purchark** [josh-berry/tab-stash#188]
### Question
I don't want to start a new bug report yet, just wonder if I'm the only one seeing this strange behavior. This happens at random times. 

When clicking on links in tab stash to re-open, instead recently closed tabs open instead of the stashed tab. I have to close the wrongly opened tab and re-try, sometimes a multitude of times before it finally opens the stashed tab.

I tried clearing session data (several times)

### System Details
Tab Stash: 2.9 (I think it just happened in 2.10.1 also)

Tab management it set to close tab immediately. I don't have hidden tabs.

**Comment by josh-berry** [comment]
I’ve actually seen this happen once or twice myself, but only very occasionally and never more than once in a short amount of time. Now that I know I’m not just seeing things, I’ll take a closer look.

Since this seems to happen a lot more frequently for you, are there any patterns you’ve noticed? For example, is it always the most recently closed tab? Same/different site from what you were trying to restore? Was the restored tab from the same/a different window? Anything you notice along those lines would be helpful to know.

I do think it raises to the level of a bug though, so: sorry for the trouble and thanks for reporting it!

**Comment by sbn-purchark** [comment]
They are recently closed tabs, but I did not notice if they are re-opening in any particular order. It is occasional, it's just opening a multitude of recently closed tabs one after another (not simultaneously -- one per click) before going back to normal. I don't use multiple windows, so they're all from the same window. I'll pay more attention next time.

**Comment by nfp0** [comment]
I am also seeing this bug a lot, but I can't reproduce it consistently.
I have selected the option to "Close tab immediately" too, so it might be related to that.
I'm on version 2.10.1

**Comment by josh-berry** [comment]
I did some more testing on this last week with some extra logging in Tab Stash, and as far as I can tell, Firefox is just choosing the wrong tab to restore (e.g. Tab Stash is asking for tab X, and Firefox is restoring tab Y instead).

I can probably work around this by putting an option in Tab Stash to turn off restoring from closed tabs, but this one will need a fix from Firefox. :(

**Comment by sbn-purchark** [comment]
Apparently it can also include recently closed windows. It just opened a weird app like (blank title bar) window for my password manager that I have never seen before. I have Tab Stash setup to close tabs entirely, I wouldn't mind if it just threw away any session data and just opening a fresh tab every time.

**Comment by josh-berry** [comment]
Yes, I think this is probably an issue in Firefox--any recently-closed tab could be chosen, even tabs having nothing to do with Tab Stash. So I will look into disabling this feature (or maybe demoting it to an optional "experimental" status) in the next release so that Tab Stash only restores hidden tabs it controls, or creates new tabs.

**Comment by josh-berry** [comment]
I've put a change in for the next release to disable the behavior of restoring recently-closed tabs (though I've left it in as an experimental feature). That should address this bug and prevent Tab Stash from restoring the wrong tab going forward.

I went ahead and filed #200 to restore the feature once the Firefox issue is resolved.
