### ISSUE TITLE
start pages

### ISSUE THREAD

**Issue by exekutive** [josh-berry/tab-stash#193]
It would be nice if you could set a start page for a particular container tab.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
I'm afraid I have no idea what you mean by this, since Tab Stash doesn't deal with containers or start pages.

If this is a feature request, please [open a feature request](https://github.com/josh-berry/tab-stash/issues/new?assignees=&labels=&template=feature_request.md) answering the questions with as much context/detail as you can provide--this will help me to understand what problem you're trying to solve and what you're looking for. Thanks!

**Comment by exekutive** [comment]
oops! Sorry.
You can delete this one. Posted in wrong browser window  XD
