### ISSUE TITLE
Add option to change the default bookmark folder

### ISSUE THREAD

**Issue by cquike** [josh-berry/tab-stash#196]
### Problem Statement
It seems that this add-on will always store the tabs in bookmark folder "Other Bookmarks/Tab Stash". I think it would be great if the folder can be customized. In particular I have the problem that I synchronize my bookmarks with floccus (floccus.org) but I am synchronizing a given folder and I would like Tab Stash to be under that folder

### Preferred"  Solution(s)

Add an option to specify the folder to store the bookmarks. Probably there should be some text explaining that if you are synchronizing the bookmarks you have to use the same folder in all the browsers.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, I'm not sure I totally understand what you're asking, but if it's just that you want the "Tab Stash" folder to live in a specific place in your bookmark tree (so that it's picked up by floccus), that is possible today—just move the folder where you would like it, and so long as it keeps the exact name of `Tab Stash`, it will still be used.

(If you're curious, [this wiki page](https://github.com/josh-berry/tab-stash/wiki/Problems-Locating-the-Tab-Stash-Bookmark-Folder) explains how Tab Stash searches for its root folder.)

If what you're asking is to be able to use different "Tab Stash" folders on different computers, there's a feature request open for this as #162 (I'll give it a better title shortly so it's easier to find :/).

Hope this helps, let me know your thoughts!

**Comment by cquike** [comment]
Yes, that exactly solves my use case. I need the Tab Stash to be under "Other Bookmarks/Floccus/Tab Stash". I have now moved it and it worked :).
Maybe a small useful addition is to report _somewhere_ which is the bookmark folder that Tab Stash is currently using. Maybe in the preferences page (even if it is not an editable field).

**Comment by josh-berry** [comment]
Great, I made a note with your suggestion on #162, and I'll go ahead and close this one out, but let me know if there's anything else!

**Comment by AeliusSaionji** [comment]
I personally would like for my stashes to be visible on the bookmarks toolbar (and not within the Tab Stash subfolder)
