### ISSUE TITLE
Imports can only be 40KB maximum otherwise the importing process fails

### ISSUE THREAD

**Issue by desbest** [josh-berry/tab-stash#203]
### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox 96.0.1
- **Tab Stash Version:** 2.10.1

**Installed Browser Extensions:**

- Optional
- 

### Describe the Bug
Imports can only be 40KB maximum otherwise the importing process fails
This causes my links to fail to import after the 40KB cutoff limit is reached as well as there being a lack of title and icon for the ones that have imported.

### Expected Behavior
All links should import with a relevant icon and title to them.

### Steps to Reproduce

Try to import links to Tab Stash using a text input that is over 40KB. For easier reproduction use the default tab stash format (not the onetab format).

```

# Group 1
http://google.co.uk
http://bing.co.uk

# Group 2
http://amazon.co.uk
http://ebay.co.uk
```

### Impact

If someone is importing over 400-500 tabs then hours of waiting for the import process to finish, as Tab Stash opens each URL individually, will be a waste which can waste hours of time if the import batch is very big with a lot of URL's.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for the report and sorry for the trouble.

Were you able to get import working if you split things into smaller chunks? If it still got into trouble even after splitting, it would be helpful if you could share any error logs from the UI: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

Also, I'm also curious how you determined it was 40KB? When you say that:

> This causes my links to fail to import after the 40KB cutoff limit is reached as well as there being a lack of title and icon for the ones that have imported.

This suggests to me it might not have been the size so much as a specific URL that was causing an issue, since the import got to the point of actually creating bookmarks in your stash. For example, you filed #204--I'm wondering if this is just another occurrence of that bug?

**Comment by desbest** [comment]
> Were you able to get import working if you split things into smaller chunks? 
Yes.

> Also, I'm also curious how you determined it was 40KB? When you say that:
Because I tried to import a larger batch. If you must know, my original batch was a 20MB text file. Every time a batch failed, I just split it in half until that certain amount was reached

> For example, you filed #204--I'm wondering if this is just another occurrence of that bug?
No it has nothing to do with my #204. They are not related to each other. I only stumbled across these 2 bugs after moving from [Onetab](http://onetab.com) to Tab Stash.

**Comment by josh-berry** [comment]
Got it, thanks for the clarification. I'm not sure where the 40KB limit would be coming from (there's nothing explicitly in Tab Stash which would enforce such a limit), but I'll take a look and see what I can discover.

**Comment by josh-berry** [comment]
So I've done quite a bit of testing on this finally, and I'm not able to find anything that might be responsible for causing imports to fail after 40KB—I was able to do imports of 10s of thousands of tabs in one go with no problem (though it did go very slowly)—I think I got as high as ~600KB before it took long enough that I didn't want to wait anymore.

A lot has changed in both Tab Stash and Firefox since this issue was opened, so I'll go ahead and close it, but if you continue to have problems with large imports, please feel free to open a new issue (and please share any crash messages you get—the more detail, the better)!

**Comment by desbest** [comment]
I’ve just tried it again and now it works. So whatever you did since January, must have fixed things.
