### ISSUE TITLE
Is there a way to close (or even stash) all current open tabs upon loading a tab group?

### ISSUE THREAD

**Issue by fbracht** [josh-berry/tab-stash#206]
### Question
Hello! 

I feel like I may be overlooking something, but I didn't find a way to open an entire tab group destructively — essentially replacing the currently opened tabs with the tab group. Is there a way to do this? 

For a bit more context, what I'm trying to do is to have different tab groups for different activities, occasionally adding or removing tabs from these groups. I _can_ do this currently, but it involves manually closing all open tabs before loading a new tab group. It'd be neat to be able to do both of these actions (closing all tabs, then loading the group) from Tab Stash with the same click, and I don't know if this is possible.

Thank you! 

(And, also: even if this isn't possible, Tab Stash is still kickass, and reason alone to switch to Firefox!)

**Comment by josh-berry** [comment]
Hi! It's not possible as such with a single click as such, but:

> For a bit more context, what I'm trying to do is to have different tab groups for different activities, occasionally adding or removing tabs from these groups.

This was exactly the thought behind making the "Tab Stash" button in the toolbar stash everything by default and show the stash—the idea was, "save what I'm doing now, get me back to a clean slate, and show me what else I could be doing (i.e. other saved stashes)". Of course, that's proven to be confusing for new users and I suspect a lot of people change it, so I will probably change the default in a later release.

However, it's possible in two clicks:

1. The `[X]` button in Unstashed Tabs (the X fully-enclosed in a box) will close all open tabs
2. Find the stash you want and restore it

It's definitely something I've given some thought to though (along with its counterpart, replacing the contents of a stash with the currently-open tabs), because the ability to easily task-switch is one of the primary reasons I built Tab Stash.

> (And, also: even if this isn't possible, Tab Stash is still kickass, and reason alone to switch to Firefox!)

Thanks, that's really nice to hear! 😄 Glad you're finding it useful and I hope the above helps!

**Comment by josh-berry** [comment]
I’ll go ahead and close this out but feel free to leave any follow-up questions! You might want to keep an eye on #157 which is related—it’s complementary to what you’re asking here, but with the same underlying goal. (And I made a note there so I won’t lose track of this discussion.)
