### ISSUE TITLE
Unable to open all tabs in a group

### ISSUE THREAD

**Issue by Comicsansproductions** [josh-berry/tab-stash#211]
### System Details
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.90 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

- **OS Version:** Windows 10
- **Browser Version:** Firefox 96.0.3 (64-bit)
- **Tab Stash Version:** 2.10.1

**Installed Browser Extensions:**
- AdBlocker Ultimate
- Better TweetDeck
- DuckDuckGo Privacy Essentials
- Enhancer for YouTube
- Honey
- Minimal Theme for Twitter
- Tree Style Tab

### Describe the Bug

Clicking "Open all tabs in this group", "Open all tabs in the group and delete the group" and "Open this tab and delete it from this group" results in this error message: Error while fetching an original source: NetworkError when attempting to fetch resource.
Other actions such as Deleting or Stashing active tabs work as intended.

### Expected Behavior

For TabStash to open all tabs in a group.

### Impact

I am unable to open an entire group of tabs with the click of a button. I am able to reopen specific tabs by either right-clicking and selecting "open in new tab" or by opening Firefox's hidden tabs drop down menu. But to go through that process with about 100+ tabs is a bit time consuming.

### Additional Details

the entire error log 
![image](https://user-images.githubusercontent.com/47769409/152473019-3d5555cb-d43d-4a80-a998-eeaeca3881e6.png)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Sorry for the trouble! The rather unhelpful “An unexpected error occurred” message usually shows up when something internal to Firefox went wrong. Since it only seems to happen when you try to open a tab, I’m suspecting it’s something related to Firefox’s session data (keeping track of which tabs are open, were recently closed, etc.)

Can you give the steps here a try and let me know if you’re still hitting the issue?

https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data

**Comment by Comicsansproductions** [comment]
Hi! Sorry for the late reply. I gave the steps a try and it worked! Thanks so much for the help!
