### ISSUE TITLE
Option to change sidebar shortcut

### ISSUE THREAD

**Issue by ClipLee** [josh-berry/tab-stash#212]
### Problem Statement

Option to change keyboard shortcut as it doesn't work for my language because it's a letter. 
In my language (polish) 🇵🇱  <kbd>Ctrl </kbd>+  <kbd>Alt </kbd> + <kbd> S </kbd> inputs a letter from a polish alphabet: "ś". That way I think I cannot access the shortcut for the sidebar which is quite a problem. I have to click the icon which makes my workflow worse.

### Preferred Solution(s)

Option to change keyboard shortcuts in settings.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, this functionality is available in Firefox itself. Since others might have this same question, I just wrote a wiki entry on how to change the shortcuts. You can find it here:

https://github.com/josh-berry/tab-stash/wiki/Changing-Keyboard-Shortcuts

Hope this helps and let me know if you have any more questions!
