### ISSUE TITLE
Confirmation mechanism before deleting data? I lost my session tabs twice.

### ISSUE THREAD

**Issue by lyne408** [josh-berry/tab-stash#213]

**Comment by ClipLee** [comment]
Please use "Issue: Request a Feature" template. Put at least that much effort to fill it with basic details. Your Issue contains no description whatsoever.

**Comment by josh-berry** [comment]
For tabs which are closed, Firefox remembers your history: Firefox menu > History > Recently closed tabs/windows

For bookmarks which are deleted out of Tab Stash, you can find them in "Deleted Items" (under the Tab Stash menu).

And yes, please do fill out the template, even if you're just asking a question. Otherwise it's hard for me to know what you're asking. Thanks and hope this helps!
