### ISSUE TITLE
Only load favicons for selected stash group and cache results while doing so

### ISSUE THREAD

**Issue by WebMechanic** [josh-berry/tab-stash#227]
### Problem Statement
The "fetch missing icons" option today retrieves the icons of **all** bookmarks in **all** stashes -- which could be a mightly lot.

It also seems to fetch icons multiple times from URLs that have already been crawled. Since domains only can have one favicon, Tab Stash should cache these icons while updating ad use the ones already downloaded.

### Preferred Solution(s)
Add context menu option ("right click") to a stash group to limit icon updates to that group only.

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
> Since domains only can have one favicon

Actually this isn’t true. A number of very common sites (Google, Office 365, etc.) have icons that change depending on which page on the domain you’re looking at. (Google Drive/Docs is a particularly bad offender here.) Pages can set their icon in a variety of ways—using the good old `favicon.ico` trick, putting the icon in the `<head>` metadata inside the page, or even updating the icon after the fact using JavaScript.

So unfortunately we do have to load each and every unique URL to get icons that are not misleading. (And individual URLs are de-duplicated to avoid hitting the same page more than once.)

If you’re interested in loading the icons only for a specific stash, the easiest way to do this is just to open the tabs in the stash—you actually don’t need to use “Fetch Missing Icons” at all. When the pages are loaded, the icons will be cached for later.

Hope this helps!

**Comment by WebMechanic** [comment]
understood.
I was only thinking about the default `favicon.ico` and the `head` variants.
Never been that obvious to me that a site uses different icons for different pages, at "worst" they may change per sub-domain.
I don't (actively) use any Google products other than YT so I wouldn't know - nor care :-)

Opening dozens of tabs in a stash just to retrieve their icon and than bother closing them again kind of defeats the purpose of the feature, I believe.

I don't understand why these icons do not persist and get lost in the first place. Maybe it's during Sync 🤔
They are part of the bookmark and stored and referenced in their own db table, right? At least that used to be the case and FF would (usually) store a single icon per URL and reference that icon's id in the bookmark.

**Comment by josh-berry** [comment]
> They are part of the bookmark and stored and referenced in their own db table, right?

Actually no, they're stored completely separate from bookmarks. For whatever reason, Firefox does not provide a way for extensions to retrieve a cached favicon for a site. So Tab Stash has to maintain a cache on its own (and that cache is not synced because Firefox offers very very limited synced storage for extensions--enough for preferences but not much else).

I did a fair amount of research into this problem when building the feature, and unfortunately there's really no standard way to get the favicon for a URL apart from just loading the page and seeing what happens. I agree it's inefficient, but it's the best option available right now.

**Comment by KerfuffleV2** [comment]
This is the relevant Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1315616

Sadly it doesn't seem to have made much progress since it was 5+ years ago. The comments possibly imply that the feature could be included with WebExtension manifest version 3.

Maybe something like an option that only fetches favicons once per domain when loading. This wouldn't always be correct, but visiting the site would fix the icon and the majority of sites aren't doing dynamic favicon stuff. I think that's something I'd use.

**Comment by WebMechanic** [comment]
> they're stored completely separate from bookmarks.

I recall fiddling with FF's many sqlite databases a while ago and there was one with encoded icons and some ref-ids to the bookmark using it. That's where that idea of "it's cached and linked" coming from. I expected FF to handle this 'cos the Tab Stash folder is just another bookmark folder it seems.

They messed up Bookmarks when they also removed comments (of which I had zillions), so maybe that former "link" is gone, too.

**Comment by WebMechanic** [comment]
> This is the relevant Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1315616

thanks for the link. 
I added a comment. 
Maybe you should post your interest in a viable solution and API ? :)

**Comment by josh-berry** [comment]
I did vote for this already, but unfortunately I think Mozilla has quite a few higher-priority things on their plate at the moment.

**Comment by WebMechanic** [comment]
they always have. 
I've seen bugs and feature request sitting there for +15yrs before someone decided to give it a go. 
So there's still hope :D
