### ISSUE TITLE
Tab Stash in a tab (pinned) gets closed everytime firefox updates

### ISSUE THREAD

**Issue by iPaulis** [josh-berry/tab-stash#235]
### System Details

- **OS Version:** Win 10
- **Browser Version:** Many Firefox versions, for example v97 or v98
- **Tab Stash Version:** any Tab Stash version, it has always behaved like this

**Installed Browser Extensions:**

-
-

### Describe the Bug

Tab Stash when displayed in a tab, and then pinned to use it recurrently to save and restore tabs, gets closed everytime firefox updates. So after any update and restart of firefox, the tab stash tab is no longer there, even if it is pinned, it does not get restored like all the other tabs restored from the previous session, as it would normally do in a regular close and start of firefox (without update).

### Steps to Reproduce

1. Show tab stash in a tab
2. Pin it
3. Apply firefox update and restart
4. All the other tabs are restored, but the tab stash tab is not.

### Expected Behavior

To keep showing the tab, specially if it is pinned.

### Impact

It is uncomfortable to have to display the tab and pin it everytime firefox updates.

Thank you in advance.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately, there's probably nothing I can do here. Whenever *any* extension is updated (and, it seems, when Firefox itself is updated), the extension has to be completely unloaded to finish the update successfully. This means closing all open UI elements, including tabs (which are different from regular tabs since they run in a privileged context inside the browser).

Otherwise, older bits of the extension might be left running, and it would cause all kinds of problems to have old and new bits mixed together.

I also wish there were a nicer way to handle this--I have to update Tab Stash *all the time* (sometimes once every few minutes) while I'm doing development, and it's annoying to have to re-open the Tab Stash tab every single time. So I can definitely sympathize.

Sorry to be the bearer of bad news here. It might be worth sending some feedback to Firefox; maybe they can find a way to simply reload extension tabs on an update instead of completely closing them.

**Comment by iPaulis** [comment]
Understood. Thank you for taking your time to explain.
