### ISSUE TITLE
All stashed tabs disappeared. How do I restore them?

### ISSUE THREAD

**Issue by Pilnath** [josh-berry/tab-stash#251]
### Question
All my stashed tabs suddenly disappeared. Is there any way to retrieve them?

### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox 99.01
- **Tab Stash Version:** Tab Stash 2.10.3

**Comment by josh-berry** [comment]
It’s possible that a Firefox Sync issue has moved things around in a way that caused a problem for Tab Stash (e.g. due to a sync conflict). Here’s a wiki entry that might help: https://github.com/josh-berry/tab-stash/wiki/Problems-Locating-the-Tab-Stash-Bookmark-Folder

If you’re still missing your tabs after trying the suggestions in the wiki, please let me know what you tried/what you discovered and we can go from there. Good luck!

**Comment by Pilnath** [comment]
Thanks a lot for this. Got all my tabs back
