### ISSUE TITLE
"Your browser won't allow Tab Stash to restore tabs that show files on your computer"

### ISSUE THREAD

**Issue by SDavidHicks1** [josh-berry/tab-stash#255]
### Question

"For security reasons, your browser won't allow Tab Stash to restore tabs that show files on your computer without your intervention.
Please make sure this URL looks right. If it looks okay, you can restore the tab by copying and pasting the URL into the address bar:"

Is this the way it's going to be now? I have to paste URLs into the address bar. because Tab Stash does not have authority to open local files itself? The above message suddenly appeared today for the first time, upon clicking on a local file URL in Tab Stash. Version 2.10.3.

### System Details
2.10.3

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- Windows 11
- **Browser Version:** [e.g. Firefox 60.0.2]
- Firefox 100.0
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]
2.10.3
![Screenshot 2022-05-05 121323](https://user-images.githubusercontent.com/67767630/166966843-5c48bfb7-211b-45aa-bcbe-30e8ee819b05.jpg)

**Comment by josh-berry** [comment]
Unfortunately, it's been like this since the inception of Tab Stash (although the nice message telling you you have to do the thing by hand is more recent—opening `file:` URLs used to just fail silently in early versions of Tab Stash). Browsers generally don't allow extensions to access privileged URLs, and there's no way for an extension to request permissions for this, either.

However, for the most part, you shouldn't notice this limitation because Tab Stash keeps stashed tabs open in the background by default, and it can just switch to the hidden tab—there's no permission problem since the tab is already open. If you closed the hidden tab somehow (e.g. by closing the window it was in, doing a clean restart of your browser, etc.), then this message will appear.

If it helps, you can at least click on the URL to copy it to the clipboard (so you don't have to click/drag, hit Ctrl+C, etc.). I know it's not ideal, but unfortunately I haven't found a less-annoying way to handle this.

Sorry for the trouble, let me know if that answers your question!

**Comment by SDavidHicks1** [comment]
Thanks very much for your prompt reply! Sorry, today was the first time I
noticed this behavior, and it surprised me at first. I started to open a
group of around 10 local files for pages of my website, and I expected them
all to open instantly, but got the message instead.

I understand the security issue and, as you said, it's been like this since
the beginning. Since I didn't notice it until now, it's no problem. I did
see you can click the URL and it is copied.That's good.

*Let me ask you about* "Tab Stash keeps stashed tabs open in the background
by default." I have my Options set to "Hide the tab and immediately unload
it." Does this affect the behavior of switching to the hidden tab? Do I
need to set the radio button to Hide the Tab and Keep It Loaded, instead?

Thoughts on Tab Stash: Tab Stash must be my favorite Firefox extension (as
in, most frequently used and enjoyed) these days. I could tell as soon as I
discovered it about a year ago that it was a labor of love, or at least, a
fine piece of engineering! It immediately replaced OneTab. It has lots of
good features and is continually improved. Awesome. Thanks, again.

David Hicks

**Comment by josh-berry** [comment]
Hi David,

> I have my Options set to "Hide the tab and immediately unload it." Does this affect the behavior of switching to the hidden tab? Do I need to set the radio button to Hide the Tab and Keep It Loaded, instead?

Either of the "Hide the tab ..." options will keep the tab open (but hidden) so that Tab Stash can find it again when you try to restore it, so both options should behave the same when stashing `file:` URLs. The only option that would cause you to see this warning more often is the option "Close the tab immediately".

> Tab Stash must be my favorite Firefox extension (as in, most frequently used and enjoyed) these days. ...

Thank you very much for the kind words! Tab Stash is indeed a labor of love—it's been a lot of fun to build, and I've learned a lot in the process. I'm really glad to hear you're enjoying it.

I'll go ahead and close this issue, but feel free to leave another comment here if you have any more follow-up questions, or open a new issue if there's anything else you need!

— Josh

**Comment by SDavidHicks1** [comment]
Hi Josh,

I just want to say thank you.  I appreciate the excellent support.

**Comment by josh-berry** [comment]
> I found myself in the exact same situation and I was wondering if there was a flag in about:config to remedy this?

I'm afraid there isn't—opting out of this restriction would create security issues. For example, if a website or extension opened a local file in a tab without your knowledge or consent and then interact with that file, it might be able to steal data. Or worse, it might be able to use special/privileged URLs to trigger other actions on your computer that you didn't intend.

So—for better or worse—there's no way to turn it off, and even if you could, doing so would not be a good idea.
