### ISSUE TITLE
Not all tabs are visible in the sidebar

### ISSUE THREAD

**Issue by q2p** [josh-berry/tab-stash#260]
### System Details
- **OS Version:** Windows 10 21H1 (x64)
- **Browser Version:** Firefox 100.0.02
- **Tab Stash Version:** 2.10.3

### The Bug
After installing the Tab Stash, a sidebar appeared. I have 268 opened tabs, and the biggest window has around 150 tabs. The sidebar shows only the last ~130 tabs. The first 20 are invisible.

![TabStash screenshot](https://user-images.githubusercontent.com/11664429/169674653-0a6a5a16-252e-43c8-a75c-f76c6c3d85f0.png)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Which tabs are missing? Are they pinned or already saved in your stash?

If they are pinned, Tab Stash will purposefully ignore them, because pinned tabs are typically pinned because the user wants them to stay open (i.e. never be stashed).

If they are stashed, then they won't show in the "Unstashed Tabs" list, but you'll be able to find them in the list of stashed tabs. Tabs which are stashed but open will have a blue color (just like the ones in "Unstashed Tabs").

Hope the above helps, let me know if this addresses your concern.

**Comment by josh-berry** [comment]
Closing since I haven't heard back with any more details. If you're still seeing this issue, please do let me know and I can always reopen the issue. Thanks!
