### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by q2p** [josh-berry/tab-stash#261]
### System Details
- **OS Version:** Windows 10 21H1 (x64)
- **Browser Version:** Firefox 100.0.02
- **Tab Stash Version:** 2.10.3
- **RAM:** 32 GiB
- **Windows RAM Swap:** Disabled

### The Bug
I have 268 tabs open and tens of thousands of bookmarks saved.
When I originally installed Tab Stash on a long-living Firefox process, it crashed the process after eating all the RAM.
I tried installing the Tab Stash on a freshly opened window with all tabs suspended.
Before installation a freshly opened Firefox instance used 1.3 GiB of RAM, after installation it used 5.2 GiB of RAM.
Spending almost 4 GiB on five sidebars in five windows is too much.

![Task Manager](https://user-images.githubusercontent.com/11664429/169674882-d3f58bb0-85ee-4107-a32f-7a6538485a5d.png)
![Task Manager](https://user-images.githubusercontent.com/11664429/169674884-7d540838-74a4-4f51-9977-70e5eb1a7fe8.png)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
When you say "tens of thousands of bookmarks", is this closer to 10,000 or 100,000?

The reason I'm asking is, Tab Stash has been tested to work well with bookmarks towards the lower end of that range, but has not been tested at the higher end. So I would not be surprised if there are performance concerns with extremely large bookmark databases. This is something I want to address in future, but to be honest, it has been a lower priority because the vast majority of users have fewer than 10,000 bookmarks.

So if you're on the higher end of that range, then unfortunately the best I can say--for now--is Tab Stash is not designed for such an extreme use case. But if you're closer to the 10,000 mark, then I'd definitely like to debug with you further. Either way, let me know!

**Comment by josh-berry** [comment]
Closing since I haven't heard back on this—if you're still seeing high RAM usage, please do answer the questions above. Thanks!
