### ISSUE TITLE
Stash All Except option

### ISSUE THREAD

**Issue by skaryzgik** [josh-berry/tab-stash#265]
#### Background

I often don't realize I have too many tabs open for my own brain to handle until I already have too many tabs open for my own brain to handle.

Sometimes this is when I have just started a new task, which I already have a tab open for. Other times it is when I am in the middle of something and suddenly notice that some of the stress I'm feeling is from all the other tasks' tabs cluttering things up. 

Sometimes the line of what is or is not the same "task" is unclear, since I also often end up reading about similar topics related to the initial topic, get distracted by that from the initial topic, and then continue to tangent further and further away from the initial task, recursively. These tabs are clearly not "one" topic or task. But how many topics or tasks are they? Three? Five? Seven? More? This can make choosing which tabs to group together more difficult, since even the number of groups that would be useful is unclear.

And that being difficult, leads me to procrastinate doing so even further. So sometimes even when I know I'm starting a new, clearly separate task, I will still sometimes not stash the existing ones before opening the new one.

To clarify, these above things are not things I am expecting a browser extension to fix. I am including them as part of the request for "as concrete, specific and detailed as possible" description of what is prompting my request and why it is important to me. And so that my explanation of the way I currently use this extension might make more sense, so that in case it's "unusual" or "not the intended way to use the extension" it might still be easier to see why some people who find the extension useful might also find this feature to be a useful improvement.

#### The Thing I Do

When I do stash, I usually just put them all in the default timestamp-named one new group. I can "organize" them "later." And in the meantime, I can use the search bar of the stash to find what I want when I want it. For now, I just want them "out of my face" so I can feel like I can think again.

But sometimes, possibly often, I already have one or a few tabs open for the task I *do* want to be doing. Those tabs, I *don't* want "out of my face." I *don't* want them to "go away."

#### The Thing I Want to Do

At times like these, I want an easy way to stash *almost* all of the tabs. Usually either all tabs except the one I am on, or all except for a small handful I can select.

### Preferred Solution(s)

In addition to actions like "Stash All" or "Stash Selected" or "Stash This Tab", I would like to see alongside that "Stash All Except (current or selected)". This could be accessed via a button, or a right-click menu from the page, tab, or toolbar button.

Individually adding each tab I want to stash to the set of selected tabs in order to do "Stash Selected" is not feasible with as many tabs as I sometimes get. I don't know how many that is, because I haven't counted recently. The stash search bar currently states I have a current total of 128 groups with 2349 total tabs, which would suggest an average of about 18 tabs per stash, but since I also tend to stash everything before I shut down or reboot my computer so I can start "fresh" after that, and some days I only do a small amount of internet reading, there are probably a not insignificant amount of those groups with significantly fewer tabs in them. Which means that at the times I'm stashing for this reason, there would be more than that at a time to stash.

### Alternative Solution(s)

I can think of a few possible workarounds where I could accomplish my goal without this feature being added to the extension.

1. I could make a new stash of the tabs I do want to keep open, so that they "go away" *temporarily* into a place I can quickly find them again in just a moment, then stash the rest of the tabs, then reopen my "temporary" stash.

1. I now observe that if I right-click on a tab in the tab bar, one of the options is "Select All Tabs." If I start with that, I could then *un*select the tabs I want to keep, and then "Stash Selected Tabs."

1. I feel like I thought of something else too but I took too long writing and forgot it.

If it isn't too much trouble, I still think having a specific thing to click on or keybind for to close all except a few would still be more convenient than either of these.

### Additional Context

If my brain sounds very weird, it's probably because of my ADHD. (But others may have other reasons for having similar tendencies, even if they don't have this specific thing.) This browser extension is already quite useful in reducing the stress I feel as a result of some of the weird things my brain does. (Alas, only in the context of web browsing, but given that that's a large part of my time, that is still quite an improvement!) And it is my hope that it will continue to become better. :-)

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
First off, sorry for the delay in responding—a combination of work and real-life events has kept me away from Tab Stash for a bit.

Thank you also for giving such a detailed backstory. I wish more people would take the time to do that, since it helps me to really understand the problem you're trying to solve and gives me a clearer picture of what might not be working for you.

First for the non-technical part of your feature request:

> Sometimes the line of what is or is not the same "task" is unclear, since I also often end up reading about similar topics related to the initial topic, get distracted by that from the initial topic, and then continue to tangent further and further away from the initial task, recursively. These tabs are clearly not "one" topic or task. But how many topics or tasks are they? Three? Five? Seven? More? This can make choosing which tabs to group together more difficult, since even the number of groups that would be useful is unclear.

In my experience this is a *very* common problem and one I also suffer from myself. For what it's worth, the way I've found that works for me is making a *deliberate* practice of sorting my tabs into groups frequently. I try to bake it into my routine at the end of my work day—run through all of my open tabs, move each one into the right group, close the ones I don't need anymore, etc.

If I can do that frequently enough, it keeps the overwhelm/distraction under control and isn't too hard to get back to a clean state. If I miss a few days or even a week, well, then it's much harder.

-----------

Now onto the technical part / specifics of how to "stash all except"...

I'm not sure if you're aware of this, but there's a multi-select feature in the Tab Stash UI itself (in addition to multi-selecting browser tabs in the Firefox tab bar). Clicking on the icon of a tab will select it, and then you can shift-click to select multiple tabs at once. So you could try something like this:

1. Click the icon of the first tab in "Unstashed Tabs"
2. Shift-click the last tab in "Unstashed Tabs" to select all your unstashed tabs
3. Click the individual tabs you want to keep open to de-select them
4. Move the selected tabs to a new stash by clicking the blue "New Stash" icon under "Unstashed Tabs", or by using the blue "selection menu" that appears at the top whenever you select a tab.

Here's what it looks like:

<img width="329" alt="Screen Shot 2022-07-04 at 11 13 06" src="https://user-images.githubusercontent.com/1203893/177202578-500c18a5-1202-41d6-baa3-c80bcea92690.png">

If you haven't tried this already, please do and let me know how it works for you. Or if that proves too cumbersome, let me know your thoughts!

**Comment by josh-berry** [comment]
Hi @skaryzgik , I know it's been a while but I wanted to check back in with you on this, especially since you took the time to write such a detailed feature request (thank you again!). Did the above suggestions help at all with your use case or are you still finding it difficult to "stash all except ..."? Please let me know, thanks!
