### ISSUE TITLE
Warn before closing all open / all unstashed tabs

### ISSUE THREAD

**Issue by jebbinBjss** [josh-berry/tab-stash#268]
### Question
I clicked "close all open tabs" on the unstashed tab section by mistake because of a misclick. 
Is there any way to undo this? I've already looked into the firefox history, and only a limited number of tabs could be reopened through that, so I'm worried they've been lost. 

### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox 101.0.1 
- **Tab Stash Version:** 2.10.3

**Comment by josh-berry** [comment]
Sorry for the delay in responding. Unfortunately, there's not a good way to restore unstashed open tabs that aren't captured by Firefox's "recently-closed tabs" list.

If you remember what some of the individual tabs were, you can probably find them through your browser history (which goes back further in time), but that's generally going to be hard because they'll be mixed in with all the other sites you visited during the same time.

I don't understand why Firefox doesn't keep ALL the tabs that were closed "recently", but it seems to be limited by number of tabs. Sorry to be the bearer of bad news here.

**Comment by jebbinBjss** [comment]
I thought that was the case, so thanks for responding!
Could I suggest adding verification do destructive actions like this? Or rather, any action that you can't easily undo.

**Comment by josh-berry** [comment]
Sure, I'll keep this in mind! Will convert this ticket to an enhancement and rename it so it's easy to find.

**Comment by jebbinBjss** [comment]
Great, thank you!

**Comment by josh-berry** [comment]
This will be in the next release!
