### ISSUE TITLE
Stashed tabs with file scheme cannot be restored

### ISSUE THREAD

**Issue by RST-J** [josh-berry/tab-stash#27]
**Describe the bug**
I stashed a session yesterday which had tabs with file:///-URIs. Stashing them worked, but restoring the group only brings back the tabs with https scheme, the file tabs remain in the group. Also clicking on one of these stashed tabs or trying to use the restore-and-delete-button for one particular tab does not work.

**To Reproduce**
1. Open website of choice in a tab
2. Open file:///home/user/what/ever.pdf in another tab
3. Stash the tabs
4. Restart the browser and click on the yellow restore and delete button for the group

**Expected behavior**
Both tabs are restored and the group gets deleted.

**Desktop (please complete the following information):**
 - OS: Kubuntu 19.04
 - Firefox Browser Version: 67.0.4

**Comment by josh-berry** [comment]
Hi, thanks for your report! I looked into this, and unfortunately it's due to browser security restrictions. AFAICT Firefox won't allow extensions to open tabs which point to arbitrary `file:///` URIs because of the potential for abuse (one could, for example, open any arbitrary local file, take a screenshot of the tab showing the file, etc.). So unfortunately there's nothing I can do to make `file:///` URIs work.

That said, Tab Stash should have excluded them as "system" tabs (so they don't show up in the stash list at all and they are ignored when stashing). I will look into fixing this for the next release, so it's at least obvious that this won't work. Then it will hopefully be less confusing.

Sorry to be the bearer of bad news. :/

**Comment by RST-J** [comment]
Thanks for the quick response. I actually suspected something like this because of potential security risks. However, it would be great to have these tabs excluded. :+1:

**Comment by josh-berry** [comment]
This is now fixed as of Tab Stash 2.4, just released. We will now correctly treat `file:...` URLs as though they were system tabs, and won't allow them to be stashed. Thanks again for the report!
