### ISSUE TITLE
Pinned Tab Stash Tab gets forgotten

### ISSUE THREAD

**Issue by ColonelClaw** [josh-berry/tab-stash#282]
### System Details
- Windows 10
- Firefox 103 64-bit
- Tab Stash 2.10.3

**Installed Browser Extensions:**
- uBlock Origin
- Bitwarden

### Describe the Bug

When I have my Tab Stash pinned as a tab and I restart Firefox the tab disappears. All other pinned tabs and open tabs reappear as expected

### Steps to Reproduce
1. Right-click Icon, select "Show Stashed Tabs in a Tab"
2. Right click the tab and select "Pin Tab"
3. Close Firefox
4. Open Firefox, pinned tab is gone :(

### Expected Behavior
Up until recently the pinned tab was there

### Impact
It's a bit annoying!

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Sorry to hear you're having trouble—can I ask how you installed Tab Stash? Did you install it through the [official add-on page](https://addons.mozilla.org/en-US/firefox/addon/tab-stash/) or by some other method?

Usually this happens because the browser has unloaded the extension or decided to reload it for some reason. I would suggest you try uninstalling and reinstalling the extension and see if that resolves the issue. (Your stashed tabs will be safe, since they are saved in your bookmarks, however you may have to reset any Tab Stash settings that you changed from their defaults.)

**Comment by josh-berry** [comment]
Going to close this one out since I haven't heard back from you, but do let me know if the above didn't help!

**Comment by a-rock-lobster** [comment]
I too have this issue. Tab Stash always disappears as a pinned tab upon restarting Firefox. I tried reinstalling to no avail. I installed through the Firefox addon platform.
