### ISSUE TITLE
Add menu items for address bar button

### ISSUE THREAD

**Issue by wordpure** [josh-berry/tab-stash#285]
### Problem Statement
I hope to replace Tab Stash's page context menu with the address bar button, but I found that the address bar button lacks the ability to set extensions and manage all tabs compared to the page context menu.

![图片](https://user-images.githubusercontent.com/68013962/186410757-bacec302-dbf0-45f1-b12a-bfb15c12567a.png)

![图片](https://user-images.githubusercontent.com/68013962/186410909-837e06ff-9738-40eb-abd1-fc5b662b95b5.png)

### Preferred Solution(s)
Make the address bar button have as many menu items as the page context menu.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately, this is because Firefox only allows extensions to show up to 6 menu items for the address bar button (the same restriction applies to the toolbar button)—and Tab Stash is already showing 6 items (including the separator after "Show Stashed Tabs..."). Any more items simply won't get displayed.

Sorry to be the bearer of bad news here!
