### ISSUE TITLE
Tab Stash consuming too much CPU in Firefox 

### ISSUE THREAD

**Issue by giazzon** [josh-berry/tab-stash#290]
Title. I'm running Firefox 104.0.2 with Tab Stash 2.10.3 in a MacBook M1. Enabling Tab Stash makes the "Extensions" process in Firefox go over 99%. Had to disable it. By doing so, the "Extensions" process goes to normal.

**Comment by josh-berry** [comment]
Most likely a dup of #240, which will be fixed in the upcoming release (due out as soon as Mozilla approves it). Please try this workaround and let me know if you still see the issue:

https://github.com/josh-berry/tab-stash/issues/240#issuecomment-1116344578

If the above workaround fixes the problem, then you should be all set so long as you have at least one stash. But if it doesn't help, then please let me know the following info:

1. Roughly (order of magnitude estimate is fine) how many bookmarks you have overall (including outside of Tab Stash)
2. How many groups and tabs you have saved in Tab Stash
3. Any particular situations in which you see the CPU usage increase? e.g. after performing certain operations in Tab Stash or Firefox

Hope this helps!

**Comment by giazzon** [comment]
It helped! Removed and installed the extension again and the CPU usage is no more. Thank you for the prompt help and for having created this great tool.
