### ISSUE TITLE
Add option to disable Google service.

### ISSUE THREAD

**Issue by spiralsam** [josh-berry/tab-stash#3]
Getting icons from Mozilla API would be ideal - or until that becomes possible, getting from the site itself (like [Bookmark-search-plus-2](https://github.com/aaFn/Bookmark-search-plus-2/wiki/Permissions-and-Privacy-policy) does). Simply having the option to turn the feature off would be good enhancement, though.

**Comment by josh-berry** [comment]
100% agree—I consider this a privacy concern which is fairly high on my list of priorities. I've been working on a way to do site icons in a self-contained fashion, but it's unfortunately quite difficult. As you probably noticed from Bookmark-search-plus-2's permissions, doing it the "correct" way requires asking for the "Access your data for all websites" permission. This is way more access than Tab Stash really needs, so I've been looking at ways to save/cache icons locally, which is possible with the current set of permissions.

You have a good point about turning them off entirely. If I don't find a good approach to caching relatively soon, I'll probably go this route.

**Comment by junkblocker** [comment]
Hello @josh-berry, any update on this?

**Comment by josh-berry** [comment]
Yes, I assigned this to myself because I'm actively working on it now. Tab Stash is a spare-time project for me so I can't make any promises on timing/when it will be released, but it's at the top of my list.

Right now my plan is to save website icons from open tabs to a local cache, and rely only on the cache for populating the stash list. This would eliminate the last (and only) set of web requests actually initiated by Tab Stash, with the caveat that sometimes a site icon might not be visible if there's nothing in the cache for that site. I think this is a reasonable trade-off for improved privacy vs. any other alternative (e.g. hitting each site directly or going through Google).

That said, I haven't decided yet whether this should be opt-out or opt-in at first. Eventually, I want the cache to be the only option and fetching icons from Google will go away entirely. But I want to see if there are any steps I can take to make it a smooth transition.

**Comment by josh-berry** [comment]
Tab Stash 2.4 no longer relies on Google (or any other service) for showing favicons—we can now cache them as described above.
