### ISSUE TITLE
Tab History is not being saved

### ISSUE THREAD

**Issue by waliddamouny** [josh-berry/tab-stash#301]
### System Details

- **OS Version:** [Windows 11]
- **Browser Version:** [Firefox 106.0.5]
- **Tab Stash Version:** [2.11.1]

**Installed Browser Extensions:**
-No known incompatible extensions are installed in Firefox https://github.com/josh-berry/tab-stash/wiki/Known-Incompatibilities-with-Other-Extensions

### Describe the Bug
The back/forward history of the tab used to be saved when retrieving a stashed tab but it isn't anymore. It's just a stash of bookmarks.

### Steps to Reproduce

1. Open a webpage
2. Navigate to other links
3. Stash the tab
4. Unstash the tab and the tab will lose it's history

### Expected Behavior
The whole history of the tab be retained after unstashing it.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Tab Stash has never stored the navigation history of a tab; it's unfortunately not possible to store this information as part of a bookmark.

You were seeing the navigation history before because by default, Tab Stash tries to keep saved tabs open as hidden tabs inside your browser. If you restore a tab with a matching URL, Tab Stash can then simply un-hide that tab if it still exists (thus restoring the navigation history and state of the tab).

However, these hidden tabs can be lost if you close the window where they were opened, if you change your Firefox settings so that Firefox restarts without saving your session, or if you change Tab Stash's settings to close tabs instead of hiding them. In these cases, tabs will be restored without navigation history.

And of course, if you stash tabs on one computer and restore them on another, the history/state will not be there since it's not possible to move tabs between computers.

Hope this explains what you are seeing; let me know if you have any follow-up questions!

**Comment by waliddamouny** [comment]
Thanks for the clarification. It would've been great if actual navigation was preserved because that's what a session should be.
