### ISSUE TITLE
Switching Between Groups

### ISSUE THREAD

**Issue by moerloos** [josh-berry/tab-stash#303]
Sorry if I missed this... I have been using Tab Stash for a few weeks now, but I feel like the behavior changed. I checked the "What's New" page but didn't see anything about this. 

Assume I have two groups of stashed tabs: Group 1, Group 2. 
I have Group 1 tabs open. Now I want to work on Group 2, so I open those tabs. 

The expected behavior - and what I thought was happening when I first started using Tab Stash - is that Group 1 tabs are hidden and Group 2 tabs are opened. 

The actual behavior is that when I open Group 2, it adds to the existing tabs in the tab bar. So, rather than things being tidy, I now end up with a ton of tabs open. 

I checked the settings, but didn't see anything obvious. Am I missing something?

**Comment by josh-berry** [comment]
Nope, you're not missing anything—this is how Tab Stash has always worked. You can get this behavior with two clicks instead of one, though. Under "Unstashed Tabs" / "Open Tabs", there is a red "Close all open tabs" button (the X surrounded by a box). You can click that to close everything (note it won't touch your pinned tabs), and then open the group you want. It's not quite as convenient as single-click switching, but hopefully it helps!
