### ISSUE TITLE
Strange Tweet Title causing weird importing behavior

### ISSUE THREAD

**Issue by diego898** [josh-berry/tab-stash#306]
### System Details

- **OS Version:** : OSX 13.0
- **Browser Version:** Firefox 107.0
- **Tab Stash Version:** 2.11.1

### Describe the Bug

I used the "About Sync" addon to get a list of the tabs I have open on firefox mobile. I then processed this large JSON file with `jq` to just export the title and (sometimes multiple) urls. For example, a couple produced entries looks like this:

```
{
  "title": "Andreas Kirsch on Twitter: \"Come to the poster sessions at https://t.co/2gN6m0jRUh tomorrow and talk to us about \"Unpacking Information Bottlenecks\" by yours truly, @clarelyle & @yaringal from @OATML_Oxford 🎉🔥 PS: I ❤️ skeuomorphism, can you tell? 🥳 https://t.co/OFsbriMF9N\" / Twitter",
  "url": [
    "https://mobile.twitter.com/BlackHC/status/1336801356708012034"
  ]
}
{
  "title": "Cameras and Lenses – Bartosz Ciechanowski",
  "url": [
    "https://ciechanow.ski/cameras-and-lenses/",
    "https://news.ycombinator.com/item?id=25357315"
  ]
}
```

Entry # 2 works as you would expect - two urls are grabbed and archived. 

But Entry #1 does not. For some reason, I thought the importer would work with formatted text like JSON, but I see it does not. It processes the first entry to grab three final urls like:
- http://bayesiandeeplearning.org/
- https://t.co/OFsbriMF9N/
- https://mobile.twitter.com/BlackHC/status/1336801356708012034

The first two are part of the "title" field, which is strange that twitter does it titles like that...

The second url is invalid and gets stuck with a title in tabstash like "Importing". But note: if you remove the `\` from the url it is valid! 

There are several more cases like this with tweets.

### Expected Behavior

Either:
- everything in the title field is ignored (would require some knowledge of JSON, or a json importer, etc.
- all urls, even the ones in titles, are processed correctly.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for splitting this out into its own report.

The importer is really—and I mean _really_ dumb. It basically searches through whatever you give it for URLs and tries to extract them using a few heuristics to figure out where the URL starts and where it stops. It doesn't care about structure or format or anything else.

Its definition of what a URL is is also overly permissive, because I have seen people put all kinds of invalid characters into URLs and expect them to work, and a certain very popular vendor of office software is one of the worst offenders here (or at least, they used to be—I think they've gotten better in recent years).

In your particular case, as you rightly pointed out, the importer seems to be getting confused by the `\\` escaping the quote after the URL. So I'll make sure it knows that `\\` is not a valid character inside a URL and that should solve this case.

As a workaround in the meantime, if you want all the links in the titles as well as the tweets, you could try smashing them all together and un-escaping them; something like this should work (note the `-r` to emit the strings as raw data, not JSON strings):

```sh
jq -r '[.title, (.url|.[])]|join(" ")'
```

**Comment by josh-berry** [comment]
<img width="319" alt="Screenshot 2022-12-03 at 10 50 11" src="https://user-images.githubusercontent.com/1203893/205457045-0ac45c48-174f-4df0-bb08-d6e5386b2174.png">

Your example should work in the next release.
