### ISSUE TITLE
When accidentally stashing all tabs multiple times, Tab Stash pretends to create groups but simply closes tabs

### ISSUE THREAD

**Issue by alainsr** [josh-berry/tab-stash#31]
**Describe the bug**
When accidentally stashing all tabs, Tab Stash creates multiple groups, each containing multiple/all tabs, then hangs, then deletes all these groups. And the tabs are also gone: not stashed, not bookmarked. :-(

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Have 50+ tabs open.
2. Right click a tab.
3. Click "Stash tabs" thinking you're stashing that one tab only.
4. Do it two more times.
5. Watch Tab Stash hang with 3 new groups, each filled with all your (non-pinned) open tabs.
6. Wait.
7. Watch Tab Stash come back with no new groups at all, and all your tabs gone at the same time.
8. Look for the tabs in Bookmarks.
9. Don't find the closed tabs nowhere.
10. Use ctrl+shift+T to reopen closed tabs.
11. Find out your number of remembered closed tabs is much smaller (20) than the number of tabs you had open.
12. Cry.
13. Stop crying and file this bug, hoping for the developer to point you to a dump file somewhere that could have your lost tabs' URLs.

**Expected behavior**
Stash properly all tabs. Or not, but then don't close them.

**Desktop (please complete the following information):**
 - OS: Windows 81 64 bit
 - Firefox Browser Version: 68.0.1 64 bits.

**Comment by josh-berry** [comment]
Sorry to hear that Tab Stash made you cry! :( That is unexpected behavior indeed, and I will look into it as soon as I can. The only thing I can think of off the top of my head is that somehow the logic which deals with duplicates while stashing is causing problems.

Regarding your lost tabs/bookmarks, have you checked your browser's history? You can access it by going to the Firefox menu > Library > History, and choosing "Show All History" at the bottom. This will obviously have a lot more than just your lost tabs, but hopefully it will help you find the pages you were actually interested in saving.

**Comment by alainsr** [comment]
The thing is that long-time-open tabs were not in recent history, because they weren't opened recently, so they are scattered throughout months of intensive research-related tab opening and closing: how to identify which URLs were still open up to yesterday? There is no way, right? So Tab Stash really harmed me this time, instead of doing exactly the opposite, which was the expected...

**Comment by alainsr** [comment]
> the logic which deals with duplicates while stashing is causing problems
Does it dump logs somewhere? Couldn't they have my tabs' URLs stored in them?!?

**Comment by josh-berry** [comment]
Sadly no, it doesn't dump logs because there is no way/place for extension to store logs in any kind of persistent way (at least, not without asking for scary/unnecessary permissions).

If you aren't able to find everything you need in the browser history, you can also check the backups Firefox makes of your bookmarks periodically. Those can be found in "Firefox Menu > Library > Bookmarks > Show All Bookmarks". The right-most menu (with the arrows) has "Backup" and "Restore" options.

**If you are technically-inclined** and don't want to do a full bookmark restore, the backup files themselves are stored as compressed JSON (`.jsonlz4`) files in `bookmarkbackups` in your Firefox profile directory—you may be able to get the URLs out of those. However, you will need a tool which can decompress mozlz4 files. **I have not used this tool,** but this one seems like the easiest to get running of the ones I was able to find: https://addons.mozilla.org/en-US/firefox/addon/mozlz4-edit/

Hope this helps, and sorry again for the trouble!

**Comment by josh-berry** [comment]
(Feel free to ignore this; this is my brain dump.)

## Technical Analysis

So here's what I think is happening (simplified to ignore the tab-management aspects among other things):

1. User clicks the "Stash all tabs" toolbar button. This spawns an async function `bookmarkTabs()` which:
   a. Creates an empty folder for the new stash
   b. Populates the stash with bookmarks for each tab (oversimplifying, but close enough)
   c. This calls `gcDuplicateBookmarks()` (technically async, but doesn't matter here). We tell it to ignore the folder we just created in step a, and clean up duplicates for any URLs created in step (b).
   d. `gcDup...()` queries the bookmarks engine for the entire Tab Stash bookmark subtree
   e. It walks all candidate folders (excluding explicitly-named folders and folders it was told to ignore), and issues deletion requests for bookmarks with duplicate URLs.
   f. If it deleted all the bookmarks in a folder, it issues a deletion request for that folder as well.
2. User clicks "Stash all tabs" again. The process above repeats.

Suppose step 2 happens before step 1 is completed. In fact, let's assume they happen at almost exactly the same time (so there are two async `bookmarkTabs()` functions running). If both instances of `bookmarkTabs()` make it to step (d) at the same time, you could hit this issue.

This happens because both instances of step (d) see the same bookmark tree, with two folders containing the same set of tabs, except that each instance is told to ignore a different folder. So, both instances clean up the *other* folder (the one they were not told to ignore), blissfully unaware that this results in *both* sets of bookmarks being deleted.

## Possible Next Steps

I don't think there is a way to serialize everything because the above two instances could be happening in *separate browsers* which can't communicate with each other except through Sync (which wasn't intended for this type of serialization; it's not an actual communication pathway). So we have no way to know if multiple sets of overlapping tabs are being synced concurrently.

Not sure if any/which of these will work or will be the best option; will have to think on it more:
1. Disable the duplicate-cleanup logic entirely. This isn't great since it's removing a feature, but it's probably not a big deal, and is guaranteed to work.
2. Squish the duplicate logic in to the bookmark-creation logic; look for duplicates BEFORE we create new bookmarks and just move the old bookmarks into the new location (if they exist). Not sure what to do about empty folders though. I've also seen problems with multiple bookmarks getting moved concurrently, so I'm not sure if this will actually work (or just create different bugs).
3. Leave the duplicate logic largely as-is, but move everything to a Trash location instead of deleting it, so there is at least a way to recover from this. Then cleanup the Trash location in the background after a while (after days, after a browser restart, or something). I'm less inclined to go with this option because it's still not a great experience to have stuff go missing that you didn't intend (and nobody likes digging around in the trash).

**Comment by alainsr** [comment]
Idea:
4. Make any stash only happen when the previous has completed.

**Comment by josh-berry** [comment]
@alainsr I thought of that too, but one concern I has is if a bookmarks sync happens while we are stashing in two different browsers at once, we might still hit the same problem. (Firefox triggers sync very aggressively, so this is more likely to happen than you might think.) We have no way to know if we are stashing in two different browsers at once, or even if a sync is happening, because Firefox doesn't give extensions any visibility/control over sync.

One other thought I had is providing a way for a user to trigger this duplicate cleanup manually instead of doing it automatically. A user is likely never going to trigger cleanup on two computers at once, so this might help reduce the risk even further.

(This is still priority 1 for me for Tab Stash, BTW—I've been busy with life and a new job and haven't had a chance to work on this yet. Apologies for the delay. :/)

**Comment by alainsr** [comment]
(No problem. Life happens... ;-) )

**Comment by josh-berry** [comment]
I have removed the offending de-duplication code for the upcoming Tab Stash 2.5 release, so this will not happen again once 2.5 is out. I still don't have a solution that keeps the de-duplication feature intact, but I've made a note for myself to revisit for a future release.

Sorry for the trouble, and thanks for taking the time to report the bug!

**Comment by 13631368** [comment]
> **Describe the bug** When accidentally stashing all tabs, Tab Stash creates multiple groups, each containing multiple/all tabs, then hangs, then deletes all these groups. And the tabs are also gone: not stashed, not bookmarked. :-(
> 
> **To Reproduce** Detailed steps to reproduce the behavior:
> 
>     1. Have 50+ tabs open.
> 
>     2. Right click a tab.
> 
>     3. Click "Stash tabs" thinking you're stashing that one tab only.
> 
>     4. Do it two more times.
> 
>     5. Watch Tab Stash hang with 3 new groups, each filled with all your (non-pinned) open tabs.
> 
>     6. Wait.
> 
>     7. Watch Tab Stash come back with no new groups at all, and all your tabs gone at the same time.
> 
>     8. Look for the tabs in Bookmarks.
> 
>     9. Don't find the closed tabs nowhere.
> 
>     10. Use ctrl+shift+T to reopen closed tabs.
> 
>     11. Find out your number of remembered closed tabs is much smaller (20) than the number of tabs you had open.
> 
>     12. Cry.
> 
>     13. Stop crying and file this bug, hoping for the developer to point you to a dump file somewhere that could have your lost tabs' URLs.
> 
> 
> **Expected behavior** Stash properly all tabs. Or not, but then don't close them.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 81 64 bit
> 
>     * Firefox Browser Version: 68.0.1 64 bits.
