### ISSUE TITLE
[FEAT] Setting to not open a new tab when closing last tab

### ISSUE THREAD

**Issue by MrNossiom** [josh-berry/tab-stash#311]
Hi there 👋🏻,
First, I have been using `Tab Stash` for a few years now, and I love it. Thanks to all for the work you did.

### Problem Statement

I usually try to keep my tabs pretty clean, and I often close them all when I've done a task or a specific thing. I like to have tab stash pinned to get a quick look at my lists when I have done something. When I stash the last tab, even though I have the pinned Tab Stash page open, the extension opens a new page. Although I understand that some like this behaviour, from my point of view, I find it annoying.

### Preferred Solution(s)

I do not develop extension and don't know what are considered good practices.
If the last tabs that remains is a pinned (or not) Tab Stash one, do not create a new tab, but focus the Tab Stash.
To avoid breaking actual user experiences, it could be under a setting flag.

### Alternative Solution(s)

I will add maybe an alternative solution in the future, but I don't have one I mind right now.

Thank you for any following answers, I am at your disposal 😉.

---
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but “Me too!” comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the feature request! I'm also glad to hear Tab Stash is working well for you, thanks for sharing!

Unfortunately, this behavior is something that's controlled entirely by Firefox; Tab Stash isn't involved at all.

What's happening is: when you stash a tab, Tab Stash tells Firefox to hide it instead of closing it, so the tab is still open but not visible in your tab bar. Then, when you close the last open tab in a window, Firefox realizes "wait, there are no open, visible tabs anymore" and it picks a tab from your hidden tabs to show you instead. I agree it's annoying and I wish there were something I could do to change it, but by the time Firefox tells Tab Stash "hey, this tab was closed", it's already too late—Firefox has un-hidden the next tab already.

There is a workaround for this, though—in the Tab Stash options, you can tell Tab Stash to "Close the tab immediately" when you stash it. Closing a tab means you'll lose whatever state, navigation history, etc. you had in that tab, but it won't spontaneously reappear later.

Hope this helps, let me know if you have any more questions!
