### ISSUE TITLE
Option for confirmation before deleting group

### ISSUE THREAD

**Issue by cognitiaclaeves** [josh-berry/tab-stash#317]
### Problem Statement

I'm autistic, with ADHD. Variable executive function leads to general distrust in myself.

Having a button that will delete a tab group without confirmation gives me an uneasy feeling. While there is a popup that pops up after the group is deleted, I don't trust myself not to panic the moment I realize a group of many tabs has been deleted and do something that dismisses the pop-up. I also was unable to figure out how to restore a deleted group, though I think I saw something about data being kept for a while after deletion.

The fact that the icon matches exactly a much less destructive option under 'Unstashed Tabs' compounds my sense of unease. (Though, to be fair, do find it to be a potentially destructive action to close, rather than hide, the tabs.) When mousing over the icons, they are even the same color. There is nothing, visually, to clue me in that one could be a lot more destructive of an operation than the other.

### Preferred Solution(s)

I'd like an option to confirm the deletion of the group.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Data is indeed kept for a while after deletion; you can access the deleted items from the Tab Stash menu next to its search bar. The "Undo" popup you see is nothing more than a way to quickly restore something you just deleted from the deleted items.

<img width="189" alt="Screenshot 2023-01-16 at 20 47 58" src="https://user-images.githubusercontent.com/1203893/212812354-f84566b5-4f5d-4291-b4df-e7be8cfed672.png">

So even if you delete something by mistake and only realize it a day (or a week, or a month) later, it should still be there in Tab Stash's deleted items. Note, however, that deleted items are not synced between computers, so you will have to restore the item on the computer you deleted it from.

(And yes, the retention time is configurable—it's 180 days by default, but if you're uncomfortable with that number, you can change it in the options.)

In general, I prefer to have an undo history of destructive operations rather than a confirmation, because a confirmation is an interruption, and it's only useful up until the moment you click that "Confirm" button. I've mindlessly clicked through confirmations and then regretted it more times than I'd care to admit. ;)

Hope this puts your mind at ease, let me know if you have any follow-up questions!

**Comment by asdrubale88** [comment]
I think this could easily be linked to #310, [see my comment](https://github.com/josh-berry/tab-stash/issues/310#issuecomment-1406713708).

**Comment by josh-berry** [comment]
As part of some other feature work I was doing, the "Delete Group" option is now hidden inside a menu, and it will be much harder to click it unintentionally. (And, even if you do, remember that deleted items are still available in case you delete something by mistake!)

This change will be available in the next release; hope it helps!
