### ISSUE TITLE
Performance with large numbers of tabs?

### ISSUE THREAD

**Issue by fencepost** [josh-berry/tab-stash#33]
Does tab-stash do anything that may not scale well with large numbers of windows and tabs open? Possibly something that might trigger a sync every time a tab is opened or closed? 

I have more than 50 windows with a total of more than 1200 tabs (clearly tab-stash performance isn't my only problem), but I was hoping to use it to be able to reduce the number of things open and be able to clear them out from any of several systems. Unfortunately, once I activated it performance ground to a halt any time tab operations happened (e.g. moving to a different tab that needed to reload taking minutes). Disabling tab-stash has returned to decent performance.

Monitoring with Resource Monitor while this was happening showed no obvious issues with CPU, memory or disk/disk queue.

My initial thought was that if syncs weren't as granular as they could be then this might be triggering a full sync every time a tab was opened or closed, possibly then causing a partial hang during the sync.

This is on Windows, x64, FF 68.0.1

**Comment by josh-berry** [comment]
No, there is nothing in Tab Stash that should be causing Firefox to sync more often that I'm aware of. Firefox will sync automatically in response to bookmark and tab changes, but we only make such changes in response to an explicit user action (such as stashing/deleting/etc.), or as part of various cleanups (which are themselves triggered in response to bookmark changes, or only once every 2 minutes by default).

**Question:** When you see the problem, do you have the Tab Stash sidebar or tab view open? If so, does the problem get better/go away when you close the sidebar/tab?

The only place where Tab Stash monitors tab events is in the UI itself. If closing the UI helps, that at least points in one possible direction.

Also, if you have many instances of the UI open (e.g. you have the sidebar open in every single window), this could contribute as well, since each instance of the UI has to monitor for changes separately.

**Comment by josh-berry** [comment]
I'm going to go ahead and close this issue since it hasn't seen any activity in a while, but if you continue to see this problem, please feel free to re-open (or open a new one and mention this issue number in the new one).
