### ISSUE TITLE
Using Tab Stash As New Tab Page.

### ISSUE THREAD

**Issue by Dennismn** [josh-berry/tab-stash#356]
Hi, I already have Tab Stash as my default HOMEPAGE so it only loads automatically when I initially open FF, however it doesn't load when I try to make it my default NEW TAB page. 

When I make a new tab it just shows me the default FF new tab blank google search page. So, I have to navigate to Home to get it to show up every time.

I tried using another addon called New Tab Override to make it my new tab page, but it doesn't support local hosts.

I appreciate the addon and it's useful, so, thanks for making it. 

System Details:

Firefox 112.0.1 on a M1 Mac.
Tab Stash Version: 2.12.0.1

**Comment by josh-berry** [comment]
Sorry for the delayed response! Yeah, unfortunately, Firefox for whatever reason doesn't allow you to set an arbitrary URL as your new tab page, and the facilities they give to extension developers to do this kinda assume that the whole point of your addon *is* a new tab page (which is not the case for Tab Stash).

It's not something I've enabled for Tab Stash because I don't want it to completely take over your browser. But it's something others have asked for—here's the feature request, feel free to watch there for updates:

* #93

I'll go ahead and mark this as a duplicate, but I hope this at least explains things!
