### ISSUE TITLE
selecting multiple tabs in the tabstash sidebar

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [josh-berry/tab-stash#360]
hello, it is not possible to select multiple tabs from the "Open Tabs" menu and drag them into an existing group. Instead the tab is opened. 

Expected behavior: 

- Click on  a button "multi-select mode"
- I can now hold shift or ctrl to select multiple tabs in the list.
- I can drag them into a collapsed group by releasing the tabs on top of the title.

Right now I can click and drag only one tab, and drag it into a group only when the group is not collapsed.

**This makes organizing larger numbers of tabs impractical.** 

I have yet to see a bookmarks / tab organizing software that really solves all problems.

I remember using tab group helper back in the day. then switched to onetab after firefox update broke many good old extensions. 

Tab Stash has great potential and I hope this will be the all in one solution.

**Comment by josh-berry** [comment]
Hi, I'm not sure if I follow what you're asking here—it is possible to drag multiple tabs together into a group by selecting and dragging any of the selected tabs. When dragging, all of the selected tabs will move into the group.

If you're seeing a new tab open because of a drag-and-drop operation, please make sure you don't have an incompatible extension installed, as certain extensions are known to interact badly with Tab Stash (one of which may cause the drag-and-drop behavior you describe): https://github.com/josh-berry/tab-stash/wiki/Known-Incompatibilities-with-Other-Extensions

It's true that you cannot drag tabs into a collapsed group today, and I'd be happy to consider this as a feature request.  Hope this helps, and let me know if I've answered your question!

**Comment by josh-berry** [comment]
Ah, I see. To select a tab, you need to click on its icon, not on the tab title. This will turn the tab blue to show that it's selected.

Hope this helps!
