### ISSUE TITLE
[request] Stash tabs from a window when said window is closed

### ISSUE THREAD

**Issue by AeliusSaionji** [josh-berry/tab-stash#370]
### Problem Statement

I have a problem with firefox's relationship to sessions. Closing a window can have two different outcomes:
- all tabs in that window are closed
- the session is saved and the process exits

Predicting the behavior requires the user to vigilantly pay attention to the number of open windows. I'm hoping tab-stash will be able to give the end user one outcome in all contexts.

### Preferred Solution(s)

Provided the following conditions are met:
- There are multiple firefox windows
- The user closes a firefox window containing more than one tab
  - potentially not including Firefox View, settings pages, etc

Tab Stash should stash all the tabs that were in that closed window.
If the user wants to discard the tabs in a window, they would close all tabs by some other means.
Tab Stash will not attempt to stash tabs when the user closes the last window, because firefox can (per user settings) use its own session logic to cover the tabs in that window.

### Additional Context

I have read a number of other feature requests regarding "autosave / session replacement" and I believe this stands distinct, because it is not hammering the firefox bookmarks engine with frequent changes and is not intended to be a safety mechanism against crashes.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the feature request! To be honest, this is probably something best-addressed in the browser itself, or as its own dedicated extension. Unfortunately, this:

>  If the user wants to discard the tabs in a window, they would close all tabs by some other means.

isn't possible in a user-friendly way. While it would be possible to implement a special "close without stashing" option in Tab Stash itself, I think that changing how core browser functionality works (i.e. behavior of "close"), and then forcing people to use the Tab Stash UI to close things they don't want to save, would be very confusing and surprising.

Also, one of the core conceits of Tab Stash is that stashing is an intentional act—I find that "automatic saving" features often create clutter and disorganization that is hard to clean up later.

I think the best ways to achieve this would be to either make use of the "recently-closed" feature in Firefox (which remembers the last few recently-closed windows and tabs), or implement it as a dedicated extension. As a dedicated extension, it could have its own separate "close this window without saving" and/or "close this tab without saving" button in the toolbar.

But unfortunately, I'm sorry to say that I think any implementation of this in Tab Stash would not be a good user experience.
