### ISSUE TITLE
Questions before adding 

### ISSUE THREAD

**Issue by TeaganXXX** [josh-berry/tab-stash#376]
### Question

So, I'd like to know a few things before trying this Add-on.  

**1.)**  Just so I understand, and I don't experience another catastrophe I experienced with another add-on.  If I have, let's say 200+ tabs open, using Tabs Stash allows me to save (or stash) those 200+ open tabs to 'its' bookmark file, and/or to the Firefox default Bookmark Folder and/or Sidebar? 

**2.)**  One of my add-ons is _Tab Session Manager_.  Will Tab Stash conflict or interfere with the add-on _Tab Session Manager_ I am using?
 
**3.)**  Will Tab Stash move, remove, delete or interfere with any of my present bookmarks I have saved in the Firefox default Bookmark Folder or Sidebar?
 
**4.)**  Will Tab Stash move, remove, delete or interfere with any of my present bookmarks I have saved in the Firefox default Bookmark Folder or Sidebar if I decide to remove it (Tab Stash) from my Add-ons?
 
**5.)**  Is it my understanding, that there is an option that allows me to export (or save) the Tab Stash bookmarks to my Firefox default Bookmark Folder and/or Sidebar without loosing, deleting or interfere with any of my present bookmarks saved in the default Firefox Bookmark Folder or Sidebar?

### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Comment by josh-berry** [comment]
> **1.)** Just so I understand, and I don't experience another catastrophe I experienced with another add-on. If I have, let's say 200+ tabs open, using Tabs Stash allows me to save (or stash) those 200+ open tabs to 'its' bookmark file, and/or to the Firefox default Bookmark Folder and/or Sidebar?

Tab Stash will create a separate folder named "Tab Stash" under "Other Bookmarks" and create folders and bookmarks under this folder for storing your stashes. You can learn more about how the "Tab Stash" folder works by reading [this wiki page](https://github.com/josh-berry/tab-stash/wiki/Problems-Locating-the-Tab-Stash-Bookmark-Folder).

> **2.)** One of my add-ons is _Tab Session Manager_. Will Tab Stash conflict or interfere with the add-on _Tab Session Manager_ I am using?

I'm not familiar with this add-on, but since it's not in the [list of incompatible add-ons](https://github.com/josh-berry/tab-stash/wiki/Known-Incompatibilities-with-Other-Extensions), that means nobody has reported a problem or conflict with it.

From a cursory glance, the only thing I can think of that might cause issues is the fact that Tab Stash will keep stashed tabs open but hidden in the background—if Tab Session Manager doesn't understand Firefox's hidden-tab feature, this may cause problems. You can change a setting in Tab Stash's options, though, so that Tab Stash closes instead of hides stashed tabs.

Afraid I can't give you a firm "yes" or "no" here, though, since I can't test Tab Stash with every possible extension.

> **3.)** Will Tab Stash move, remove, delete or interfere with any of my present bookmarks I have saved in the Firefox default Bookmark Folder or Sidebar?

No. (If it does, that would be considered a serious bug.)

> **4.)** Will Tab Stash move, remove, delete or interfere with any of my present bookmarks I have saved in the Firefox default Bookmark Folder or Sidebar if I decide to remove it (Tab Stash) from my Add-ons?

No. In fact, you can remove Tab Stash and keep all the bookmarks saved under "Tab Stash", so even if you decide to stop using Tab Stash entirely, you have not lost your saved tabs. 

> **5.)** Is it my understanding, that there is an option that allows me to export (or save) the Tab Stash bookmarks to my Firefox default Bookmark Folder and/or Sidebar without loosing, deleting or interfere with any of my present bookmarks saved in the default Firefox Bookmark Folder or Sidebar?

You can simply move (or copy) bookmarks around using Firefox's built-in bookmark editor, and Tab Stash will notice and adapt to the changes. You do not need to use the Tab Stash UI (even while Tab Stash is installed) to manage Tab Stash's bookmarks if you don't want to.

This is intentionally supported to allow Tab Stash to play nicely with other bookmark add-ons (e.g. add-ons that delete duplicates etc.).

Hope this helps, let me know if you have any follow-up questions!
