### ISSUE TITLE
"Open All Tabs & Delete Group" Fails When Tab Stash is Home Page

### ISSUE THREAD

**Issue by riyfu** [josh-berry/tab-stash#377]
### System Details

- **OS Version:** Fedora 37
- **Browser Version:** Firefox 115.0.2 (Mozilla Flatpak)
- **Tab Stash Version:** 2.12.1

**Installed Browser Extensions:**

- None (tested on new profile)

### Describe the Bug

When Tab Stash is set as the home page, the "Open all tabs in the group and delete the group (hold Ctrl to open in background)" button does not delete groups when pressed from the stashed tabs page. All tabs open but the group is not deleted.

If Ctrl is held, groups are deleted as expected.

### Steps to Reproduce

1. Follow "Make Tab Stash Your Homepage" at https://josh-berry.github.io/tab-stash/tips.html 
2. Click "Home" toolbar button to navigate to stashed tabs page
3. Click "Open all tabs in the group and delete the group (hold Ctrl to open in background)" button over a group
4. See group tabs open and stashed tabs page close
5. Click "Home" toolbar button to navigate back to stashed tabs page
6. See group has not been deleted

### Expected Behavior

Group is deleted.

### Additional Details

The stashed tabs page stays open if Tab Stash is not set as the home page and closes if it is. Seems likely this is the cause.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for the bug report! This happens because Tab Stash thinks the active tab (i.e. Tab Stash itself) is a "blank" tab (since it's set as the homepage), and so closes the active tab (i.e. closes itself). Unfortunately, this was happening before the bookmarks could be cleaned up, so that's why your stash was still sticking around.

I've pushed a fix that will make sure the bookmarks get deleted before the active "blank" tab is closed, so this should make sure groups get deleted properly. It will be in the next feature release. If you're finding this behavior to be super annoying, do let me know and I'll consider it for a bugfix release.
