### ISSUE TITLE
Tab Stash makes Firefox freeze on new window open

### ISSUE THREAD

**Issue by junkblocker** [josh-berry/tab-stash#39]
**Describe the bug**
If I have Tab Stash as the selected sidebar and I open a new window with Cmd+N on macOS, Firefox freezes for quite a long time (around a minute or so) before becoming usable.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Make sure Tab Stash is open in the sidebar.
2. File Menu > Open New Window
3. Try to type something in the new window address bar. Notice how your input lags for multiple seconds and sometimes almost a minute.
4. Repeat the same with a different sidebar like Bookmarks open and notice how there is instant responsiveness.

**Expected behavior**
There should be no freezing of the Firefox UI. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2
 - Firefox Browser Version: 71.0

**Additional context**

**Comment by junkblocker** [comment]
The problem may not be limited to new window opening only but may be due to first render of the tab stash sidebar. This can be seen by switching sidebar panel away from and back to tab stash.

More details - I have 34 groups and 797 tabs in those per tab stash.

**Comment by josh-berry** [comment]
Sorry to hear you're having trouble, and thanks for the numbers—that's useful information. I'm very surprised to hear that Tab Stash is blocking the rest of the Firefox UI; Firefox itself is designed so that should never happen.

Certainly the larger your stash, the longer it takes to load the sidebar, but I tried with approximately 220 groups and 1,700 tabs in my stash just now, and haven't been able to reproduce the issue of the entire Firefox UI freezing while the sidebar loads (even on my 2018 MacBook Air, which is optimized for battery life and not much else). I was able to type in the address bar, scroll through the new-tab page, etc. while the sidebar was loading. Tab Stash itself takes several seconds to load, but nothing like a minute.

The fact that Firefox itself is freezing makes me think there is more going on on your system—outside of Tab Stash itself, either in your browser or the OS. Because Tab Stash tries to load the entire stash during startup, this can be somewhat demanding of the browser and your computer's storage (if the browser has to load bookmarks from its database). Anything that's causing a slow-down in that path might have a disproportionately large impact on Tab Stash.

A few more questions:

* How many browser windows and tabs did you have *open* (not stashed) at the time?
* What other things are running on your system? I see you're a dev, so I'm assuming you've already checked Activity Monitor etc. to ensure the system itself isn't overloaded.
* Can you tell me more about your Mac's hardware? What model is it, what is the CPU/RAM? What kind of storage do you have (I assume it's flash/SSD)?

**Comment by junkblocker** [comment]
Hmmm, I closed everything else and relaunched it but the problem has gone away.

1. I had one Firefox window open with 23 tabs, 12 were visible and 11 were hidden.
2. I had a bunch of other things running but there was ample free disk space and nothing else was using CPU either. I had run top and noticed that whenever I would open the new window, firefox would just to take 100% CPU and stay there til the problem went away. `about:performance` was useless too until Firefox started responding again. I did not check Activity Monitor.
3. 
```
OS:   darwin18.2.0 Mac OS X 10.15.2 (Build 19C57)
CPUs: 6 physical/12 logical
Mach: x86_64
Arch: MacBookPro15,1
RAM:  16 GB
```

So, I'll just wait and watch for a bit more but seems like it could be closed soon.

**Comment by josh-berry** [comment]
Sounds like a plan. You definitely shouldn't be seeing performance problems on that system with only 23 tabs open, so hopefully restarting Firefox fixed it.

**Comment by junkblocker** [comment]
It feels like there's still a bit of freeze if all or almost all groups are folded while it is folding them.

**Comment by junkblocker** [comment]
I think it's behaving fine. I'll reopen if needed.
