### ISSUE TITLE
Auto-Stash on App Close

### ISSUE THREAD

**Issue by nao9797** [josh-berry/tab-stash#392]
Hi I'd like to suggest a feature that can be Enabled/Disabled from the Add on's Options Menu that would 
Stash all Tabs when the Browser is Closed 

This is extremely useful for people like myself who might experience power outages often and or unexpected closing of the browser. Just as Firefox already has this option and does this natively, I thought Tab Stash would provide a much better interface. 
It would be helpful if these were titled "Auto-Stashed from Browser Closing" Or something similar (maybe a short name)
Even without the scenario where the browser is closed unexpectedly, I would enable this option because then I can comfortably close my browser with its tens of tabs open in a hurry, without worrying about what I am closing and then when I reopen the browser, I can more easily go through the tabs and organize them. I appreciate the time taken to read this and considerations to add this in advance! Thank you!

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately, you really are better-off relying on Firefox's built-in feature for saving and restoring sessions in this case. The built-in version is implemented in a more reliable way than what can be done in any extension.

The reason is, Firefox doesn't wait for extensions to finish what they are doing before it shuts down, and there is no way to guarantee that stashing is complete before the browser closes.

And in the case of a power outage or unexpected crash, again, Firefox itself can do a better job here because it has total control over how it keeps track of what you have open (and the Firefox developers have put a lot of work into making this work well over the years). To do something similar, Tab Stash would have to be auto-saving your tabs _all the time_, not just at browser close. (And there are other issues with auto-saving—see #224.)

Sorry have to tell you this isn't possible, but I hope this makes sense. Thanks for taking the time to reach out!

**Comment by nao9797** [comment]
thank you for taking the time to reply, i do understand with your explanation and its too bad it isn't possible. In any case thanks for all your work thus far on tab stash! It's been very useful to me! have a great day , cheers!

**Comment by josh-berry** [comment]
Thanks, I'm really happy to hear it's been helpful!
