### ISSUE TITLE
What causes a stashed tab to be duplicated as an unstashed tab?

### ISSUE THREAD

**Issue by edsnowden** [josh-berry/tab-stash#394]
### Question

I have lots of tabs and I just wanted a way to group them. I came across Tab Stash a couple of days ago and it seems to do that.

When I click a tab in a stash, it appears to become the active tab. However, sometimes when I navigate in that tab, the active tab appears to become a new entry in Unstashed Tabs (i.e. instead of the active tab indicator being the entry I clicked on, a new entry appears in Unstashed Tabs and that has the active tab indicator), and I have no mental model of why that happens.

Most likely it's a feature not a bug and I've just not understood what Tab Stash is really about (it's not called Tab Groups so I'm probably misusing it if all I want is grouping).

**Comment by josh-berry** [comment]
Hi, Tab Stash decides whether a tab is "stashed" or not based on its URL. So if you navigate away from a page (and the URL changes), it will start to show as unstashed. And if you navigate back to the URL that's saved in the stash, the tab will appear as stashed once again.

The main distinction between Tab Stash and other tab grouping addons is the idea that putting something in your stash should be an intentional action, rather than something that happens automatically. I've often found that it's easy to lose things or get groups into a disorganized state if the group strictly tracks the open tab, and so I wanted something that was "in between" tab grouping and more traditional features like bookmarks.

Hope this helps!
