### ISSUE TITLE
If I close all tabs a stashed tab opens

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#40]
**Describe the bug**
If I close all tabs a stashed tab opens, instead of the browser closing.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Stash everything
2. Open a few tabs
3. Close all tabs

**Expected behavior**
The browser should close

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Firefox Browser Version: 71.0 (64-bit)

**Additional info**
It is possible to delete a stashed tab by closing the one opened by the bug above, but I cannot get a reliable replication method.

**Comment by josh-berry** [comment]
Hi,

Unfortunately this behavior isn't controlled by Tab Stash, but by Firefox itself.

By default, Tab Stash uses Firefox's "Hidden Tabs" feature to keep your tabs open but hidden in the background. So when you close the last visible tab in your browser window, Firefox will restore a hidden tab, rather than closing the window (and all your hidden tabs along with it). This is so that if there's anything you were working on in one of those hidden tabs, you won't lose it.

If you don't want this behavior, you can tell Tab Stash to stop using the hidden-tabs feature entirely:

1. Right-click on the Tab Stash icon in your toolbar.
2. Choose "Manage Extension". The Firefox Add-ons Manager will open in a new tab.
3. Click "Options" underneath the Tab Stash name/icon.
4. Under "Once the tab has been stashed:" choose "Close the tab immediately".

The downside to this option is tabs may take longer to restore, and if you were working on anything in the stashed tab (e.g. writing a comment or blog post), it may be lost, since the tab is unloaded completely by the browser. But this will give you the behavior you're expecting.

Hope this helps!

**Comment by EmmanuelMess** [comment]
@josh-berry I saw that configuration and disabled it, the bug still occurs.

**Comment by josh-berry** [comment]
Hi,

Changing the option won't immediately close any hidden/stashed tabs, it only takes effect for new tabs that are stashed. After you changed the option, did you see the issue again in a new window, or were you using the same window as before?

You can tell if a window has hidden tabs in it by looking in the corner of the window. If you see a little icon like this:
<img width="130" alt="Screen Shot 2019-12-28 at 14 39 45" src="https://user-images.githubusercontent.com/1203893/71550227-e7841580-297f-11ea-91ad-6e7071f1016a.png">

Click it, and you'll see a menu like this:
<img width="349" alt="Screen Shot 2019-12-28 at 14 40 22" src="https://user-images.githubusercontent.com/1203893/71550229-fc60a900-297f-11ea-9e2c-43af6f1e9350.png">

If you see the "Hidden Tabs" menu item, that window still has hidden tabs in it, and you will still see the same behavior.

You can just close the window entirely to get rid of the hidden tabs, or you can tell Tab Stash to close any leftover hidden tabs it has saved in a particular window by opening the stash list, holding Alt (or Option on a Mac) and clicking the red ☒ icon in "Unstashed Tabs".

Give this a try and let me know if it solves your problem. :)

**Comment by EmmanuelMess** [comment]
> You can just close the window entirely to get rid of the hidden tabs

That doesn't seem to work.

> you can tell Tab Stash to close any leftover hidden tabs it has saved in a particular window by opening the stash list, holding Alt (or Option on a Mac) and clicking the red ☒ icon in "Unstashed Tabs".

That worked! Thanks!

**Comment by josh-berry** [comment]
Awesome, glad to hear it! If you do see this happen again even with that option selected, please reopen and let me know. :)
