### ISSUE TITLE
Double click on stash title to rename; single click to open/close

### ISSUE THREAD

**Issue by santinoscripts** [josh-berry/tab-stash#423]
Yep, there are arrows at the left, I know, but I find current behaviour of little to no use. How often do you need to rename a stash? How often do you open/close a stash?
So that's my request.
Thanks!

**Comment by josh-berry** [comment]
You're right that restoring is probably more common than rename. However, I think this would be pretty confusing for most users, since it's completely different from standard UI design conventions used by most other apps/extensions, which use single-click to edit.

There is also unfortunately no way to implement both single-click and double-click actions that do different things (because a single click is always triggered before a double click).

Thanks for the suggestion, though!
