### ISSUE TITLE
Pinned tabs

### ISSUE THREAD

**Issue by CConchelos** [josh-berry/tab-stash#43]
my pinned tabs will load in reverse order.

### Steps to Reproduce
create some pinned tabs, shut down and restart notice order change

### Expected Behavior
pinned tabs stay in order

### Desktop (please complete the following information):
Win 10
Firefox Nightly

I just snagged this addon yesterday, and it happened on the first restart. I thought it may be a first time config thing, so I re-arranged them. just opened FF and they are reversed again.

**Comment by josh-berry** [comment]
If I understand you correctly, it sounds like your pinned tabs are being rearranged when you shut down and restart Firefox itself?

If so, I can't think of any way this would be a Tab Stash issue--Tab Stash isn't involved in restoring tabs on a browser restart, nor does it touch your pinned tabs at all, since (presumably) you pinned them because you want to keep them open.

It sounds instead like maybe there is something wrong in the saved-session data Firefox itself maintains. I notice you are using Firefox Nightly--Nightly can at times be very unstable and prone to issues like this. Can you please try using a stable version of Firefox and see if that resolves your issue?

**Comment by CConchelos** [comment]
Like a fool I just restarted nightly and only 3 out of 8 pins came back. I have been using nightly for a very long time, but you're right, it could be. Your add-on I only just installed,and on the first restart it went wacky, and it's never happened before, so I assumed it was related to the change I made. I will keep an eye on it, and let you know if it's nightly related. As of yet, there doesn't seem to be anyone reporting about nightly's pins having issues.

**Comment by josh-berry** [comment]
Hi, have you been able to determine if this was an issue with Nightly?

**Comment by CConchelos** [comment]
Heya josh, 
The issue gas not popped up since. Thanks for the follow up. 
Chris

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 6, 2020 at 12:03 PM, Josh Berry<notifications@github.com> wrote:   
Hi, have you been able to determine if this was an issue with Nightly?

**Comment by josh-berry** [comment]
Glad to hear it, I'll go ahead and close this out then.
