### ISSUE TITLE
'Show Stashed Tabs in a New Tab' button not working?

### ISSUE THREAD

**Issue by SugarBooty** [josh-berry/tab-stash#44]
'Show Stashed Tabs in a New Tab' button not doing anything for me

The button to open stashed tabs in a new tab does nothing when I click it

 - OS: Windows
 - Firefox version: 72.0.1
 - Tab Stash version: 2.5

I am new to this, I'm sorry for any formatting mistakes

**Comment by SugarBooty** [comment]
The 'Open all tabs in this group' and 'Open all tabs in the group and delete the group' buttons in the sidebar are also not functioning for me, I need to right click and open in a new tab to open the individual links. The delete, create empty group and stash buttons all work correctly. Am I the only one with this issue?

**Comment by Tumble-Dryer-Lottery** [comment]
I'm experiencing exactly the same problems on:

Name 	Firefox
Version 	72.0.1
Build-ID 	20200107212822

OS: Windows 10 Home 1909 [Version 10.0.18363.535]

I've successfully installed and ran tab stash in another (test) profile. But I can't get it working in the standard-profile. So it may be some not granted rights or something else in the standard-profile's configuration?

**Comment by josh-berry** [comment]
Hi, sorry to hear you're both having trouble!

I've actually heard of this issue happening a couple times before. In the previous instance, it was because of a problem in Firefox's saved session state. Can you please try the following steps to see if it resolves the problem?

1. You will have to restart your browser in a way that causes it to forget any open tabs you might have, so first save off any open tabs you have that you might want to keep (you can stash them to Tab Stash, save them to bookmarks, or whatever is most convenient for you).
2. Open the Firefox menu and choose "Options" (or "Preferences" on Mac).
3. In the "General" section, turn off the "Restore previous session" option.
4. Completely shut down/exit your browser (make sure ALL open Firefox windows are closed and the application is not running). On Mac, you can do this by pressing the Command+Q shortcut. On Windows, open the Firefox menu and choose "Exit".
5. Restart Firefox.
6. Optionally, turn the "Restore previous session" option back on.

Let me know how it goes; if you're still having trouble, I'd like to get some debugging info to narrow things down and we can go from there.

**Comment by Tumble-Dryer-Lottery** [comment]
Hi Josh,

thank you for replying so quickly. Your suggestion worked for me! Thank you a lot, also for your great work on tab stash.

On a side-note also some other developer's extensions (unclose@dook and LoadOnTabSelect3) had some issues in my firefox-standard-profile and are now running smoothly again. I hope, I remember that trick, when I come across these problems again.

Kind Regards
Michael

**Comment by SugarBooty** [comment]
Thank you, this fix also worked for me. I appreciate the fast response and your willingness to help. May I recommend appending this fix to the readme in case anyone else has the same issue. Have a great day!

**Comment by josh-berry** [comment]
Hi Michael,

You're quite welcome, and I'm glad to hear it worked for you! Also glad to hear it fixed some other issues you were having. This seems to be the most common problem so far, so I should probably start a FAQ for it.

In any case, if you ever run into trouble with Tab Stash again, always feel free to open another issue.

Best,
Josh

**Comment by josh-berry** [comment]
@SugarBooty Glad to hear it! And I agree, I should start a FAQ, and have made a note to myself for this. (The README is getting quite large at this point, so would probably benefit from being split into separate pages.)

Have a great day, and always feel free to open another issue if you run into trouble again!
