### ISSUE TITLE
Add new tabs in the same group that previous tabs are a part of

### ISSUE THREAD

**Issue by SHolm3s** [josh-berry/tab-stash#440]
First of all, huge thanks for creating this, to all the contributors. It really saves a lot of time and multiplies productivity by order of magnitudes. Sincere thanks!!

### Problem Statement
I have a lot of tabs (around 1500 now and growing) which are organised into different groups (40 now). Each main group has different sub groups within them. I am posting a picture below:

![tab_stash](https://github.com/josh-berry/tab-stash/assets/88152029/cadfcd8c-24dd-4cb1-9609-70c0a289e41b)

The way I manage my work is that, I open each group in a separate window, so that tabs belonging to different groups are not mixing with each other. For example, to open tabs from the group called "Course Railway Noise", I right click on any tab underneath it, and choose "Open Link in New Window". In this way I can open multiple windows for each group I am researching on. Now the problem is addition of new tabs. When I add new tab in a window, I want that tab go automatically go under the group that window is used for. All the tabs in a particular window are part of the same group, so any new tab should also go under the same group. At present, all the new tabs are going into the unstashed section, and at the end of the day, I have to sort each link into the groups.

### Preferred Solution(s)
New tabs should go under the same group as other tabs in a particular window

### Alternative Solution(s)
I can't think of one. 

### Additional Context
I am sorry if someone else has already requested such a feature. I am coming from using the "Tabs Outliner" extension in Chrome before, which had this functionality. I also plan to make another feature request, where clicking on an already opened link in the tab stash brings the window in which that link was opened into the foreground focus, rather than opening the link in the current window. Again, this is to keep one window for one group, which is my method. In this way, all the groups are separate, and I can work on any number of groups simultaneously without losing structure.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the thoughtful writeup!

It's true that Tab Stash does not automatically save tabs, and this is an intentional choice—the idea being that things in your stash are exactly those things you have explicitly chosen to put there. I've found (in using other tab-grouping extensions/features) that this helps a lot with organization and eliminating clutter in your stash over time. It also makes it harder to lose things e.g. if you unintentionally navigate away from the page you're interested in.

Also, to this point:

> I also plan to make another feature request, where clicking on an already opened link in the tab stash brings the window in which that link was opened into the foreground focus, rather than opening the link in the current window.

Someone's already filed #375, so feel free to subscribe to that issue for updates!

I think #224 probably mostly-covers what you're looking for on this issue (at least to the extent possible without overloading Firefox's bookmark engine), so I'll mark it as a duplicate, but thanks for sharing your thoughts!

**Comment by SHolm3s** [comment]
Hi! Thanks for the comment. Even as I was writing, I felt that it must be intentional that there is no auto save tabs thing. I understand. It does make it more intentional and actively helps to reduce the number of saved tabs.  Thanks for taking the time to respond to my request! When #375 is implemented, this will be pretty much prefect for me! Thanks a lot!
