### ISSUE TITLE
"Close Stashed Tabs" keeps tabs opened, but hidden

### ISSUE THREAD

**Issue by Lgmrszd** [josh-berry/tab-stash#442]
### System Details

- **OS Version:** NixOS Unstable
- **Browser Version:** Firefox 121.0
- **Tab Stash Version:** 3.0

### Describe the Bug

When stashing tabs and then selecting "Close Stashed Tabs" in Stash context menu, the tab is hidden (is not displayed), but is still active and can be accessed through drop-down menu on the right -> "Hidden Tabs"

### Steps to Reproduce

1. Open a new tab go to any website (youtube or any other media playing tab is preferred to display the issue)
2. Stash the tab into a new group. The tab is hidden but is still opened in the background, I assume this is correct behavior.
3. Open the tab from the stash. The resulting layout is shown on the screenshot:
![image](https://github.com/josh-berry/tab-stash/assets/16291541/0cf1e9d0-e3f9-41b9-9aeb-34a1e3dafc77)
4. Open Stash context menu and select "Close Stashed Tabs". Result can be seen on the screenshot below. While the tab is visually closed, it's actually just hidden. If there's any media playing, it will keep playing. It can be seen in "Hidden Tabs" menu (second screenshot below)
![image](https://github.com/josh-berry/tab-stash/assets/16291541/038aee1d-020b-4d81-bb16-63e68c580f1b)
![image](https://github.com/josh-berry/tab-stash/assets/16291541/29581033-6754-4179-ab5f-d948b2cc5ee2)

### Expected Behavior

Closing stashed tabs should actually close them.

### Impact

This affects me and other Tab Stash users because the name of the option is misleading. When I close the tabs, I expect them to be actually closed, without any background processes occupying system resources. Either it should be renamed to "Hide Stashed Tabs", or it should actually close them, or there should be two options for hiding and closing.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
> When stashing tabs and then selecting "Close Stashed Tabs" in Stash context menu, the tab is hidden (is not displayed), but is still active and can be accessed through drop-down menu on the right -> "Hidden Tabs"

This is expected and intentional—by default, Tab Stash tries to keep things in the stash open but hidden, so they can easily be restored and any tab state is preserved. By default, it also manages system resources and the number of loaded, hidden tabs so you should not have to worry about their presence at all.

You can configure this in the options:

<img width="500" alt="Screenshot 2024-01-21 at 11 32 51" src="https://github.com/josh-berry/tab-stash/assets/1203893/69eb26d5-46d6-4199-a335-5019a00cb925">

If you want stashed tabs to actually be closed entirely, change this option to "Close the tab immediately".

> This affects me and other Tab Stash users because the name of the option is misleading. When I close the tabs, I expect them to be actually closed, without any background processes occupying system resources.

Note that just because a tab appears in the Firefox UI does not mean it is consuming system resources—keeping the "Automatically unload hidden tabs" option checked will ensure that stashed tabs that aren't used in a while are unloaded automatically. You can also choose the option to "Hide the tab and immediately unload it" if you want Tab Stash to immediately free memory associated with that tab (but still keep some of the tab state, which Firefox persists on disk as part of its session data).

Finally, if you find you're accumulating a bunch of hidden tabs and you just want to tidy up, Alt+Clicking (/Option+Clicking) the "Close all open tabs" button will cause Tab Stash to actually close all its hidden tabs (as a one-time thing).

Hope this helps!
