### ISSUE TITLE
The Tab Stash button has disappeared from Firefox toolbar

### ISSUE THREAD

**Issue by aapo88** [josh-berry/tab-stash#447]
The Tab Stash button has disappeared from my Firefox toolbar. I tried "Customize toolbar" but it doesn't show Tab Stash as an option. I've checked that the add-on is still enabled and my add-on configuration hasn't changed.  

OS Version: Windows 10 
Firefox Version: 122.0 
Tab Stash Version: 3.0
 
Can you please help me get the button back? Thank you!

**Comment by josh-berry** [comment]
It may be hiding in the "Extensions" button (the one that looks like a puzzle piece). Can you see if it's still listed there?

See: https://support.mozilla.org/en-US/kb/extensions-button

If it's not showing up there, you may just want to try uninstalling and reinstalling it. (Your saved tabs will be safe even if you uninstall, because they are stored in your bookmarks.)

Hope this helps, let me know!

**Comment by josh-berry** [comment]
Gonna close this out since I never head back, but please let me know if you're still having trouble!
