### ISSUE TITLE
Memory issues immediately after intall 

### ISSUE THREAD

**Issue by johnnieo** [josh-berry/tab-stash#451]
Added tab stash to my system last night and began experimenting.
This morning after boot it  was clear that Firefox was lagging badly, 
here is brief symptom list of issues:
1.) emails are loading slowly,
2.) links are loading slowly, 
3.) fans are ramping up and down constantly and 
4.) temperatures have climbed 15 + degrees into caution/ovverheat zones.

Machine specs as follows:
1.) Intel Core i7-4790 bits: 64 type. Haswell rev: 3  L2 cache: 8 MiB 
2.) 28gb ram
3.) Linux ~ LMDE 5 (Elsie) 
4.) Firefox ESR 115.7 (oesr) 64 bit. 

Windows and tabs:
5 Firefox windows are open with total of 300 tabs. 
3-4 tabs stashed. 

Bookmarks
2000 active bookmarks are showing in the manager. However, the actual number
may be multiples of this. Because the calculation does not  include duplicate folders 
which have not yet been investigated. Prior to the Tab Stash install the machine operated 
without related issues for 3-5 years.

Am open to discussing this is greate retail if it will help to diagnose and provide reference 
or members. Thx.  

Below are a few quick vitals:
17-23% CPU usage??
MemTotal: 24,476,516
MemFree: 728,100
Swap: 3.5gb (44% of 8.2gb)
Tab Stash version: 3.9.22

Note to Josh:
Did investigate about: memory and about: processes but am unable to draw conclusions.

**Comment by josh-berry** [comment]
Hi, sorry for the long delay in getting back to you—life has been pretty busy on my end.

The easiest way to tell if this is Tab Stash or not is to disable or uninstall it, restart your browser, and see if the symptoms persist. If you can enable Tab Stash, see the problem, then disable it again and the problem goes away, that's a pretty clear sign that it's actually Tab Stash. But if the problem persists, it's likely something else.

The only thing I can think of in Tab Stash itself that might start to cause performance problems immediately on install is the size of your bookmarks database—do you know roughly how many bookmarks you have in total (both inside and outside of Tab Stash)? You mentioned 2,000 but possibly it was multiples of that?

Just as one data point, I know that Tab Stash has been used with tens of thousands of bookmarks without issue on machines less beefy than yours, and I myself have ~4,000 saved tabs right now on an older Mac laptop. If you have hundreds of thousands, this might become a problem, though.

All that said, it seems more likely to me that having 300 tabs open is the culprit here—what you're describing sounds more like continuous high CPU usage. If you are not seeing "Extensions" show high in the list of `about:processes` then it's almost certainly not Tab Stash. But if "Extensions" is high in the list, then it could be Tab Stash or some other extension (in which case the enable/disable trick I mentioned will help).

Hope this helps, let me know what you find!

**Comment by josh-berry** [comment]
Gonna close this out since I haven't heard back, but do let me know if you've had a chance to look into this further or if you're still seeing the memory issue!

**Comment by johnnieo** [comment]
Josh,

Appreciate your response.
Most of your responses have already been checked
or performed without resolution;

a few responses to your questions:
About: does not indicate excessive memory usage by extensions, firefox is about 1gb
300 tabs, is not the issue, prior was 400-500 tabs and system ran fine
having reduced to 300 also made an already capable system ,  a bit better
bookmark db is less than 6000
Commands to not reveal too much but may not be interpreting correct

Since beginning this thread have continue to tease out possible issues,
without luck so, reduced open windows to three and tabs to 250,
temps have come down a bit, and fan speeds, memory not so much,

am out of bullets,
am going to retain some help

It's highly unlikely that something else suddenly caused these issues
right after the install, but is also likely that tab stash is fine but that
the install kicked a dependency or process.

My background includes engineering and fifteen years as a linux user
but am not an IT specialist. Am planning to retain some help to
evaluate.  I do have extra memory which would bring system from
24 to 32gb, This will likely solve the problem but throwing hardware
at the problem is not particularly satisfying. The geek in me wants to
know what's going on.

john
Oregon




________________________________
