### ISSUE TITLE
Incompatability with Mullvad Browser

### ISSUE THREAD

**Issue by cohesive-flight** [josh-berry/tab-stash#455]
### System Details

- **OS Version:** Fedora Linux 39
- **Browser Version:** Mullvad Browser 13.0.13 (based on Mozilla Firefox 115.9.1esr)
- **Tab Stash Version:** 3.0

**Installed Browser Extensions:**

- uBlock Origin
- Mullvad Browser Extension
- NoScript

These three extensions are bundled into the Mullvad Browser.

### Describe the Bug

When clicking on icon for tab stash, nothing happens.

### Steps to Reproduce

1. Click on the icon on tab stash
2. See nothing appears

### Expected Behavior

For tab stash to show its sidebar.

### Additional Details

- The extension works on my normal Firefox browser
- It's never worked on the Mullvad Browser based on my previous attempt in installing it a few months ago

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the request! I took a quick look at what Mullvad does/is, and unfortunately, it’s unlikely Mullvad will ever work with Tab Stash, because it disables some of the internal storage features Tab Stash relies on to work properly. (Turning off “save browser history” ALSO disables the database Tab Stash uses to store favicons, deleted items, etc.)

If Mullvad allows/you are willing to save browser history, it’s possible Mullvad might work with Tab Stash. But, never having used it myself, I’m afraid I can’t say for sure.

Sorry to be the bearer of bad news here.

**Comment by josh-berry** [comment]
> Is it possible for tab stash to store its data elsewhere, like how bookmarks do, so it could work within this mode?

Unfortunately not. Disabling history also disables most persistent browser storage, so there's no other option available for Tab Stash to use.
