### ISSUE TITLE
Bring back de-duplication feature removed in #31

### ISSUE THREAD

**Issue by josh-berry** [josh-berry/tab-stash#46]
Tab Stash used to automatically de-duplicate bookmarks when saving to a stash, but there were problems with over-aggressive de-duplication (see #31) which would in some cases delete things that weren't duplicates, so this feature was disabled. It would be nice to find a way to bring it back, either automatically or add some way of allowing the user to trigger de-duplication manually.

**Comment by TheRealBax** [comment]
Suggestion: When stashing tabs, give a hint that there are duplicates (most likely) and "simply" mark them with color or something else and give the user the option to delete the duplicates.

**Comment by josh-berry** [comment]
Thanks, that's a great idea. :) I'll keep it in mind when I get a chance to revisit this.

**Comment by acc987** [comment]
I also just noticed that stashed tabs can shadow bookmarks of the same page when they were created before stashing the tab, in the sense that you manually have to search your bookmarks to find the duplicates as the star in the address bar will refer to the Tab Stash bookmark. As you are effectively using the bookmark mechanic as a data structure, you should provide some way to handle possible duplicates and I would also appreciate it if you could look into this. (As @TheRealBax suggests, a semi-automatic way to prevent duplicates will probably be preferable in order to avoid behavior not expected by the user.)

**Comment by josh-berry** [comment]
@acc987 To be honest, I think having Tab Stash search your entire bookmarks DB for duplicates would probably get very confusing/surprising for most people, since Tab Stash otherwise will not even look at anything outside your Tab Stash folder. So any new/revised de-duplication feature will almost certainly limit itself to what's in Tab Stash.

That said, any extension which de-duplicates your bookmarks should also work well with Tab Stash. For example, I've used this one in the past and found it works pretty well: https://addons.mozilla.org/en-US/firefox/addon/bookmarks-clean-up/

**Comment by acc987** [comment]
Ah, thanks for the clarification, I had not considered that this issue might only be related to duplicates within Tab Stash itself.

I was assuming that you would not have to iterate over all bookmarks to determine whether a page is already as Firefox is already showing that information in the address bar. If there is indeed no API to query this state, then I am wrong and I agree that you should not iterate over all bookmarks each time a user stashes a tab. (Some users might not like this behavior and a fast implementation might be tricky.)

If such an API function ever becomes available, I would at least ask you to reconsider, but for the time being I agree that using a de-duplication Add-on like the one that you suggested should be the way to go.
