### ISSUE TITLE
TabStash: Hidden Tabs

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#461]
### Question

I am a very long-term user of Onetab; but i am finding the move to TS quite confusing.

I do not understand this apparent concept of 'Hidden Tabs'.
Indeed i do not understand just what a lot of the TS options mean/do. The meanings/actions i find quite opaque

(and i speak as an IT, Web, and UI, professional for over 30 years.)

And i can find no actual 'Manual' or Users Guide to assist.

### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Comment by josh-berry** [comment]
I'm sorry to hear that—what, specifically, do you find confusing apart from hidden tabs?

Hidden tabs are exactly what they sound like—rather than closing a tab when you stash it, Tab Stash uses Firefox's "hidden tabs" feature to keep the tab open but not visible from your tab bar. This allows Tab Stash to simply un-hide the tab when you un-stash it (so long as it / the window it's in is still open).

**Comment by dec-mail** [comment]
hmm. i don't know of this FF 'hidden tabs' feature. 
Have seen no mention of it in FF at all.
You don't just mean Minimize, right?

"Tab Stash uses Firefox's "hidden tabs" feature to keep the tab open but not visible from your tab bar. "
Simple question: If they are hidden, how do you see them?
Why wouldn't you just 'stash' Tabs rather than hide them?

And some point, i will create a list of questions about TS and OT functions, and what were missing OT functions, ie the missing ones they never implemented, and how they compare and differ.

**Comment by josh-berry** [comment]
Hidden tabs are a feature specifically for Firefox extensions to use to aid in tab management. Here's a bit of information from Firefox: https://support.mozilla.org/en-US/kb/access-hidden-tabs-firefox
