### ISSUE TITLE
Keeping/preserving Tab Group Names

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#488]
### Problem Statement

I think that this issue might be here somewhere, but i can't find it.

it appears that if i name tab groups in the browser window, those names are NOT preserved when i add/move those tab groups to the TabStash side bar.

am i right?
is this the expected/known behaviour?

of course, i realise i am using another wonderful complementary tab app, Tab Manager Plus. 
which of course might be the whole issue. ;-)
maybe you guys should collaborate?

btw, i am finding TabStash a wonderful replacement for the previous somewhat dysfunctional and totally unsupported OneTab.

And TabStash & Tab Manager Plus are a great high;ly functional combination!!   

### Preferred Solution(s)

If so, obviously, it would be far more efficient and functional, if those tab group names were preserved when saved to TabStash

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
There's unfortunately no way to know what's going on re. grouping/naming in other tab manager extensions—each one has to keep track of things on its own since there's no native/standardized grouping functionality in Firefox. And while two extensions can—sometimes—work together if each one knows about the other, it seems Tab Manager Plus hasn't been updated in a while, so it's unlikely this will be possible.

Sorry I won't be able to help here!
