### ISSUE TITLE
Sudden Odd Tabstash Behaviour - Appears to be only showing/stashing Unstashed Tabs that have not been previously stashed.

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#491]
Sudden Odd Tabstash Behaviour - Appears to be only showing Unstashed Tabs that have not been previously stashed.
### System Details
Win 10 x64
FF xx
TS 3.0.1

### Describe the Bug

When i go to 'stash' active Tabs, all of a sudden, now, it is ONLY stashing Tabs  that (apparently) have not been stashed previously.

it is NOT stashing ALL the active tabs as previously

is this caused by update to ver 3.0.1?

is this one of those MS things that is meant to be a 'feature', but is actually a problem?

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Nope, this should not be caused by anything in 3.0.1.

Perhaps you inadvertently switched from showing "Open Tabs" to showing "Unstashed Tabs"?

![Screenshot 2024-07-08 212906](https://github.com/josh-berry/tab-stash/assets/1203893/11236653-e40a-4929-89e1-509b7261e846)

vs.

![Screenshot 2024-07-08 212923](https://github.com/josh-berry/tab-stash/assets/1203893/6326855f-5edb-4e61-9532-433f3d7c557a)

This might cause what you are seeing, as the blue "stash" button will only stash things that are visible in the list (to avoid any unpleasant surprises). So if you are showing "Open Tabs", it will stash all open tabs, and if you show only unstashed tabs, then it will only stash unstashed tabs.

**Comment by dec-mail** [comment]
Hi there Josh.

 

Thanks for responding.

 

Yes that sounds EXACTLY like that.

 

At 1st glance, I can see no option for that (or when I looked several times before); but let me now check your screenshots.

 

Kind regards

 

Don

***@***.*** 

Mb/Zalo: +84 9 663 651 07

**Comment by dec-mail** [comment]
Update.

 

Yes, it says "Unstashed Tabs" (which I noticed before) - BUT despite extensive searching, I can find NO way to change or toggle that, ie I can find NO 'Open Tabs' option.

 

Kind regards

 

Don

***@***.*** 

Mb/Zalo: +84 9 663 651 07

**Comment by josh-berry** [comment]
Just click on the text: "Unstashed Tabs". It will toggle back and forth between "Unstashed Tabs" and "Open Tabs" each time you click it.

**Comment by dec-mail** [comment]
Thanks for fast response, Josh.

 

But f*k me, that is, not only NOT intuitive and totally opaque; but is very prone to error by clicking/changing it when you are trying to do something else.

 

(I note that this is the same perverse logic and UI design you use for renaming Tab Groups)

 

Kind regards

 

Don

***@***.*** 

Mb/Zalo: +84 9 663 651 07

**Comment by dec-mail** [comment]
PS Just to say (again) that nonetheless TabStash is a wonderful app, and much better than OneTab ever was.

And the complementary combination of Tabstash and Tab Manager PLus is just wonderful synergy.
