### ISSUE TITLE
differentiate private and normal lists

### ISSUE THREAD

**Issue by q962** [josh-berry/tab-stash#501]
### Problem Statement

Content in private mode does not need to be displayed in normal mode. Likewise, the reverse is also true.

### Preferred Solution(s)

Should not be shown by default, but can be toggled via a button

It is a good idea to add a flag to the list item to indicate that the group is private.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately, due to the way Firefox bookmarks work, there's not a way to do this—bookmarks are always shared between private and non-private browsing modes. So even if I were to use different folders in Tab Stash (for example), it would be trivially easy to find private bookmarks in non-private mode just by opening the bookmark manager.

I have heard Mozilla is working on features to allow for multiple profiles to be used at once, so something like this might be what you need once it's available.

Sorry I won't be able to help here!

**Comment by q962** [comment]
I may not have described it in detail enough.

I need a button to do the following:
In normal mode:
- show private list

In private mode:
- show normal list

It should distinguish between groups instead of tabs.

I don't know how this is related to `bookmarks`.
Isn't it using `storage` as a storage method?

**Comment by q962** [comment]
When I was browsing my bookmarks, I found the "Tab Stash" directory.

I understand why it is not possible to distinguish between private and non-private.

But I still feel the need for this feature, so I will try to write the code.

The compromise is: add a symbol to the "private group" name. This symbol will not be displayed in the plugin. This will distinguish the difference between the two.

**Comment by josh-berry** [comment]
I saw your PR, and I think if you want to get something merged that solves this problem, we should talk about the approach before you write any code, to make sure we both agree on it first.

My concern with the approach that you've taken here (and anything similarly-shaped) is that it would give users the false impression that their stashes are somehow more protected in private mode than not-private mode, which just isn't true. I also really want to avoid adding any "special" tags, strings, etc. to bookmark node names and URLs, because this is unfriendly to anyone who uses other tools (even the default bookmark editor), other extensions, etc. to work with the bookmarks in their stash.

My preferred way to do this would be to implement something like #162, and give people an additional opt-in to choose a different root folder for private browsing windows and/or different containers. I think this would be a cleaner approach implementation-wise as well; you would only need to change how the root folder is detected and updated, and add options accordingly.

Hope this gives you some ideas on how to proceed, thanks for looking into it!

**Comment by q962** [comment]
I understand the trouble of using other tools to manage bookmarks.
But I think there should be a consensus: when a set of data is unique to a certain software, you should not modify its content through other software.
Although the current data is bookmarks, it is relatively simple content.
But users should actively ignore the entire "Tab Stash" directory when using other bookmark managers.

Yes, using different roots to store different data is a good choice. I will continue to modify it!

**Comment by q962** [comment]
As for private tabs, they should be better protected.

For this case, use the description as a hint to dispel the wrong idea.

I will provide more options. 

Private tabs will allow the use of local storage. Features such as not showing by default

**Comment by q962** [comment]
The following features will be provided:
1. Allow local storage
1. Add new root directory to store private bookmarks.
   Use local storage by default.

Solution for #162:
Allow setting of root directory name (not sync)

**Comment by q962** [comment]
Can you describe your debugging process?

**Comment by josh-berry** [comment]
> Can you describe your debugging process?

Not sure I understand your question? If you're asking about how to work on Tab Stash in general, probably the best place to start is to read the contributor doc: https://github.com/josh-berry/tab-stash/blob/master/docs/contributing.md — and then let me know if you have more specific questions (best thing to do is comment on the issue you're working on, or open a new issue ahead of time if you plan to work on something that's not covered by an existing issue).
