### ISSUE TITLE
Have you changed anything performance related lately? 

### ISSUE THREAD

**Issue by 96jaco96** [josh-berry/tab-stash#508]
### Question

I've noticed that after this last update (3.0.1) searching became very slow. What was instantaneous before now takes around 2 or 3 minutes. During this time the page seems frozen and firefox actually thinks it crashed; But if you wait it eventually finish "calculating" and returns the results of the search query. So yeah my question is: have you changed something lately about this specifically? 
And also it should be noted that i have A LOT of tabs, around 6000... but again: it was instantaneous before... Thanks!

### System Details

- **OS Version:** Arch Linux
- **Browser Version:** FireFox 128.0
- **Tab Stash Version:** 3.0.1

**Comment by josh-berry** [comment]
hm, that's quite surprising! I haven't made any performance (or even implementation) changes in the search department, no. I made drag-and-drop faster but that's about it. Search works exactly the same way it did in 3.0.

A few questions to see if I can narrow things down:
- Does it make any difference whether you search in the popup view, the sidebar, or the full-tab view?
- Can you share the specs of your system?
- Any other performance issues you've noticed at the same time, either in Firefox or in your system at large?

I have about 4,400 tabs on my M1 Mac and searching is nearly instantaneous. So I'm very surprised it's taking upwards of 2 minutes.

**Comment by josh-berry** [comment]
Oh, one other question I forgot to ask: about how many bookmarks do you have _in total_ (even outside of Tab Stash)?

**Comment by 96jaco96** [comment]
it makes no difference if i search in the side bar or in the full tab; i've tried it 3 times each now and i'm getting an average response time of ~45 seconds. it seems faster now compared to some days ago, but still: not instantaneous. 

my pc has an AMD Ryzen 5600, 32GB of RAM and the system is on a m.2 SSD. 

haven't noticed any other performance issues in the whole system.

i haven't many other bookmarks besides the ones in tab stash, so yeah, around 6000 (6268 total bookmarks tab stash + outside bookmarks to be exact)

At this point i believe that it might be something else that was updated or changed in my system and not tab stash per se.... 
Arch Linux is a rolling distro and always has the latest stable version of everything, and i update it every week or so.

Since you haven't touched anything search related i'm starting to think that maybe it's not related to the tab stash update and it was probably just a coincidence. 

I don't know how to debug this tho haha.

**Comment by josh-berry** [comment]
Depending on how much you want to dig into Tab Stash's code, probably the easiest thing to do is to collect a profile while trying to search.

Since you have some repos of your own on GitHub, I'll assume you're technical enough that the following will make sense, but let me know if any of this is confusing and I can do a more detailed walkthrough for you:

1. Open Tab Stash in a tab
2. Open the web inspector (right-click anywhere in the page and choose "Inspect")
3. Choose the "Performance" tab
4. Make sure you're using the "Web Developer" settings and click "Start recording"
5. Do a search in Tab Stash, then wait for the search to complete and the UI to finish updating
6. Click "Capture recording"
7. Firefox should open a new tab with all the profiling info
8. Upload the profile and share the link here. (I have double-checked on my own system, and Firefox seems to anonymize anything that could be personal info, e.g. page URLs you have open, etc.)

To upload the profile, click "Upload Local Profile" in the upper-right corner and include extension information:

<img width="538" alt="Screenshot 2024-07-28 at 12 30 41" src="https://github.com/user-attachments/assets/2aeb86c2-6f18-4602-b90a-f761605fb2b5">

Then share the permalink with me (it should start with `https://share.firefox.dev/...`).

(And, if you want to poke around inside the profile yourself, you certainly can—Firefox has some nice docs on how to use the profiler here: https://profiler.firefox.com/docs/#/ )

**Comment by 96jaco96** [comment]
I did it, i just hope it did not leak any personal stuff like my bookmarks and such... hahaha, here's the link: https://share.firefox.dev/3StfrC5 let me know...

**Comment by josh-berry** [comment]
Thanks, that does help. I am wondering if something changed in one of the libraries Tab Stash uses, because I see that most of the time is spent re-drawing the UI (not in Tab Stash code). I don't have a clear answer as to exactly what's happening, yet, but it does point me towards something to look into further.

I also have some general performance improvements planned, and seeing this profile tells me those should help as well once they're finished.

Regardless, that's really unfortunate re. performance on Linux. I'll see what else I can find out.

**Comment by 96jaco96** [comment]
Thank you for looking into this!

Yeah, i thought it could've been something else that updated and changed in my system.

But now i wonder if this issue will arise to other systems too eventually...

Arch Linux being a rolling release always has the latest updates of everything, and this also means that if there are any incompatibilities or problems they arise here first.

If this problem was caused by a library or something that tab stash depends on it means that when eventually it'll be updated on other systems too it'll show this problem there too...

Unless it's something Linux specific of course.

**Comment by MrConorAE** [comment]
Hey, just checking in on this. I've started experiencing these slowdowns too. Nowhere near as many tabs (only ~2000 here, with ~100 outside Tab Stash), but searching is noticeably slower.

Looks like it may actually be a Linux thing - I'm on Ubuntu 24.04, running (non-snap) Firefox 130.0b5.
Let me know if there's anything I can do to help :)

**Comment by char8x** [comment]
I seem to have encountered a similar problem, I have 300+ groups and 1600+ tabs, I'm on macOS 14.6.1, running Firefox 115.14.0 esr.

Here's what the screen recording looks like, sometimes 1~2 seconds lag when typing or deleting characters

https://github.com/user-attachments/assets/0cd32ada-2556-4e5f-bc52-c242121b29b9

**Comment by josh-berry** [comment]
Closing as a dup of #97
