### ISSUE TITLE
Moving/Copying Stashed Tabs

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#513]
Josh
Two related things/behaviours i have noted (again) in past couple of days, both which are non-standard, illogical, dysfunctional. 

1. I can't drag and drop a tab/tabs onto the TOP of a closed Tab Group; instead, i have to first open the Group, and then drag & drop selected Tabs INTO the Group

2. Having selected a single or multiple Tabs, and then moved or copied, the industry-standard logical functional behaviour  would be that, if i then click on any single Tab, it would automatically DEselect the previously selected Tabs.

but it doesn't!

As you know, first, you have to select the top/bottom previously selected Tab, and then, Shift-Select the bottom/top Tab of the selected Tabs to deselect them all.

That is just slow, dysfunctional and non-standard behaviour.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
(1) is a known feature request covered by #407.

Regarding (2), I agree with you this was a standard earlier on, but it has become much less of a standard over time, especially with web applications—many web apps are moving away from this because it's less intuitive to newer users who do not have so much experience with Windows Explorer (/File Manager...), Finder, etc., and it's also a minor accessibility issue for those who may find it physically difficult to hold a modifier key while clicking repeatedly.

For Tab Stash, this is another case of something I thought about and chose very deliberately—without this behavior, it would not be possible to open a tab while in the middle of a selection operation. This, in turn, is important because sometimes one wants to open a tab to decide whether to include it or not.

Hope that clarifies things!
