### ISSUE TITLE
add other functions such as removing duplicates

### ISSUE THREAD

**Issue by GHOSTS15** [josh-berry/tab-stash#528]
### Problem Statement

hello I have 31 thousand bookmarks(no joke) this is the only extension that comes close to helping me d organize them well however it lacks important features like for example a function to remove duplicates (would be a big hand, I have thousands of them scattered around), or even the simple conetege of total bookmarks(this less important) and add translation to Italian(I can do translation).

### Preferred Solution(s)

since it works with bookmarks (and just move the folders to the “tab stash” folder to implement them in the sidebar), you could introduce:
1)Important.Button to automatically remove duplicate bookmarks (which leaves only one and not duplicates) or even manually but with the ability to select multiple duplicate bookmarks to remove at a time (not remove one at a time)
2)Add a count of total bookmarks.
3)Check if bookmarks are working.
4)Add translation to Italian

### Alternative Solution(s)

remake the firefox bookmark system

### Additional Context

maybe revise a little bit the positioning of the various function keys, make it of little understanding what they do

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Thanks for reaching out! There are a few different feature requests in here I'll try to unpack:

1. Removing duplicates. This is covered by #334 already.
2. Counting every bookmark is unfortunately not advisable, because that requires _loading_ every bookmark, which is a performance and memory-usage issue. (In fact, this is the single biggest performance improvement that was rolled out in the latest version of Tab Stash—loading bookmarks alone was taking a substantial amount of time during startup.)
3. That's fair and probably worth its own feature request.
4. Enabling translations is covered by #130. Specific languages would have to come after #130 is done unfortunately.

Regarding all of these except (4), I think you might actually be better-served by using other extensions alongside Tab Stash. For example, there is a [Bookmarks clean up](https://addons.mozilla.org/en-US/firefox/addon/bookmarks-clean-up/) extension that can do much of what you describe, but across your entire bookmarks tree (not just those in Tab Stash).

Hope this helps, let me know your thoughts!

**Comment by GHOSTS15** [comment]
> Regarding all of these except (4), I think you might actually be better-served by using other extensions alongside Tab Stash. For example, there is a [Bookmarks clean up](https://addons.mozilla.org/en-US/firefox/addon/bookmarks-clean-up/) extension that can do much of what you describe, but across your entire bookmarks tree (not just those in Tab Stash).
> 
> Hope this helps, let me know your thoughts!

the “problem” is that all other extensions to organize bookmarks are not monitored by mozilla , instead yours is and more reliable (not that the others can't be)

**Comment by josh-berry** [comment]
LOL, fair enough! It's true that Mozilla scrutinizes every version I release. They have started doing that more stringently even with non-recommended add-ons, though, so I think things will get better for others soon.

Since I already have issues open for the things you mentioned, I will go ahead and close this one, but feel free to reach out anytime!
