### ISSUE TITLE
Does Tab Stash support open several selected tabs of a group and delete them from that group?

### ISSUE THREAD

**Issue by qqlovekerry** [josh-berry/tab-stash#53]
### Question
Hi, I am using Tab Stash and I am trying to replace OneTab with Tab Stash. The sync function is very useful and the stash process is quick and clear. I also found that if I have a bunch of URLs, I can import them from Firefox, and then they will show in the view of Tab Stash. However, when I try to open them in the Tab view with `Open this tab and delete it from the group`, it jumps to the newly opened tab in the browser. If I want to open like 10 tabs at a time, I need to jump between the views for 10 times. Does Tab Stash support open several selected tabs of a group at once and delete them from that group? The action of popping up a tab seems is not as quick as that in OneTab, it would be better if this can be improved.

### Supporting Details
*Please complete the following information if relevant:*
 - **OS: Linux** 
 - **Firefox Browser Version: 75.0**

**Comment by josh-berry** [comment]
Hi, there's no multi-select feature right now, but to open a tab in the background, you can Ctrl+Click on it, and this works for the "Open this tab and delete it from the group" button as well, just like you would Ctrl+Click on any link to open it in a new background tab.

So to avoid having the focus moved away from Tab Stash while you are opening your 10 tabs, just hold down Ctrl and click on each button. You can also use the Tab Stash sidebar if you prefer (which will stay open regardless).

I'll take a look at the performance issue you mentioned; I'm a little surprised to hear it's not as snappy as OneTab (or any other extension)—there's some extra logic in the background to search recently-closed and hidden tabs to find one to restore (rather than opening a new one fresh each time), but that should be making things faster, not slower. :)

**Comment by qqlovekerry** [comment]
Hi,
Thanks very much! Ctrl+Click is just the right thing I needed. That is great. Do you ever consider writing a brief instruction for Tab Stash? I think the number of people using this addon is increasing and maybe it can save your time since simple questions like this one would not bother you anymore. I am sorry I only found the brief description on the Github page and did not find an official guide.
Considering the performance issue, I have re-used both of them and to feel the response. Possibly it is due to I have more than 100 tabs in a group and when one tab is popped up, the tabs remained in that group needs to rearrange and it makes me feel like a lag existed. It seems that feeling is not that obvious in the side view. And it is just a direct feeling of me and I do not have any data to support that. If I feel that wrong, I am sorry for the bothering. Anyway, thanks for creating this addon and I hope it becomes better and better. I think I can safely replace OneTab with Tab Stash now.

**Comment by josh-berry** [comment]
Awesome, glad to hear it! :) A guide is probably not a bad idea. So far I have the [tips and tricks page](https://josh-berry.github.io/tab-stash/tips.html) and the various screenshots on addons.mozilla.org to show off the main features, but there's probably more that can be done.

One quick thing I want to do is change the help text which shows up when you hover over the "Open this tab and delete it" icon. If that help text mentions Ctrl+Click, hopefully that will make it easier for others to discover.

Re. the performance issue, it never hurts to take a quick look. :) I haven't done a lot of performance work on Tab Stash (other than to make sure it can scale to handle very large stashes), so even if it's subjective, there might be something easy that can be improved.

For now I'll keep your issue open to remind myself:

* Add "Ctrl+Click" to the open/delete tab help text
* Look for low-hanging performance fruit when restoring tabs (and maybe also stashing tabs, while I'm at it)

**Comment by josh-berry** [comment]
Added the Ctrl+Click text for the next release. I took a quick look but didn't see anything obvious performance-wise that could be improved while restoring tabs. But if something does seem noticeably slow in future, definitely feel free to open another issue. :)

**Comment by qqlovekerry** [comment]
Hi, about the performance issue，I think the feeling is caused by the fact that when I import about lots of tabs in a single group and I click my mouse to open them in the tab view, sometimes when the length of the list becomes shorter, the location of the tabs is rearranged. And at that time, I need to re-locate my mouse and then click. I think if the two buttons (yellow and red, to open and delete the saved links) are at the leftmost of the link, possibly it would be much convenient. Could you please consider that?

**Comment by josh-berry** [comment]
Very early on in the development of Tab Stash (before releasing it), I had actually started with the buttons on the left. But I had to reserve space for them to the left of the icon/tab title, because I didn't want them to cover the icon (so the icon can be clicked to select a tab, once multi-select is implemented). Ultimately I found the buttons took up quite a bit of space, making it harder to read the titles, which is why I moved them to the right.

That said, it's certainly something that could be done as an option, so feel free to open a feature request. :) Just something to keep in mind that it might make your tab titles harder to read.

**Comment by qqlovekerry** [comment]
Hi, thanks for the explanation! My feeling is that if the icons are located at the rightmost of the bar. When tabs are popped up, the positions of the tabs would float and I need to relocate my mouse to click. It might be hard to avoid, so it is just for your reference.
By the way, have you ever used the addon `start.me`. That addon has a good function to organize URLs into different groups and even into different pages. But I feel the stash function of that addon is kind of difficult to be used. Is that possible to enhance the group function of TabStash in the future?  With the excellent stash function, I think TabStash would be a swiss knife to save tabs.

**Comment by josh-berry** [comment]
I haven't used it, but I've made a note to check it out. Thanks for the pointer!
