### ISSUE TITLE
"Stash All" UI Wastes my Time

### ISSUE THREAD

**Issue by Brandon8D** [josh-berry/tab-stash#55]
I chose your program because of the simple UI.  I got it because I have too many tabs open (had over 1000). I am interested in a wide range of subjects, and so far have created 19 groups to contain my Tabs.
But the program has some major shortcomings that are a real problem, so I cannot recommend it yet.

BUG:  If you click on the "Stash All" icon, which also shows up on the Firefox toolbar, but zero or just one tab is selected, the program, without giving you a choice, puts ALL open tabs into that group.  AND deletes from the browser view. 
1. If that is a desirable feature, there should be popup a choice to: "Stash All Tabs", or the One tab highlighted, or Cancel the action. I have clicked on it by mistake more than once and caused this problem, which, with hundreds of tabs open, will cost you 15 minutes or more by the time you get all your tabs re-opened again.
2. The icon on the browser toolbar should default as "Show Stashed Tabs in Sidebar" when left-clicked This would be in conformation to other programs which open a basic functions window from the toolbar icon e.g. Adblock Plus (This could be user-configurable but as it is it sabotages me.)

 - **OS:** Windows 10 (up to date)
 - **Firefox Browser Version: 75

The below are requested Enhancements which I will also submit in their own post. I am including it here as everything I am submitting will together allow for fast sorting / grouping  and use, and make it a 5* program:

1. Really needed: Able To select multiple tabs in one group so to move them to another group (or to delete I suppose). This will speed up one's grouping setup a lot, correcting mistakes.

2. If a tab is already open, it just needs to go to that already opened tab, not open another.
Sometimes it does, sometimes it doesn't.

3. It needs to open tabs next to the current viewed tab, not at end of all tabs. 
Example: I have a group I call "Office". I want it at the left end of my Tabs. But it opens on the right end. Or sometimes I want to open a tab or tabs next to something I am working on.

Thank you.

**Comment by josh-berry** [comment]
Wow, there is quite a lot to unpack here. Let's go point by point.

The "Stash All" toolbar button:

1. There is already an enhancement request, #21, which covers this—if you're interested, you can subscribe to that issue and vote for it by giving it a thumbs-up (click the 😄 icon in the upper-right corner of the issue description). And if you have more ideas/specifics to add to that discussion, please feel free to leave a comment there.
2. This can certainly be one of the choices to be added for #21 (so you could make it *your* default), but I don't agree that it should be the default for all users. Firefox already offers a "Show Sidebar" button for the toolbar, so making the Tab Stash button do the same thing would be redundant. For example, I have my toolbar configured to place the "Sidebar" button right next to the "Stash" button, and this way I get the single-click ability to both show the sidebar AND stash tabs.

Regarding your other enhancement requests:
1. Yes, I agree this would be helpful. It's a large enough effort that I would like to track it separately. Can you please open a separate enhancement/feature request?
2. Tab Stash already does this. It searches for open tabs by comparing against the full URL. So if the URLs don't match exactly, Tab Stash will not be able to tell you already have that page open. It's done like this because there is no way to tell which parts of a URL are significant—sites can structure their URLs however they choose, and can change their URLs to store extra information even if you don't navigate between pages. So we err on the side of opening a new tab, rather than showing you something that isn't what you asked for—this may explain why you are only seeing this behavior "sometimes". If you find a situation where the URLs match exactly but Tab Stash still opens a new tab, please file a separate bug (preferably with example URLs and as much detail as possible).
3. I have a few more questions for you here, but I think this one also merits its own enhancement request. Can you please open a separate request and elaborate a little more on what you're looking for? For example, are you asking to *keep* tabs in the same group organized together, or is the issue simply finding the new tabs that are opened?

I'm asking for separate issues because having one issue per item helps me to keep things organized and prioritized so I can plan future releases. It also gives others who are interested in the same issue a single place to go to vote for and discuss that item, keeps the discussion focused, and ensures all the feedback/input on that item is easy to find in one place.

Thank you for taking the time to write up your Tab Stash feedback!

**Comment by Brandon8D** [comment]
Ok I opened the two threads you requested.

I am trying to help you improve the User experience.
I don't think I made clear the magnitude of the problem I ran into.
One should NOT have to find / read the instructions to do basic stuff in any utility program. (A complicated program like Photoshop or a Spreadsheet will require some learning to get going, but that is different sort of animal.)
Clicking the obvious button (think new user), or by mistake, should not put you in Tabs hell. I've been there at least four times now, for well over an hour of lost time.


Re my requests under BUGS at top of my post:
Re 1.  This is not the same issue as #21.  Tab Stash should not let you "shoot yourself in the foot", which it does now, by default! My suggestion 1 of a Popup WILL work, anywhere the "Stash All" button appears. 

Actually you might be able to only have one "Stash" button, not a separate "Stash All", but with a popup. 
A pop up, with three choices (box buttons): Cancel, Stash Selected Tabs, Stash ALL Tabs. 

AND:
One tab selected should NOT Stash ALL. It does now.

And the hover Help text should be kept!

And the default cursor position on the popup should be on the "Cancel" button. This helps when one is tired and "Clicking through", to not screw up.

And the "Hold ALT" notice there and available too in the Popup.


Re 2. You said "Firefox already offers a "Show Sidebar" button for the toolbar".
However it opens the last sidebar you had open, and I often open my Bookmarks (CTRL B) to search for one.
After doing that it will NOT open the Stash.
Thus my suggestion number 2, to open the Stash as the default action. That is not critical, as you get there by right click, but suggestion 1 is.

Thank you for your explanation re Enhancement item 2.

Also, many of your explanations could go into a user Wiki or manual.

**Comment by josh-berry** [comment]
> Ok I opened the two threads you requested.

Thanks!

> I don't think I made clear the magnitude of the problem I ran into.

It was quite clear in your original post.

> Clicking the obvious button (think new user), or by mistake, should not put you in Tabs hell. I've been there at least four times now, for well over an hour of lost time.

I'd like to understand what exactly happened here. If you click the "Stash all tabs" button by mistake, it only requires a single click to restore and delete the newly-created stash. Under normal circumstances, I would expect the restore operation to take even less time than the original stash operation. Can you explain a little more about how/why it took you an hour to recover?

> Re 1. This is not the same issue as #21. Tab Stash should not let you "shoot yourself in the foot", which it does now, by default! My suggestion 1 of a Popup WILL work, anywhere the "Stash All" button appears.

#21 is about adding options to control the behavior of the toolbar button. It doesn't mention popups specifically, but as I mentioned before, a popup can certainly be added as one of the options.

> Re 2. You said "Firefox already offers a "Show Sidebar" button for the toolbar".
> However it opens the last sidebar you had open, and I often open my Bookmarks (CTRL B) to search for one.

You can also use the Tab Stash keyboard shortcut to open the sidebar (Ctrl+Shift+S on Mac, Ctrl+Alt+S on Windows). Or you can right-click on the toolbar button and choose one of the "Show Stashed Tabs" options.

I know this isn't ideal compared to having a dedicated button. Until I get time to implement #21, that's probably going to be the best option, unfortunately, since Firefox only allows extensions to add a single button to the toolbar, and a single button to the URL bar.

> Also, many of your explanations could go into a user Wiki or manual.

* There is a Usage Tips page (which discusses the sidebar button and keyboard shortcuts) here: https://josh-berry.github.io/tab-stash/tips.html
* And the wiki is here, although it is focused more on specific problems/issues you might encounter: https://github.com/josh-berry/tab-stash/wiki

Your question about Tab Stash not reusing open tabs hasn't been asked before, but I'll keep it in mind for a future addition to the tips page or the wiki.

**Comment by Brandon8D** [comment]
I will start with this one:
"I'd like to understand what exactly happened here. If you click the "Stash all tabs" button by mistake, it only requires a single click to restore and delete the newly-created stash. Under normal circumstances, I would expect the restore operation to take even less time than the original stash operation. Can you explain a little more about how/why it took you an hour to recover?"

** Let us say I just spent an hour poring through open tabs and selected 50 of them into a group "INVESTING and CHARTS". Then I accidentally stashed ALL tabs there. I don't know if the ones I selected are at the top or are now interspersed or what. So now I have to at least skim all the tabs which are now in the group, to figure it out (remember, over 1000). Then I have to create a temporary group to move the ones that I actually want in this group, and move them there, one by one. THEN I can open all tabs and delete the group, then rename the temp group to "INVESTING and CHARTS". And this is the LEAST time-intensive way I came up with, better than starting over completely for this group.  (I went through this several times.)

**Comment by josh-berry** [comment]
Got it, thanks for the explanation. Browsers really aren't designed for having ~1000 tabs open at a time, and I wouldn't generally expect Tab Stash users to have anywhere near that many tabs open on a regular basis—after they get organized and set up. But as a new user trying to get out of that ~1000-open-tabs situation, I can understand why this would be frustrating.

I think another way to address this might be to place a soft limit on the number of tabs that can be stashed at once. For example, if over 50 (or 100, or whatever) tabs will be saved, open a prompt to ask "Are you sure you want to stash 1024 tabs?". Then your workflow is only interrupted when it's likely you're about to make a mistake—and the single-click stashing behavior still works outside of those times.

In the meantime, one approach that might be a bit faster for you is to open a new browser window (if you still have anything open in the original window), load Tab Stash in the new window, and scroll through your list of 1000 wrongly-stashed tabs and click the yellow "Open ... and delete" button on each tab you want to keep. Then click the "Stash tabs" button in the Firefox toolbar to save those tabs to their own group. This will save you from having to drag-and-drop each individual tab.

**Comment by josh-berry** [comment]
I went ahead and filed #62 as an enhancement summarizing our discussion and a couple possible ways to avoid the frustration in future. I'll close this out for now but feel free to subscribe to that issue for updates, and/or add any more thoughts/comments you have.

Thanks again for taking the time to write up your feedback, and if any other questions/concerns/etc. come up, please don't hesitate to open a new issue!
