### ISSUE TITLE
Append to top group only works if NOT CUSTOMISED group

### ISSUE THREAD

**Issue by oehm-smith** [josh-berry/tab-stash#556]
### OS Version

MacOS 14.7 Sonoma

### Browser Version

Firefox 132.0.1

### Tab Stash Version

3.1.1

### Non-Standard Browser Settings

n/a

### Installed Extensions

None.  I created a fresh FF profile and installed TS.

### Problem Description

Appending to top-most group only works for a TS created group with time/date name.  If you rename to create named groups they aren't used.

### Steps to Reproduce

1. Start fresh profile so know it is not another extension
2. Launch profile
3. Install Tab Stash
4. Turn on advanced settings and make sure 'when stashing a single tab: append to top group...' has a minute value
5. Create 3 new tabs
6. Save No_1 as stash (I have 'stash active tab' and 'show the stash in the sidebar') and it appears in dated group
7. Save No_2 as stash and it goes to same group
8. Rename group
9. Save No_3 as stash and it goes to new dated group

### Expected Behavior

The stashed tabs (within time window) should go to top-most regardless of it's name.

### Impact

This is obviously not a killer bug.  But it could cause 'data loss' if you create a named group (*) and expect stashed tabs to go there.  Don't get me wrong - this Extension is AMAZING for productivity.  It would be nice if it was closer to perfect!

(*) - I have billions of tabs opened and I haven't found a good way of managing it that isn't overly onerous.  TS is close to being that.  I will make it a pillar of my Firefox productivity.

To make perfect:
* Instead of 'append to top tab', allow users to pick a bookmarks folder
* Link to diigo or other similar web-based bookmarking services (use AI to generate recommended tags!)
* Nested folders to help organise things

### Vote for This Issue

- [X] _Readers: If you are also experiencing this problem, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system._

**Comment by oehm-smith** [comment]
I found a decent work-a-round.  
* Have TS show unstashed tabs in the sidebar
* Drag to named groups

**Comment by josh-berry** [comment]
Hi, thanks for reaching out. This is actually intentional (though perhaps the setting should better-explain this)—un-named groups work slightly differently in two ways:

1. When stashing from the address bar, or using the blue buttons next to "Unstashed Tabs", as you noticed. Tab Stash deliberately does not stash to a named group, because it doesn't know whether you're intending to add the tab to an existing group or start a new group, and it's much easier to combine an unnamed group with a named group than it is to find a tab that was stashed in the wrong named group by mistake.
2. When moving things out of an unnamed group, if the unnamed group becomes empty, it is automatically deleted.

You CAN stash directly to a desired group from the Tab Stash UI if you want—there are a couple ways to do it:

- Drag-and-drop (like you discovered)
- In the Tab Stash sidebar or popup, use the blue buttons that appear when you hover over the group's name to stash all/the active tab directly to that stash
- Select the tabs you want to move (click their icons) and then use the blue drop-down menu that appears in the upper-left corner to move them to the group you want. (Or scroll directly to the group and use the blue buttons to move them.)

Hope that helps, let me know if you have any more questions!
