### ISSUE TITLE
Isn't this extension meant to hide/close active tabs when you stash tabs??

### ISSUE THREAD

**Issue by Spaceboy60** [josh-berry/tab-stash#563]
### Question

Because it doesn't do that on Floorp Browser (Firefox based).  Tabs remain the top of the page when you select "stash tabs".

Works on Waterfox fine, but not sure why it's not working on floorp.

Suggestions?

**Comment by josh-berry** [comment]
If it's working on Waterfox, the problem is most likely with Floorp itself. I'm not familiar with most of the Firefox forks, I'm afraid.

One possibility is that Floorp just does not support hiding tabs at all. A quick thing you could try is changing what happens when tabs are stashed—if you tell Tab Stash to "Close the tab immediately" instead of hiding them, this might resolve the issue.

Otherwise, if you want to troubleshoot with the Floorp folks, a good place to start is by collecting error logs: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

This might show why the tabs aren't being hidden as expected.

**Comment by Spaceboy60** [comment]
> One possibility is that Floorp just does not support hiding tabs at all. A quick thing you could try is changing what happens when tabs are stashed—if you tell Tab Stash to "Close the tab immediately" instead of hiding them, this might resolve the issue.

Thanks, that worked!!

**Comment by josh-berry** [comment]
Glad you were able to sort it out!
