### ISSUE TITLE
Need Ability to Select Multiple Tabs in one Group

### ISSUE THREAD

**Issue by Brandon8D** [josh-berry/tab-stash#57]
Really needed: Able To select multiple tabs in one Group so to move them to another Group (or to delete I suppose). This will speed up one's grouping setup a LOT, especially correcting mistakes.

**Comment by josh-berry** [comment]
Wholeheartedly agree. Thanks for filing this as a separate issue.

**Comment by josh-berry** [comment]
see also: https://github.com/SortableJS/Sortable/wiki/Dragging-Multiple-Items-in-Sortable

**Comment by josh-berry** [comment]
This will be available in 2.10, coming soon!

**Comment by lucatrv** [comment]
Sorry but I can't find out how to select multiple tabs in one group. I tried with Shift+Click but it does not work. I'm using Firefox 94.0.1 on Windows.

**Comment by AnttiBoman** [comment]
> 

Just like the release info says, just click on the tab icon on the left side of the tab links. If you don't see them, maybe your extension hasn't been updated?
![image](https://user-images.githubusercontent.com/3209996/142735022-fa875aff-6072-44ba-947e-57d394974c3a.png)

**Comment by josh-berry** [comment]
Sometimes it can take a few days for your browser to notice an update is available, here's how to force an update if you're not on 2.10 already: https://github.com/josh-berry/tab-stash/wiki/Make-Sure-Tab-Stash-Is-Up-to-Date

**Comment by kljohann** [comment]
The new multi-select feature is super useful, thanks for continuing to make this extension even better. Also, I love how I can now scroll the sidebar using the touchscreen (previously, touch events would initiate drag-and-drop of a single tab). (Possibly as an effect of the new implementation using Vue 3?)

W.r.t. the ![image](https://user-images.githubusercontent.com/67211/142772530-d12b5e3e-fec1-4000-82eb-b526214938ed.png) menu: Could you add an "unselect all" option? Also, right now the selected tabs stay selected after using that menu to move them to another group.

**Comment by lucatrv** [comment]
> > 
> 
> Just like the release info says, just click on the tab icon on the left side of the tab links. If you don't see them, maybe your extension hasn't been updated? ![image](https://user-images.githubusercontent.com/3209996/142735022-fa875aff-6072-44ba-947e-57d394974c3a.png)

Thanks for the hint, now it works fine. I was reading the [Usage Tips](https://josh-berry.github.io/tab-stash/tips.html) and got confused the about multiple tabs selection using Shift+Click or Cmd/Ctrl+Click mentioned there. I think this hint should be added to the usage tips.

**Comment by RealRedFox** [comment]
Hello. This is accelent feature, but is it possible to select multiple tabs just with Ctrl+LMB, as in file explorer?

**Comment by josh-berry** [comment]
@kljohann:
> The new multi-select feature is super useful, thanks for continuing to make this extension even better. Also, I love how I can now scroll the sidebar using the touchscreen (previously, touch events would initiate drag-and-drop of a single tab). (Possibly as an effect of the new implementation using Vue 3?)

Thanks, I'm glad to hear it! Actually this probably changed because I switched how drag-and-drop was implemented--I was using an off-the-shelf component before (Vue-Draggable), and switched to my own implementation to better-handle multi-select.

> W.r.t. the ![image](https://user-images.githubusercontent.com/67211/142772530-d12b5e3e-fec1-4000-82eb-b526214938ed.png) menu: Could you add an "unselect all" option? Right now the tabs stay selected after using that menu to move them to another group.

You should be able to click in any blank space in the window (e.g. the whitespace between stashes) to unselect everything. Another good place to aim for is one of the separator lines between the stash title and tab list. If this is proving too cumbersome, please do open another issue and let me know though.

-----------------

@lucatrv:
> @josh-berry I think this hint should be added to the usage tips.

Thanks, I've made a note of this.

-----------------

@RealRedFox:
> Hello. This is excellent feature, but is it possible to select multiple tabs just with Ctrl+LMB, as in file explorer?

No, unfortunately not, since Ctrl+click is reserved for opening a tab in the background (just like Ctrl+clicking a link). However, once you select the first tab and the blue selection menu appears (as shown in @kljohann's post above), you can select subsequent tabs just by clicking on the titles. So you only need to aim your mouse at the small icon for the first click, and you have a bit more room for error on subsequent clicks. Hope this helps!

**Comment by kljohann** [comment]
> You should be able to click in any blank space in the window (e.g. the whitespace between stashes) to unselect everything. Another good place to aim for is one of the separator lines between the stash title and tab list. If this is proving too cumbersome, please do open another issue and let me know though.

Thanks for letting me know, that works great for me.

**Comment by rayman89** [comment]
Glad to see it´s working. Visibility on this feature is hard to notice though IMO.

**Comment by sergeevabc** [comment]
@rayman89, can't but agree, I spent half an hour to find this tip on how to select multiple tabs (coming from Simple Tab Groups where Shift+select does the trick). Perhaphs the developer should mention it on the addons page of Mozilla.
