### ISSUE TITLE
Stash a page opened from a file

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#64]
### System Details
- **OS Version:** Ubuntu 20.04
- **Browser Version:** Firefox 77.0.1
- **Tab Stash Version:** 2.6

### Describe the Bug
You cannot stash tabs that start with "file:///"

### Expected Behavior
Tabs that are a file are stashable.

### Steps to Reproduce
1. Open a pdf in Firefox
2. Stash it

### Impact
Somewhat.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, unfortunately this isn't possible because Firefox has additional restrictions in place for `file:///` URLs, which are generally granted more permissive access to your system than regular `http[s]://` URLs. Extensions are simply not allowed to open such URLs in tabs due to the potential for abuse (e.g. downloading and then opening a script which could execute arbitrary commands on your computer), and there is no way that I know of for an extension to ask for such permission.

Sorry to be the bearer of bad news. :/

**Comment by EmmanuelMess** [comment]
I shouldn't fail silently then, maybe add a warning when trying to stash such a tab.

**Comment by josh-berry** [comment]
That's a fair point; I'll have to think about how this can be done in a user-friendly way. The complication arises from the fact that users can stash tabs without opening _any_ Tab Stash UI if they set their preferences accordingly, so I will have to see if there's a way I can display some kind of notification using just the browser itself. So I can't promise anything but I'll certainly look at it further.

**Comment by Mikhail-M12** [comment]
OneTab can save `file:///` tabs. (Opening such URLs from OneTab is less convenient than opening regular URL, but possible through right click menu).
OneTab also works with `moz-extension://` tabs (saves and opens them normally) while Tab Stash doesn't.

I was going to replace OneTab with Tab Stash, but lack of support of special tabs stopped me. Please, allow stash tabs with special URLs. It's significant feature. I use tabs with special URLs as separators inside tab groups.

**Comment by josh-berry** [comment]
I've added some code to the next release to allow stashing/restoring of extension pages. Hopefully this helps to address at least some of your concerns.

I'm still thinking on how to deal with other "privileged" URLs like `file:///`, but TBH I'm not optimistic that there's a good solution. I know that OneTab will save file URLs, but to me the fact that you can't restore what you've saved feels like a bug rather than intentional behavior, so I don't want to follow OneTab's approach here. (See for example #27, which is why file URLs are explicitly ignored.)

Since this is only partially fixed, I'll keep it open and keep it in the back of my mind. I hope the above helps though.

**Comment by Mikhail-M12** [comment]
Thank you! I will try the next release.

But I would like to have **option** for stashing (with closing) even those tabs that cannot be unstashed normally.
Idea: such tabs could be restored as dynamically created html-pages with tab link and button "Copy link to clipboard" in it. (It would be better than OneTab's impossibility to normally open such tabs.)
Even without this function, "OneTab's approach" can be preferable. Saving of complete tab group with file-tabs can be useful.

**Comment by josh-berry** [comment]
hm, that's a good idea. Let me experiment and see what I can come up with.

**Comment by josh-berry** [comment]
Alright, I think I have something I'm relatively happy with. @Mikhail-M12 it's basically what you described above—Tab Stash will instead open a page showing the URL with an option to copy it to the clipboard.

It will be in the next release. Hope you like it!

**Comment by Mikhail-M12** [comment]
Thank you very much! Am waiting for the next release to switch from OneTab.
