### ISSUE TITLE
Weird behavior when closing last tab if it is already stashed

### ISSUE THREAD

**Issue by JimBreton** [josh-berry/tab-stash#70]
### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox 77.0.1
- **Tab Stash Version:** 2.6

### Describe the Bug
If I have a window with a bunch of tabs, and stash them all, I am left with just the 'New Tab Page.'  So then if I try to close that tab (which under normal circumstances would close the whole window), that tab flashes closed but then is immediately replaced by one of the recently stashed tabs.  Then if I close THAT tab, the same thing happens, but it's replaced by one of the OTHER recently stashed tabs, and so on -- until I have finally closed all of them, one at a time, after which point the window will finally close.

I think this is because of the tabs being 'Hidden' and the window just keeps presenting you the sequence of hidden tabs when you try to close the window.

If I try to use the 'close box' in the corner of the window it will give me the usual warning about closing multiple tabs.

I suppose some of this behavior makes sense, because the tabs really are still open.  But the behavior of trying to close the last tab is strange and unexpected I think.

### Expected Behavior
The window should close when closing the last tab.

### Steps to Reproduce

1. Open several tabs in a window
2. Stash them all, leaving you with just the NTP
3. Try to close just the NTP
4. Observe that the NTP goes away but is instantly replaced by one of the tabs hidden by Tab Stash

### Impact
Not the end of the world, but would be nice to see behavior more akin to what you'd expect when tabs were not stashed/hidden.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by JimBreton** [comment]
OK, after some more fiddling, it looks like this may have nothing to do with Tab Stash and may just be the way Firefox behaves when you close the last non-hidden tab of a window that still has hidden tabs.  Thoughts?

**Comment by josh-berry** [comment]
Yeah, this is (fortunately or unfortunately) just the way Firefox behaves and has nothing to do with Tab Stash. Since "hidden tabs" is a pretty generic feature for use by a wide variety of extensions, I think the Firefox developers made the trade-off that they didn't want users to be surprised/upset if they lost any hidden tabs unexpectedly (e.g. if you are using some extension which only manages tabs and doesn't save them in any way). But it's unfortunately a bit surprising in Tab Stash's context.

If it bothers you, you can tell Tab Stash to close tabs instead of hiding them in the preferences—in the Tab Stash UI, open the menu (next to the search bar), choose "Options", and under "Tab and Memory Management", choose "Close the tab immediately". The downside is that tabs won't be as quick to restore, and you may lose any unsaved data you've entered into a tab that is being stashed, but this behavior will go away.

Thanks for a nicely-written bug report; I hope this helps!

**Comment by JimBreton** [comment]
Thanks!
