### ISSUE TITLE
Stash all/stash selected dichotomy is unintuitive

### ISSUE THREAD

**Issue by josh-berry** [josh-berry/tab-stash#74]
### Problem Statement
I think having separate buttons for "stash all/selected" vs. "stash one" is rather confusing, and contrary to how most other programs handle the one/many distinction.

### Preferred Solution(s)
The "stash selected" behavior should probably be clubbed with "stash one" instead of "stash all" across these contexts:
* Context menus
* Browser toolbar buttons
* Stash UI

### Additional Context
See also:
* https://addons.mozilla.org/en-US/firefox/addon/tab-stash/reviews/1548598/

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by joshgold22** [comment]
I agree this is important to fix, and does cause me confusion.  (including several occasions of lost work and time from having the command do something different than I expected)

I'll make a number of suggestions that I think are complimentary to the original post, to feed the conversation.

1. Ideal is to change the labels depending if there are one or multiple tabs selected.  Then you would have
Stash Selected Tabs
Copy Selected Tabs to Stash
or
Stash Tab
Copy Tab to Stash

2. (minor) I'd recommend putting the stashing commands at the top, and the commands to open the Stashes views just above Options (It seems more consistent with my expectations, but I'm only saying this on intuition.)

3. Consider a toggle, rather than extra menu item for Copy vs. Stash, since I suspect many users *mostly* do one or the other, for example, a section of the menu below the commands:
------
    Copy
    Hide
    Hide and Unload
✓ Close
------

4. More thought would be good about how to control where (which stash) items go to.  If you like the idea above of moving the copy vs. close distinction, that would create more "room" for that, since you wouldn't have to duplicate for "Copy".  I.e., 

Stash Selected Tabs to "Saved 11/13/20 08:07:13"  (or Stash Tab to ... if only one)
Stash Selected Tabs to New Group
Stash Selected Tabs to -> (submenu of last 6 groups?)
Stash All Tabs in Window  (This could always go to a new group to avoid excess of options.)

(You would still need default behaviors like you have now for the Toolbar button or keyboard shortcut.  I.e., new group or last group, depending on how much time has passed.  I think that's ok.)

5. Also consider unstashing in the context menu
Unstash tabs -> (submenu of last 10 groups?)

(Would it be better to position below the clicked tab or at the bottom?  Perhaps a preference.)

6. URGENT (I didn't realize when I started this comment that Stash Tabs stashes all in the window. I actually lost a bunch of other work by trying it out in the middle of working on this comment!)
Please rename "Stash Tabs" to "Stash All Tabs in This Window".  I expected Stash Tabs to Stash either the Selected Tabs, or just the active tab if it was the only one selected.

7. Don't add submenus if they would require background cpu with large numbers of stashes or unstashed tabs.  (Just limit the context menu to the last group if that's the case.)

**Comment by josh-berry** [comment]
Thanks, there are a lot of good suggestions/feedback here and I really appreciate you taking the time to write it up!

I do want to revisit how stashing, toolbar buttons, menus etc. work but that will probably be a project for a major release like 3.0, since it's a bigger change to the look and feel, and I want to take the time to get it right. But I will definitely keep all of this in mind when the time comes. And if you have more observations over time related to stashing behavior, please continue to share. :)

**Comment by joshgold22** [comment]
That sounds good.  I would still nudge you to add "All" right away as an interim fix for now, though.  (Stash Tabs -> Stash All Tabs in Window)

**Comment by josh-berry** [comment]
> I would still nudge you to add "All" right away as an interim fix for now, though. (Stash Tabs -> Stash All Tabs in Window)

Filed #98 for this. Might take some work (menus etc. need to be dynamic/update when selection changes, whereas right now they are generated once at startup) but I'll see what I can do.

**Comment by josh-berry** [comment]
Cleaned up the toolbar button UI a bit in the next release of Tab Stash, so I'm going to call this "finished". (#98 is still open for the context-menu stuff, though.)
