### ISSUE TITLE
Does Tab Stash sync tabs between multiple computers/Firefox installations?

### ISSUE THREAD

**Issue by 8thHalfHour** [josh-berry/tab-stash#92]
### Question

Does Tab Stash sync tabs between multiple computers/Firefox installations?

### System Details

- **OS Version:** Win 10 Pro
- **Browser Version:** Firefox 81.0 (64-bit)
- **Tab Stash Version:** 2.6

**Comment by josh-berry** [comment]
Hi, yes it does, by way of Firefox Sync (there is no separate syncing service).

Tab Stash will save your tabs to a "Tab Stash" folder in your bookmarks. So long as you have Firefox Sync turned on and configured to sync your bookmarks, your tabs will be synced between computers.

There's one important caveat though: because it uses your bookmarks, Tab Stash only saves the URLs, not the *content* of the tabs themselves. For example, if you start writing a comment in a forum (or on GitHub for that matter), your comment would not be synced. Tab Stash cannot see into the page to save whatever you have typed--it just knows that you were looking at that page.

**Comment by josh-berry** [comment]
I hope the above answered your question--I'm going to close this out but please feel free to leave another comment or open a new issue if you have any more questions!
