### ISSUE TITLE
Stashed tab titles not correctly captured (showing "Importing..." or "Stashing..."

### ISSUE THREAD

**Issue by nafarinha** [josh-berry/tab-stash#96]
### System Details

- **OS Version:** macOS 10.14.6 Mojave
- **Browser Version:** Firefox 82.0.2
- **Tab Stash Version:** 2.7

**Installed Browser Extensions:**

- OneTab
- 

### Describe the Bug

All these stashed tabs were originally created on a previous version of Tab Stash (2.6 most probably).
The ones with the name "Importing..." were generated by importing from OneTab.
These bookmarks have correctly kept the URL, only the names are missing.

The ones with the name "Stashing...", if I'm not mistaken, were created using a few dozen opened tabs and trying to stash them to test the addon.
These don't seem to have saved the URL correctly. The URL stored look like this about:blank#stashing--LQ0QuSjQYaD-10

### Expected Behavior
Have the stashed tabs stored with the the correct name.
Ideally, have a way to rebuild bookmark titles by fetching through the URL stored, like the Fetch missing Icons.

### Steps to Reproduce

The bookmarks with these issues were created on a version before 2.7, probably 2.6. I've tested 2.7 by importing from OneTab and I wasn't able to reproduce the problem with the titles. But I'm unable to fix the existing issues on 2.7.

### Impact

I tried using the "Fetch Missing Icons" as it could perhaps also update the bookmark names but to no avail.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Yikes, sorry for the inconvenience!

I did find a bug in 2.7 late last night (of course, shortly after I released it...) where website info for imports and missing icons might not get fetched correctly. I have a fix for this in progress and will try to release a 2.7.1 for it very soon.

Can you clarify if both the "Stashing" and "Importing" tabs were originally added to Tab Stash via import? Or did the "Stashing..." tabs come through clicking one of the "stash" toolbar buttons (either in the Firefox toolbar or the Tab Stash UI)?

If it was through the stash toolbar button, can you please try to collect error logs? It may be there is a different problem with stashing specifically. Here's how to collect logs: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

**Comment by josh-berry** [comment]
I went ahead and pushed out a fix for the import issue I found last night. Can you please try again with 2.7.1 and let me know if you're still running into the issue with import?

**Comment by nafarinha** [comment]
Hi Josh, no worries:) 
The "importing..." tabs were grandfathered from 2.6 while trying to import a few dozen of tabs from OneTab.
The "stashing..." tabs were also from 2.6 but in this case were from active tabs opened on Firefox.

I can't replicate these issues on 2.7.1 anymore. I can only try to open them. Would that still be useful to you if I send the error logs?

**Comment by josh-berry** [comment]
Glad to hear 2.7.1 fixed the issues for you!

For the "Stashing..." tabs left over from 2.6, the logs from the actual stashing operation have probably been lost (Firefox clears the logs on extension updates and on browser restart). But if you see it happen again, logs would be a huge help. Any that have `about:blank...` URLs you won't be able to open; feel free to delete those. Since the stashing didn't complete, the tabs themselves should have stayed open (such that you wouldn't actually lose anything), but if that's not the case, please let me know so I can look into it further.

Also, if there are any stashed tabs that have proper URLs but you can't open them, I'd love to see the logs.

Finally, for any of the "Importing..." or "Stashing..." tabs that have correct URLs but incorrect titles, you can try copying them from "Export..." and pasting into "Import...", and Tab Stash should fetch the correct titles/icons ("Import" only looks at the URLs) when it re-imports them.

Hope the above helps and let me know what you find!

**Comment by josh-berry** [comment]
I'm going to go ahead and close this out, but please do let me know if you're still seeing issues with tabs stuck in "Stashing..." or "Importing..." in 2.7.1 or later. Thanks again for the bug report!
